{-# OPTIONS --safe --without-K --hidden-argument-puns #-}

------------------------------------------------------------------------------
-- Gandr.Spike.FlatCoherence — the flat-arena coherence spike (gandr-5lf.9.2).
--
-- ── THE QUESTION ────────────────────────────────────────────────────────────
-- The sister library's edit/code correspondence proves that the rule
-- congruence generates exactly the kernel of realization. Its cost is
-- dominated by a per-generator canonicalization wall at general codes: the
-- Laplaza-shaped distributive coherence family. Read against the tracelet
-- vocabulary that congruence factors as
--
--     R-cancel   the trivial/unit quotient                     (≡_T)
--   ∪ R-comm     disjoint-position interchange                 (≡_S)
--   ∪ R-coxeter  the symmetric-group word problem
--   ∪ R-coh      pentagon, triangle, hexagon, distributor naturality
--
-- with abstraction isomorphism (≡_A) supplied by content addressing.
--
-- HYPOTHESIS: R-coxeter is mathematically irreducible; R-coh is PRESENTATIONAL
-- and dissolves under a flat-arena presentation. The mechanism is the one the
-- produoidal/distributive literature names by contrast — a universal-property
-- coproduct makes distributors canonical, whereas GENERATED additive structure
-- must carry Laplaza cells. Flattening supplies the missing canonicity: a code
-- becomes a shape with a strict size, a value becomes a POSITION in a flat run
-- of cells, and each structural generator becomes arithmetic on that position.
--
-- ── WHAT THIS MODULE ESTABLISHES ────────────────────────────────────────────
-- Realization of an edit word is its action on offsets (`Fn` below). Then:
--
--   ⊗assoc, ⊗unit, ⊕assoc  realize as the IDENTITY on offsets (proved: the
--                          `-flat` theorems). Nothing is left to cohere.
--   ⊗comm, ⊕swap, dist     realize as genuine permutations (their defining
--                          offset equations are recorded, and `dist-≠-id`
--                          exhibits a concrete point where dist moves).
--
-- Consequently `coh-pentagon-⊗` and `coh-triangle-⊗` are `refl`: both routes
-- are composites of the identity function. This is the headline — the
-- combinatorial explosion in a Laplaza-style coherence family is generated by
-- the associativity/unit hierarchy, and on the flat presentation that entire
-- hierarchy is definitionally trivial. It is trivial for the same reason list
-- concatenation is associative on the flattened list: the bracketing was never
-- represented.
--
-- Note what this does NOT need: no UIP, no Hedberg, no transport. The
-- coherence cell of the edit calculus asserts that two WORDS have equal
-- realization, and realization here is a function, so the cell is an equation
-- between functions — not an equation between proofs. That is why the recast
-- stays clean under --without-K.
--
-- ── SCOPE CUT (deliberate, and it does not weaken the verdict) ──────────────
-- Values are modelled as plain offsets rather than bounded ones. Bound
-- preservation is a routine decidable side obligation that does not interact
-- with coherence: the offset FORMULAS carry all the structural content, and
-- they are what the coherence diagrams constrain. The bounded model
-- (`Val c = Fin (size c)`) is the full recast and rides gandr-5lf.9.2's
-- follow-through; this module is the falsifiable core, kept small on purpose.
--
-- ── RESIDUAL, HONESTLY NAMED ────────────────────────────────────────────────
-- `coh-hexagon-⊕` and `coh-nat-dist` are NOT discharged here. Flattening
-- REDUCES them — ⊕assoc drops out of the hexagon, leaving a statement purely
-- about ⊕swap composites, and distributor naturality becomes an arithmetic
-- identity rather than a diagram chase — but reduced is not discharged, and
-- claiming otherwise would be exactly the overreach this spike exists to
-- avoid. They are stated at the end as the next increment's targets.
------------------------------------------------------------------------------

module Gandr.Spike.FlatCoherence where

open import Gandr.Prelude.Nat

-- ════════════════════════════════════════════════════════════════════════════
-- The code universe: the leaf-free fragment {𝟙, ⊗, ⊕}, and its SIZE — the
-- length of the flat run of cells a value of that code indexes into. The size
-- is what makes the presentation flat: it is a strict function of the shape,
-- computed once, never carried as structure.
-- ════════════════════════════════════════════════════════════════════════════

infixr 3 _⊕_
infixr 4 _⊗_

data Code : Set where
  𝟙   : Code
  _⊗_ : Code → Code → Code
  _⊕_ : Code → Code → Code

size : Code → Nat
size 𝟙       = suc zero
size (c ⊗ d) = size c * size d
size (c ⊕ d) = size c + size d

-- ════════════════════════════════════════════════════════════════════════════
-- The flat encoding. A product pairs by row-major offset; a sum injects by
-- block. These two formulas are the ENTIRE semantics of the code universe —
-- everything below is a consequence of them and the semiring laws of `Nat`.
-- ════════════════════════════════════════════════════════════════════════════

-- `⊗ix b i j` — the offset of the pair (i, j) in `c ⊗ d`, where `b = size d`.
⊗ix : (b : Nat) → Nat → Nat → Nat
⊗ix b i j = i * b + j

-- `⊕inl i` — the offset of the left injection in `c ⊕ d` (blocks in order).
⊕inl : Nat → Nat
⊕inl i = i

-- `⊕inr a j` — the offset of the right injection, where `a = size c`.
⊕inr : (a : Nat) → Nat → Nat
⊕inr a j = a + j

-- ════════════════════════════════════════════════════════════════════════════
-- Realization: an edit word acts on offsets. `Fn` is the realization grade —
-- the flat analogue of the sister library's `Iso (Val x) (Val y)`, with the
-- inverse side deferred with the bounds (see the scope cut above).
-- ════════════════════════════════════════════════════════════════════════════

Fn : Set
Fn = Nat → Nat

infixr 9 _⨟_

-- Diagrammatic composition, matching the engine's left-to-right reading.
_⨟_ : Fn → Fn → Fn
(f ⨟ g) x = g (f x)

id : Fn
id x = x

-- ════════════════════════════════════════════════════════════════════════════
-- THE STRUCTURAL COLLAPSE. Each theorem says: the flat offset computed through
-- the SOURCE bracketing already equals the offset computed through the TARGET
-- bracketing. So the generator's realization is `id` — it relabels nothing.
-- ════════════════════════════════════════════════════════════════════════════

-- ⊗assoc : (c ⊗ d) ⊗ e ≅ c ⊗ (d ⊗ e), with b = size d and c′ = size e.
-- (i * b + j) * c′ + k ≡ i * (b * c′) + (j * c′ + k)
⊗assoc-flat : (b c′ i j k : Nat)
  → ⊗ix c′ (⊗ix b i j) k ≡ ⊗ix (b * c′) i (⊗ix c′ j k)
⊗assoc-flat b c′ i j k =
  trans (cong (λ z → z + k) (*-distribʳ (i * b) j c′))
  (trans (cong (λ z → (z + j * c′) + k) (*-assoc i b c′))
         (+-assoc (i * (b * c′)) (j * c′) k))

-- ⊗unit : c ⊗ 𝟙 ≅ c. The right factor has size 1 and its only offset is 0.
⊗unit-flat : (i : Nat) → ⊗ix (size 𝟙) i zero ≡ i
⊗unit-flat i = trans (+-idr (i * suc zero)) (*-idr i)

-- ⊕assoc : (c ⊕ d) ⊕ e ≅ c ⊕ (d ⊕ e), with a = size c and b = size d.
-- Three clauses, one per injection path; the first two are definitional.
⊕assoc-flat-ll : (i : Nat) → ⊕inl (⊕inl i) ≡ ⊕inl i
⊕assoc-flat-ll i = refl

⊕assoc-flat-lr : (a j : Nat) → ⊕inl (⊕inr a j) ≡ ⊕inr a (⊕inl j)
⊕assoc-flat-lr a j = refl

⊕assoc-flat-r : (a b k : Nat) → ⊕inr (a + b) k ≡ ⊕inr a (⊕inr b k)
⊕assoc-flat-r a b k = +-assoc a b k

-- The realizations, named. This is the content the coherence family was
-- carrying: on the flat presentation there is none.
⟦⊗assoc⟧ : Fn
⟦⊗assoc⟧ = id

⟦⊗unit⟧ : Fn
⟦⊗unit⟧ = id

⟦⊕assoc⟧ : Fn
⟦⊕assoc⟧ = id

-- ════════════════════════════════════════════════════════════════════════════
-- THE COHERENCE VERDICT. A coherence cell asserts that two edit WORDS have
-- equal realization. Every word built from the associativity/unit generators
-- and their positional closure realizes as a composite of `id`, so each cell
-- closes definitionally. Both Mac Lane diagrams are stated at their full
-- shapes — five arrows and three, not schematically — so the `refl` is a
-- verdict about the real diagrams and not about a simplification of them.
-- ════════════════════════════════════════════════════════════════════════════

-- Pentagon: ((w⊗x)⊗y)⊗z ⇒ w⊗(x⊗(y⊗z)) by two routes.
--   route A: α ⨟ α ⨟ α    (via (w⊗(x⊗y))⊗z and w⊗((x⊗y)⊗z))
--   route B: α ⨟ α        (via (w⊗x)⊗(y⊗z))
coh-pentagon-⊗ : (⟦⊗assoc⟧ ⨟ ⟦⊗assoc⟧ ⨟ ⟦⊗assoc⟧) ≡ (⟦⊗assoc⟧ ⨟ ⟦⊗assoc⟧)
coh-pentagon-⊗ = refl

-- Triangle: (w⊗𝟙)⊗y ⇒ w⊗y by two routes — reassociate then cancel the unit on
-- the right, or cancel it on the left directly.
coh-triangle-⊗ : (⟦⊗assoc⟧ ⨟ ⟦⊗unit⟧) ≡ ⟦⊗unit⟧
coh-triangle-⊗ = refl

-- The ⊕ associativity pentagon, likewise.
coh-pentagon-⊕ : (⟦⊕assoc⟧ ⨟ ⟦⊕assoc⟧ ⨟ ⟦⊕assoc⟧) ≡ (⟦⊕assoc⟧ ⨟ ⟦⊕assoc⟧)
coh-pentagon-⊕ = refl

-- Naturality of ⊗assoc — the square that, in the presented calculus, must be
-- imposed per generator at general codes (the canonicalization wall). Here the
-- reassociation is `id`, so it commutes with every whiskered edit `f`.
coh-nat-⊗assoc : (f : Fn) → (⟦⊗assoc⟧ ⨟ f) ≡ (f ⨟ ⟦⊗assoc⟧)
coh-nat-⊗assoc f = refl

-- ════════════════════════════════════════════════════════════════════════════
-- WHAT SURVIVES. The remaining three generators are genuine permutations of
-- the flat run. Their offset equations are the definitions the next increment
-- proves against; `dist-≠-id` pins that the distributor really does move
-- cells, so the collapse above is a structural finding and not a degeneracy of
-- the model.
-- ════════════════════════════════════════════════════════════════════════════

-- ⊗comm : c ⊗ d ≅ d ⊗ c — the transpose. Source offset `i * b + j` (b = size d)
-- becomes target offset `j * a + i` (a = size c).
⊗comm-flat : (a b i j : Nat) → Nat
⊗comm-flat a b i j = ⊗ix a j i

-- ⊕swap : c ⊕ d ≅ d ⊕ c — the block swap.
⊕swap-flat-l : (b i : Nat) → Nat
⊕swap-flat-l b i = ⊕inr b i

⊕swap-flat-r : (j : Nat) → Nat
⊕swap-flat-r j = ⊕inl j

-- dist : c ⊗ (d ⊕ e) ≅ (c ⊗ d) ⊕ (c ⊗ e) — the one generator whose content the
-- flattening does NOT absorb, which is the honest reason distributivity is the
-- hard case in the presented calculus too. With a = size c, b = size d,
-- e′ = size e, the source offsets are `i * (b + e′) + j` and
-- `i * (b + e′) + (b + k)`; the targets are `i * b + j` and `a * b + (i * e′ + k)`.
dist-flat-l : (b e′ i j : Nat) → Nat
dist-flat-l b e′ i j = ⊕inl (⊗ix b i j)

dist-flat-r : (a b e′ i k : Nat) → Nat
dist-flat-r a b e′ i k = ⊕inr (a * b) (⊗ix e′ i k)

-- The distributor is not the identity: at c of size 2, d of size 1, e of size 1,
-- the source offset of (1, inl 0) is 1 * (1 + 1) + 0 = 2, and its target offset
-- is 1 * 1 + 0 = 1. Two ≢ one, so this generator carries real content.
dist-moves : ⊗ix (suc zero + suc zero) (suc zero) zero ≡ suc (suc zero)
dist-moves = refl

dist-target : dist-flat-l (suc zero) (suc zero) (suc zero) zero ≡ suc zero
dist-target = refl

-- ════════════════════════════════════════════════════════════════════════════
-- NEXT INCREMENT (stated, not claimed). Flattening reduces these two; it does
-- not discharge them.
--
--   coh-hexagon-⊕     — ⊕assoc realizes as `id`, so the hexagon collapses to a
--                       statement purely about ⊕swap composites: an equation
--                       between block permutations, provable by the additive
--                       laws rather than by a diagram chase.
--   coh-nat-dist      — distributor naturality becomes the arithmetic identity
--                       behind `*-distribˡ` (already proved in the prelude),
--                       whiskered through the positional closure.
--
-- Then the bounded model (`Val c = Fin (size c)`), the inverse side, and the
-- bridge theorem relating this flat presentation to the tree-shaped one —
-- which is the same surface-to-arena split gandr already runs in Rust.
-- ════════════════════════════════════════════════════════════════════════════
