{-# OPTIONS --safe --without-K --hidden-argument-puns #-}

------------------------------------------------------------------------------
-- Gandr.Arena.Structure — the six structural generators, and which of them
-- carry content.
--
-- ── THE FINDING ─────────────────────────────────────────────────────────────
-- The presented (tree-shaped) edit calculus must impose a Laplaza-shaped
-- coherence family, and its cost centre is a per-generator canonicalization
-- wall at general codes. That family is generated by the associativity/unit
-- hierarchy. On the flat arena that hierarchy is RIGID: `⊗assoc`, `⊗unitl`,
-- `⊗unitr`, `⊕assoc` and their inverses move no cell — each is the identity
-- on offsets, certified by `Rigid.fixed`.
--
-- Rigidity is not a property of individual diagrams but a CLOSED CLASS: it
-- survives composition (`rigid-∘`) and whiskering (`rigid-⊗`, `rigid-⊕`), so
-- every word in the hierarchy is rigid however deeply it is applied. That is
-- what Gandr.Arena.Coherence cashes in: any two parallel rigid words agree,
-- with no diagram imposed and no coherence cell to normalize past.
--
-- ── WHAT SURVIVES ───────────────────────────────────────────────────────────
-- `⊗comm`, `⊕swap` and `dist` are NOT rigid, and `dist-moves` exhibits a
-- concrete cell the distributor relocates. So the collapse above is a
-- structural finding about which generators carry content, not a degeneracy
-- of a model that trivializes everything. These three are the arena's real
-- permutation content — the part a normalizer must actually compute.
--
-- ── THE INVERSE SIDE ────────────────────────────────────────────────────────
-- Every generator here is invertible, and the two halves are proved
-- differently, which is itself the finding restated. The rigid generators are
-- inverted for FREE: `rigid-inv` says any rigid map back inverts any rigid map
-- out, because both are the identity on offsets and `Fin` is discrete. The
-- surviving three need their own round trips (`⊗comm-invol`, `⊕swap-invol`,
-- `dist-undist`, `undist-dist`) because they genuinely permute.
------------------------------------------------------------------------------

module Gandr.Arena.Structure where

open import Gandr.Arena.Code
open import Gandr.Arena.Offset
open import Gandr.Arena.Value
open import Gandr.Prelude.Data
open import Gandr.Prelude.Equality
open import Gandr.Prelude.Fin
open import Gandr.Prelude.Nat

-- ════════════════════════════════════════════════════════════════════════════
-- The unit code is a singleton. Needed by both unitors: cancelling a unit is
-- only well defined because the factor being dropped carried no information.
-- ════════════════════════════════════════════════════════════════════════════

𝟙-η : (x : Val 𝟙) → x ≡ unit
𝟙-η (cell fzero) = refl

-- ════════════════════════════════════════════════════════════════════════════
-- THE RIGID CLASS. A rigid map relabels nothing: it carries a value to the
-- value at the SAME offset under a different code. `ext` records that the two
-- codes have the same extent, which is what makes rigidity survive whiskering
-- — inside a product, a factor's extent is the block width the OTHER factor's
-- offset is scaled by.
-- ════════════════════════════════════════════════════════════════════════════

record Rigid (c d : Code) : Set where
  constructor rigid
  field
    -- The relabelling.
    app   : Val c → Val d
    -- Source and target span the same run of cells.
    ext   : size c ≡ size d
    -- …and the relabelling is the identity on that run.
    fixed : (x : Val c) → app x ≐ x

open Rigid public

-- ── Closure ─────────────────────────────────────────────────────────────────

-- The identity is rigid.
rigid-id : {c : Code} → Rigid c c
rigid-id = rigid (λ x → x) refl (λ x → refl)

-- Rigidity composes. Diagrammatic order: `rigid-∘ r s` runs `r` then `s`.
rigid-∘ : {c d e : Code} → Rigid c d → Rigid d e → Rigid c e
rigid-∘ r s =
  rigid (λ x → app s (app r x))
        (trans (ext r) (ext s))
        (λ x → trans (fixed s (app r x)) (fixed r x))

-- Whiskering a rigid map into a product preserves rigidity. This is the step
-- the presented calculus cannot take for free: there, a reassociation deep in
-- a code must be slid past every generator between it and the root.
⊗map-fixed
  : {c c′ d d′ : Code}
  → (f : Val c → Val c′) (g : Val d → Val d′)
  → size d ≡ size d′
  → ((u : Val c) → f u ≐ u)
  → ((v : Val d) → g v ≐ v)
  → (x : Val (c ⊗ d)) → ⊗map f g x ≐ x
⊗map-fixed {c} {c′} {d} {d′} f g e hf hg =
  ⊗-ind (⊗map {c} {c′} {d} {d′} f g) (λ x → x)
    (λ u v →
      trans (≡-≐ (⊗map-pair f g u v))
      (trans (ix-pair {c′} {d′} (f u) (g v))
      (trans (cong₂ (⊗ix (size d′)) (hf u) (hg v))
      (trans (cong (λ z → ⊗ix z (ix u) (ix v)) (sym e))
             (sym (ix-pair {c} {d} u v))))))

-- The same, for a sum.
⊕map-fixed
  : {c c′ d d′ : Code}
  → (f : Val c → Val c′) (g : Val d → Val d′)
  → size c ≡ size c′
  → ((u : Val c) → f u ≐ u)
  → ((v : Val d) → g v ≐ v)
  → (x : Val (c ⊕ d)) → ⊕map f g x ≐ x
⊕map-fixed {c} {c′} {d} {d′} f g e hf hg =
  ⊕-ind (⊕map {c} {c′} {d} {d′} f g) (λ x → x)
    (λ i →
      trans (≡-≐ (⊕map-inl f g i))
      (trans (ix-inl {c′} {d′} (f i))
      (trans (hf i)
             (sym (ix-inl {c} {d} i)))))
    (λ j →
      trans (≡-≐ (⊕map-inr f g j))
      (trans (ix-inr {c′} {d′} (g j))
      (trans (cong₂ ⊕ixʳ (sym e) (hg j))
             (sym (ix-inr {c} {d} j)))))

rigid-⊗ : {c c′ d d′ : Code} → Rigid c c′ → Rigid d d′ → Rigid (c ⊗ d) (c′ ⊗ d′)
rigid-⊗ r s =
  rigid (⊗map (app r) (app s))
        (cong₂ _*_ (ext r) (ext s))
        (⊗map-fixed (app r) (app s) (ext s) (fixed r) (fixed s))

rigid-⊕ : {c c′ d d′ : Code} → Rigid c c′ → Rigid d d′ → Rigid (c ⊕ d) (c′ ⊕ d′)
rigid-⊕ r s =
  rigid (⊕map (app r) (app s))
        (cong₂ _+_ (ext r) (ext s))
        (⊕map-fixed (app r) (app s) (ext r) (fixed r) (fixed s))

-- ── What rigidity buys ──────────────────────────────────────────────────────

-- Two rigid maps between the same codes are the SAME map. Not merely equal at
-- the grade: `Fin` is discrete on its offset, so this is equality of values.
rigid-unique : {c d : Code} (r s : Rigid c d) (x : Val c) → app r x ≡ app s x
rigid-unique r s x = ≐-≡ (trans (fixed r x) (sym (fixed s x)))

-- A rigid map is inverted by ANY rigid map back. The inverse side of the whole
-- associativity/unit hierarchy is this one line.
rigid-inv : {c d : Code} (r : Rigid c d) (s : Rigid d c) (x : Val c) → app s (app r x) ≡ x
rigid-inv r s x = ≐-≡ (trans (fixed s (app r x)) (fixed r x))

-- ════════════════════════════════════════════════════════════════════════════
-- THE HIERARCHY. Each generator is defined by decomposing and rebuilding, so
-- its β-rule is a consequence of the arena's β-rules and nothing else.
-- ════════════════════════════════════════════════════════════════════════════

-- ── ⊗ associator ────────────────────────────────────────────────────────────

-- Rebuild a left-nested product as a right-nested one.
⊗assoc-on : {c d e : Code} → Val c × Val d → Val e → Val (c ⊗ (d ⊗ e))
⊗assoc-on p w = pair (proj₁ p) (pair (proj₂ p) w)

⊗assoc : {c d e : Code} → Val ((c ⊗ d) ⊗ e) → Val (c ⊗ (d ⊗ e))
⊗assoc x = ⊗assoc-on (⊗split (proj₁ (⊗split x))) (proj₂ (⊗split x))

⊗assoc-pair
  : {c d e : Code} (u : Val c) (v : Val d) (w : Val e)
  → ⊗assoc (pair (pair u v) w) ≡ pair u (pair v w)
⊗assoc-pair u v w =
  trans (cong (λ p → ⊗assoc-on (⊗split (proj₁ p)) (proj₂ p)) (⊗split-pair (pair u v) w))
        (cong (λ p → ⊗assoc-on p w) (⊗split-pair u v))

-- Rebuild a right-nested product as a left-nested one.
⊗assoc⁻¹-on : {c d e : Code} → Val c → Val d × Val e → Val ((c ⊗ d) ⊗ e)
⊗assoc⁻¹-on u q = pair (pair u (proj₁ q)) (proj₂ q)

⊗assoc⁻¹ : {c d e : Code} → Val (c ⊗ (d ⊗ e)) → Val ((c ⊗ d) ⊗ e)
⊗assoc⁻¹ x = ⊗assoc⁻¹-on (proj₁ (⊗split x)) (⊗split (proj₂ (⊗split x)))

⊗assoc⁻¹-pair
  : {c d e : Code} (u : Val c) (v : Val d) (w : Val e)
  → ⊗assoc⁻¹ (pair u (pair v w)) ≡ pair (pair u v) w
⊗assoc⁻¹-pair u v w =
  trans (cong (λ p → ⊗assoc⁻¹-on (proj₁ p) (⊗split (proj₂ p))) (⊗split-pair u (pair v w)))
        (cong (⊗assoc⁻¹-on u) (⊗split-pair v w))

-- THE COLLAPSE, product side: reassociating names the same cell. This is the
-- statement the whole spike turns on, and its proof is `⊗ix-assoc` — the
-- semiring law — whiskered through the arena's β-rules.
⊗assoc-fixed
  : {c d e : Code} (x : Val ((c ⊗ d) ⊗ e)) → ⊗assoc x ≐ x
⊗assoc-fixed {c} {d} {e} =
  ⊗-ind ⊗assoc (λ x → x)
    (λ y w →
      ⊗-ind (λ z → ⊗assoc (pair z w)) (λ z → pair z w)
        (λ u v →
          trans (≡-≐ (⊗assoc-pair u v w))
          (trans (ix-pair u (pair v w))
          (trans (cong (⊗ix (size d * size e) (ix u)) (ix-pair v w))
          (trans (sym (⊗ix-assoc (size d) (size e) (ix u) (ix v) (ix w)))
          (trans (cong (λ z → ⊗ix (size e) z (ix w)) (sym (ix-pair u v)))
                 (sym (ix-pair (pair u v) w)))))))
        y)

⊗assoc⁻¹-fixed
  : {c d e : Code} (x : Val (c ⊗ (d ⊗ e))) → ⊗assoc⁻¹ x ≐ x
⊗assoc⁻¹-fixed {c} {d} {e} =
  ⊗-ind ⊗assoc⁻¹ (λ x → x)
    (λ u y →
      ⊗-ind (λ z → ⊗assoc⁻¹ (pair u z)) (λ z → pair u z)
        (λ v w →
          trans (≡-≐ (⊗assoc⁻¹-pair u v w))
          (trans (ix-pair (pair u v) w)
          (trans (cong (λ z → ⊗ix (size e) z (ix w)) (ix-pair u v))
          (trans (⊗ix-assoc (size d) (size e) (ix u) (ix v) (ix w))
          (trans (cong (⊗ix (size d * size e) (ix u)) (sym (ix-pair v w)))
                 (sym (ix-pair u (pair v w))))))))
        y)

rigid-⊗assoc : {c d e : Code} → Rigid ((c ⊗ d) ⊗ e) (c ⊗ (d ⊗ e))
rigid-⊗assoc {c} {d} {e} = rigid ⊗assoc (*-assoc (size c) (size d) (size e)) ⊗assoc-fixed

rigid-⊗assoc⁻¹ : {c d e : Code} → Rigid (c ⊗ (d ⊗ e)) ((c ⊗ d) ⊗ e)
rigid-⊗assoc⁻¹ {c} {d} {e} =
  rigid ⊗assoc⁻¹ (sym (*-assoc (size c) (size d) (size e))) ⊗assoc⁻¹-fixed

-- ── ⊗ unitors ───────────────────────────────────────────────────────────────

⊗unitr : {c : Code} → Val (c ⊗ 𝟙) → Val c
⊗unitr x = proj₁ (⊗split x)

⊗unitr⁻¹ : {c : Code} → Val c → Val (c ⊗ 𝟙)
⊗unitr⁻¹ u = pair u unit

⊗unitr-pair : {c : Code} (u : Val c) (z : Val 𝟙) → ⊗unitr (pair u z) ≡ u
⊗unitr-pair u z = cong proj₁ (⊗split-pair u z)

⊗unitr-fixed : {c : Code} (x : Val (c ⊗ 𝟙)) → ⊗unitr x ≐ x
⊗unitr-fixed =
  ⊗-ind ⊗unitr (λ x → x)
    (λ u z →
      trans (≡-≐ (⊗unitr-pair u z))
      (trans (sym (⊗ix-unitʳ (ix u)))
      (trans (cong (⊗ix (suc zero) (ix u)) (sym (cong ix (𝟙-η z))))
             (sym (ix-pair u z)))))

⊗unitr⁻¹-fixed : {c : Code} (u : Val c) → ⊗unitr⁻¹ u ≐ u
⊗unitr⁻¹-fixed u = trans (ix-pair u unit) (⊗ix-unitʳ (ix u))

rigid-⊗unitr : {c : Code} → Rigid (c ⊗ 𝟙) c
rigid-⊗unitr {c} = rigid ⊗unitr (*-identityʳ (size c)) ⊗unitr-fixed

rigid-⊗unitr⁻¹ : {c : Code} → Rigid c (c ⊗ 𝟙)
rigid-⊗unitr⁻¹ {c} = rigid ⊗unitr⁻¹ (sym (*-identityʳ (size c))) ⊗unitr⁻¹-fixed

⊗unitl : {c : Code} → Val (𝟙 ⊗ c) → Val c
⊗unitl x = proj₂ (⊗split x)

⊗unitl⁻¹ : {c : Code} → Val c → Val (𝟙 ⊗ c)
⊗unitl⁻¹ v = pair unit v

⊗unitl-pair : {c : Code} (z : Val 𝟙) (v : Val c) → ⊗unitl (pair z v) ≡ v
⊗unitl-pair z v = cong proj₂ (⊗split-pair z v)

⊗unitl-fixed : {c : Code} (x : Val (𝟙 ⊗ c)) → ⊗unitl x ≐ x
⊗unitl-fixed {c} =
  ⊗-ind ⊗unitl (λ x → x)
    (λ z v →
      trans (≡-≐ (⊗unitl-pair z v))
      (trans (sym (⊗ix-unitˡ (size c) (ix v)))
      (trans (cong (λ t → ⊗ix (size c) t (ix v)) (sym (cong ix (𝟙-η z))))
             (sym (ix-pair z v)))))

⊗unitl⁻¹-fixed : {c : Code} (v : Val c) → ⊗unitl⁻¹ v ≐ v
⊗unitl⁻¹-fixed {c} v = trans (ix-pair unit v) (⊗ix-unitˡ (size c) (ix v))

rigid-⊗unitl : {c : Code} → Rigid (𝟙 ⊗ c) c
rigid-⊗unitl {c} = rigid ⊗unitl (*-identityˡ (size c)) ⊗unitl-fixed

rigid-⊗unitl⁻¹ : {c : Code} → Rigid c (𝟙 ⊗ c)
rigid-⊗unitl⁻¹ {c} = rigid ⊗unitl⁻¹ (sym (*-identityˡ (size c))) ⊗unitl⁻¹-fixed

-- ── ⊕ associator ────────────────────────────────────────────────────────────

⊕assoc : {c d e : Code} → Val ((c ⊕ d) ⊕ e) → Val (c ⊕ (d ⊕ e))
⊕assoc x = [ (λ y → [ inl , (λ v → inr (inl v)) ]′ (⊕split y)) , (λ w → inr (inr w)) ]′ (⊕split x)

⊕assoc-inl-inl
  : {c d e : Code} (i : Val c) → ⊕assoc {c} {d} {e} (inl (inl i)) ≡ inl i
⊕assoc-inl-inl {c} {d} i =
  trans (cong [ (λ y → [ inl , (λ v → inr (inl v)) ]′ (⊕split y)) , (λ w → inr (inr w)) ]′
              (⊕split-inl (inl {c} {d} i)))
        (cong [ inl , (λ v → inr (inl v)) ]′ (⊕split-inl i))

⊕assoc-inl-inr
  : {c d e : Code} (j : Val d) → ⊕assoc {c} {d} {e} (inl (inr j)) ≡ inr (inl j)
⊕assoc-inl-inr {c} {d} j =
  trans (cong [ (λ y → [ inl , (λ v → inr (inl v)) ]′ (⊕split y)) , (λ w → inr (inr w)) ]′
              (⊕split-inl (inr {c} {d} j)))
        (cong [ inl , (λ v → inr (inl v)) ]′ (⊕split-inr j))

⊕assoc-inr
  : {c d e : Code} (k : Val e) → ⊕assoc {c} {d} {e} (inr k) ≡ inr (inr k)
⊕assoc-inr k =
  cong [ (λ y → [ inl , (λ v → inr (inl v)) ]′ (⊕split y)) , (λ w → inr (inr w)) ]′
       (⊕split-inr k)

⊕assoc⁻¹ : {c d e : Code} → Val (c ⊕ (d ⊕ e)) → Val ((c ⊕ d) ⊕ e)
⊕assoc⁻¹ x =
  [ (λ i → inl (inl i)) , (λ y → [ (λ v → inl (inr v)) , inr ]′ (⊕split y)) ]′ (⊕split x)

⊕assoc⁻¹-inl
  : {c d e : Code} (i : Val c) → ⊕assoc⁻¹ {c} {d} {e} (inl i) ≡ inl (inl i)
⊕assoc⁻¹-inl i =
  cong [ (λ i′ → inl (inl i′)) , (λ y → [ (λ v → inl (inr v)) , inr ]′ (⊕split y)) ]′
       (⊕split-inl i)

⊕assoc⁻¹-inr-inl
  : {c d e : Code} (j : Val d) → ⊕assoc⁻¹ {c} {d} {e} (inr (inl j)) ≡ inl (inr j)
⊕assoc⁻¹-inr-inl {c} {d} {e} j =
  trans (cong [ (λ i′ → inl (inl i′)) , (λ y → [ (λ v → inl (inr v)) , inr ]′ (⊕split y)) ]′
              (⊕split-inr (inl {d} {e} j)))
        (cong [ (λ v → inl (inr v)) , inr ]′ (⊕split-inl j))

⊕assoc⁻¹-inr-inr
  : {c d e : Code} (k : Val e) → ⊕assoc⁻¹ {c} {d} {e} (inr (inr k)) ≡ inr k
⊕assoc⁻¹-inr-inr {c} {d} {e} k =
  trans (cong [ (λ i′ → inl (inl i′)) , (λ y → [ (λ v → inl (inr v)) , inr ]′ (⊕split y)) ]′
              (⊕split-inr (inr {d} {e} k)))
        (cong [ (λ v → inl (inr v)) , inr ]′ (⊕split-inr k))

-- THE COLLAPSE, sum side. Left injections are offset-invariant outright; the
-- one case with content is the doubly-right one, and there the law is exactly
-- additive associativity of the two block widths.
⊕assoc-fixed
  : {c d e : Code} (x : Val ((c ⊕ d) ⊕ e)) → ⊕assoc x ≐ x
⊕assoc-fixed {c} {d} {e} =
  ⊕-ind (⊕assoc {c} {d} {e}) (λ x → x)
    (λ y →
      ⊕-ind (λ z → ⊕assoc {c} {d} {e} (inl {c ⊕ d} {e} z)) (λ z → inl {c ⊕ d} {e} z)
        (λ i →
          trans (≡-≐ (⊕assoc-inl-inl {c} {d} {e} i))
          (trans (ix-inl {c} {d ⊕ e} i)
          (trans (sym (ix-inl {c} {d} i))
                 (sym (ix-inl {c ⊕ d} {e} (inl {c} {d} i))))))
        (λ j →
          trans (≡-≐ (⊕assoc-inl-inr {c} {d} {e} j))
          (trans (ix-inr {c} {d ⊕ e} (inl {d} {e} j))
          (trans (cong (⊕ixʳ (size c)) (ix-inl {d} {e} j))
          (trans (sym (ix-inr {c} {d} j))
                 (sym (ix-inl {c ⊕ d} {e} (inr {c} {d} j)))))))
        y)
    (λ k →
      trans (≡-≐ (⊕assoc-inr {c} {d} {e} k))
      (trans (ix-inr {c} {d ⊕ e} (inr {d} {e} k))
      (trans (cong (⊕ixʳ (size c)) (ix-inr {d} {e} k))
      (trans (sym (⊕ix-assoc (size c) (size d) (ix k)))
             (sym (ix-inr {c ⊕ d} {e} k))))))

⊕assoc⁻¹-fixed
  : {c d e : Code} (x : Val (c ⊕ (d ⊕ e))) → ⊕assoc⁻¹ x ≐ x
⊕assoc⁻¹-fixed {c} {d} {e} =
  ⊕-ind (⊕assoc⁻¹ {c} {d} {e}) (λ x → x)
    (λ i →
      trans (≡-≐ (⊕assoc⁻¹-inl {c} {d} {e} i))
      (trans (ix-inl {c ⊕ d} {e} (inl {c} {d} i))
      (trans (ix-inl {c} {d} i)
             (sym (ix-inl {c} {d ⊕ e} i)))))
    (λ y →
      ⊕-ind (λ z → ⊕assoc⁻¹ {c} {d} {e} (inr {c} {d ⊕ e} z)) (λ z → inr {c} {d ⊕ e} z)
        (λ j →
          trans (≡-≐ (⊕assoc⁻¹-inr-inl {c} {d} {e} j))
          (trans (ix-inl {c ⊕ d} {e} (inr {c} {d} j))
          (trans (ix-inr {c} {d} j)
          (trans (cong (⊕ixʳ (size c)) (sym (ix-inl {d} {e} j)))
                 (sym (ix-inr {c} {d ⊕ e} (inl {d} {e} j)))))))
        (λ k →
          trans (≡-≐ (⊕assoc⁻¹-inr-inr {c} {d} {e} k))
          (trans (ix-inr {c ⊕ d} {e} k)
          (trans (⊕ix-assoc (size c) (size d) (ix k))
          (trans (cong (⊕ixʳ (size c)) (sym (ix-inr {d} {e} k)))
                 (sym (ix-inr {c} {d ⊕ e} (inr {d} {e} k)))))))
        y)

rigid-⊕assoc : {c d e : Code} → Rigid ((c ⊕ d) ⊕ e) (c ⊕ (d ⊕ e))
rigid-⊕assoc {c} {d} {e} = rigid ⊕assoc (+-assoc (size c) (size d) (size e)) ⊕assoc-fixed

rigid-⊕assoc⁻¹ : {c d e : Code} → Rigid (c ⊕ (d ⊕ e)) ((c ⊕ d) ⊕ e)
rigid-⊕assoc⁻¹ {c} {d} {e} =
  rigid ⊕assoc⁻¹ (sym (+-assoc (size c) (size d) (size e))) ⊕assoc⁻¹-fixed

-- ════════════════════════════════════════════════════════════════════════════
-- WHAT SURVIVES. These three genuinely permute the run of cells, so none of
-- them is rigid and none is discharged by the coherence theorem. They are the
-- content a normalizer must actually compute — which is the honest reason
-- distributivity is the hard case in the presented calculus too.
-- ════════════════════════════════════════════════════════════════════════════

-- ── ⊗ symmetry: the transpose ───────────────────────────────────────────────

⊗comm : {c d : Code} → Val (c ⊗ d) → Val (d ⊗ c)
⊗comm x = pair (proj₂ (⊗split x)) (proj₁ (⊗split x))

⊗comm-pair : {c d : Code} (u : Val c) (v : Val d) → ⊗comm (pair u v) ≡ pair v u
⊗comm-pair u v = cong (λ p → pair (proj₂ p) (proj₁ p)) (⊗split-pair u v)

-- The transpose's offset law: source `b * i + j` becomes target `a * j + i`.
⊗comm-ix
  : {c d : Code} (u : Val c) (v : Val d)
  → ix (⊗comm (pair u v)) ≡ ⊗ix (size c) (ix v) (ix u)
⊗comm-ix u v = trans (≡-≐ (⊗comm-pair u v)) (ix-pair v u)

⊗comm-invol : {c d : Code} (x : Val (c ⊗ d)) → ⊗comm (⊗comm x) ≡ x
⊗comm-invol {c} {d} x =
  ≐-≡ (⊗-ind (λ y → ⊗comm {d} {c} (⊗comm {c} {d} y)) (λ y → y)
        (λ u v → ≡-≐ (trans (cong (⊗comm {d} {c}) (⊗comm-pair u v)) (⊗comm-pair v u)))
        x)

-- ── ⊕ symmetry: the block swap ──────────────────────────────────────────────

⊕swap : {c d : Code} → Val (c ⊕ d) → Val (d ⊕ c)
⊕swap x = [ (λ i → inr i) , (λ j → inl j) ]′ (⊕split x)

⊕swap-inl : {c d : Code} (i : Val c) → ⊕swap {c} {d} (inl i) ≡ inr i
⊕swap-inl i = cong [ (λ i′ → inr i′) , (λ j → inl j) ]′ (⊕split-inl i)

⊕swap-inr : {c d : Code} (j : Val d) → ⊕swap {c} {d} (inr j) ≡ inl j
⊕swap-inr j = cong [ (λ i → inr i) , (λ j′ → inl j′) ]′ (⊕split-inr j)

⊕swap-invol : {c d : Code} (x : Val (c ⊕ d)) → ⊕swap (⊕swap x) ≡ x
⊕swap-invol {c} {d} x =
  ≐-≡ (⊕-ind (λ y → ⊕swap {d} {c} (⊕swap {c} {d} y)) (λ y → y)
        (λ i → ≡-≐ (trans (cong (⊕swap {d} {c}) (⊕swap-inl {c} {d} i)) (⊕swap-inr {d} {c} i)))
        (λ j → ≡-≐ (trans (cong (⊕swap {d} {c}) (⊕swap-inr {c} {d} j)) (⊕swap-inl {d} {c} j)))
        x)

-- ── The distributor ─────────────────────────────────────────────────────────

dist-on : {c d e : Code} → Val c → Val d ⊎ Val e → Val ((c ⊗ d) ⊕ (c ⊗ e))
dist-on u = [ (λ v → inl (pair u v)) , (λ w → inr (pair u w)) ]′

dist : {c d e : Code} → Val (c ⊗ (d ⊕ e)) → Val ((c ⊗ d) ⊕ (c ⊗ e))
dist x = dist-on (proj₁ (⊗split x)) (⊕split (proj₂ (⊗split x)))

dist-inl
  : {c d e : Code} (u : Val c) (v : Val d)
  → dist {c} {d} {e} (pair u (inl v)) ≡ inl (pair u v)
dist-inl {c} {d} {e} u v =
  trans (cong (λ p → dist-on (proj₁ p) (⊕split (proj₂ p))) (⊗split-pair u (inl {d} {e} v)))
        (cong (dist-on u) (⊕split-inl v))

dist-inr
  : {c d e : Code} (u : Val c) (w : Val e)
  → dist {c} {d} {e} (pair u (inr w)) ≡ inr (pair u w)
dist-inr {c} {d} {e} u w =
  trans (cong (λ p → dist-on (proj₁ p) (⊕split (proj₂ p))) (⊗split-pair u (inr {d} {e} w)))
        (cong (dist-on u) (⊕split-inr w))

undist-on : {c d e : Code} → Val (c ⊗ d) ⊎ Val (c ⊗ e) → Val (c ⊗ (d ⊕ e))
undist-on =
  [ (λ y → pair (proj₁ (⊗split y)) (inl (proj₂ (⊗split y))))
  , (λ z → pair (proj₁ (⊗split z)) (inr (proj₂ (⊗split z))))
  ]′

undist : {c d e : Code} → Val ((c ⊗ d) ⊕ (c ⊗ e)) → Val (c ⊗ (d ⊕ e))
undist x = undist-on (⊕split x)

undist-inl
  : {c d e : Code} (u : Val c) (v : Val d)
  → undist {c} {d} {e} (inl (pair u v)) ≡ pair u (inl v)
undist-inl {c} {d} {e} u v =
  trans (cong undist-on (⊕split-inl (pair u v)))
        (cong (λ p → pair (proj₁ p) (inl (proj₂ p))) (⊗split-pair u v))

undist-inr
  : {c d e : Code} (u : Val c) (w : Val e)
  → undist {c} {d} {e} (inr (pair u w)) ≡ pair u (inr w)
undist-inr {c} {d} {e} u w =
  trans (cong undist-on (⊕split-inr (pair u w)))
        (cong (λ p → pair (proj₁ p) (inr (proj₂ p))) (⊗split-pair u w))

dist-undist : {c d e : Code} (x : Val (c ⊗ (d ⊕ e))) → undist (dist x) ≡ x
dist-undist {c} {d} {e} x =
  ≐-≡ (⊗-ind (λ y → undist {c} {d} {e} (dist {c} {d} {e} y)) (λ y → y)
        (λ u y →
          ⊕-ind (λ z → undist {c} {d} {e} (dist {c} {d} {e} (pair u z)))
                (λ z → pair {c} {d ⊕ e} u z)
            (λ v → ≡-≐ (trans (cong (undist {c} {d} {e}) (dist-inl u v)) (undist-inl u v)))
            (λ w → ≡-≐ (trans (cong (undist {c} {d} {e}) (dist-inr u w)) (undist-inr u w)))
            y)
        x)

undist-dist : {c d e : Code} (x : Val ((c ⊗ d) ⊕ (c ⊗ e))) → dist (undist x) ≡ x
undist-dist {c} {d} {e} x =
  ≐-≡ (⊕-ind (λ y → dist {c} {d} {e} (undist {c} {d} {e} y)) (λ y → y)
        (λ y →
          ⊗-ind (λ z → dist {c} {d} {e} (undist {c} {d} {e} (inl {c ⊗ d} {c ⊗ e} z)))
                (λ z → inl {c ⊗ d} {c ⊗ e} z)
            (λ u v → ≡-≐ (trans (cong (dist {c} {d} {e}) (undist-inl u v)) (dist-inl u v)))
            y)
        (λ z →
          ⊗-ind (λ y → dist {c} {d} {e} (undist {c} {d} {e} (inr {c ⊗ d} {c ⊗ e} y)))
                (λ y → inr {c ⊗ d} {c ⊗ e} y)
            (λ u w → ≡-≐ (trans (cong (dist {c} {d} {e}) (undist-inr u w)) (dist-inr u w)))
            z)
        x)

-- The distributor is NOT rigid. At `c` of extent 2 and `d`, `e` of extent 1,
-- the value `pair u (inl v)` with `u` at offset 1 sits at source offset
-- 1 * (1 + 1) + 0 = 2, and its image sits at target offset 1 * 1 + 0 = 1.
-- Two is not one, so this generator carries real content and no collapse
-- theorem can be stated for it.
-- The witness: `c` of extent 2 (a two-block sum), `d` and `e` of extent 1.
-- The value pairs the SECOND cell of `c` with the left summand.
dist-witness : Val ((𝟙 ⊕ 𝟙) ⊗ (𝟙 ⊕ 𝟙))
dist-witness = pair (inr unit) (inl unit)

-- Source offset: 2 * 1 + 0 = 2.
dist-moves : ix dist-witness ≡ suc (suc zero)
dist-moves = refl

-- Target offset: the left block of the target, at 1 * 1 + 0 = 1.
dist-target : ix (dist {𝟙 ⊕ 𝟙} {𝟙} {𝟙} dist-witness) ≡ suc zero
dist-target = refl
