#![no_std]
#![warn(missing_docs)]

//! Deterministic record-safe chunk boundary detection for future Prolly-Bao.
//!
//! # Provenance
//!
//! This crate is a storage-tier skeleton absorbed directly from the owner's
//! unpublished `mach` `prolly-bao-chunker` crate (Apache-2.0, same owner;
//! source commit `fb78601`). It is a direct source absorption adapted to the
//! gandr storage tier and lint discipline, not an external dependency. See the
//! ratified vendor plan in `docs/research/massive-term-design.md` §6.1.
//!
//! # Crate boundary
//!
//! This crate is `#![no_std]` with **zero runtime dependencies** (an empty
//! `[dependencies]` table) — a deliberate property kept visible at the crate
//! boundary so the chunker stays a minimal, self-contained substrate. Its
//! 85-byte fixed-order [`ChunkerParams::commitment_bytes`] parameter commitment
//! ([`PARAMETER_COMMITMENT_LEN`], magic `MPBCHK01`, big-endian fields) is the
//! primitive downstream layers bind so records cannot be replayed under
//! incompatible chunking parameters.
//!
//! `current`: this crate owns only boundary detection over already-canonical
//! ordered records. It does not serialize records, build Prolly-Bao trees, hash
//! nodes with BLAKE3, store blocks, produce proofs, or talk to storage and
//! transport adapters.
//!
//! `designed direction`: callers commit [`ChunkerParams::commitment_bytes`]
//! into Prolly-Bao root or proof context so the same records cannot be replayed
//! under incompatible chunking parameters.
//!
//! `open decision`: stronger adversarial boundary-grinding mitigations may add
//! new algorithm profiles later. The only supported profile here is the local,
//! deterministic, FastCDC-2020-inspired Gear scanner identified by
//! [`AlgorithmVersion::FASTCDC_2020`].

extern crate alloc;

use alloc::vec::Vec;
use core::convert::TryFrom as _;
use core::fmt;

/// Length in bytes of [`ChunkerParams`] parameter commitments.
pub const PARAMETER_COMMITMENT_LEN: usize = 0x55_usize;

/// Offset of the commitment-format version field.
const COMMITMENT_FORMAT_VERSION_OFFSET: usize = 0x08_usize;

/// Offset of the algorithm-version field.
const COMMITMENT_ALGORITHM_OFFSET: usize = 0x0A_usize;

/// Offset of the Gear-table-version field.
const COMMITMENT_TABLE_OFFSET: usize = 0x0C_usize;

/// Offset of the seed salt bytes.
const COMMITMENT_SALT_OFFSET: usize = 0x0F_usize;

/// Offset of the minimum-byte-limit field.
const COMMITMENT_MIN_BYTES_OFFSET: usize = 0x31_usize;

/// Offset of the target-byte-limit field.
const COMMITMENT_TARGET_BYTES_OFFSET: usize = 0x39_usize;

/// Offset of the maximum-byte-limit field.
const COMMITMENT_MAX_BYTES_OFFSET: usize = 0x41_usize;

/// Offset of the minimum-record-limit field.
const COMMITMENT_MIN_RECORDS_OFFSET: usize = 0x49_usize;

/// Offset of the target-record-limit field.
const COMMITMENT_TARGET_RECORDS_OFFSET: usize = 0x4D_usize;

/// Offset of the maximum-record-limit field.
const COMMITMENT_MAX_RECORDS_OFFSET: usize = 0x51_usize;

/// Version of the commitment byte layout implemented by this crate.
const COMMITMENT_FORMAT_VERSION: u16 = 0x0001_u16;

/// Raw value for the supported FastCDC-2020-inspired algorithm profile.
const ALGORITHM_FASTCDC_2020_RAW: u16 = 0x0001_u16;

/// Raw value for the supported Mach Gear table.
const GEAR_TABLE_MACH_V1_RAW: u16 = 0x0001_u16;

/// Raw value for a seedless boundary scan.
const SEED_KIND_NONE: u8 = 0x00_u8;

/// Raw value for a caller-provided public salt.
const SEED_KIND_PUBLIC_SALT: u8 = 0x01_u8;

/// Raw value for byte-preserving input normalization.
const NORMALIZATION_NONE_RAW: u8 = 0x00_u8;

/// Raw value for between-record-only cut emission.
const RECORD_BOUNDARY_BETWEEN_RECORDS_RAW: u8 = 0x00_u8;

/// Maximum target byte value supported by the first release-build profile.
const MAX_TARGET_BYTES: u64 = 0x0000_0000_FFFF_FFFF_u64;

/// Default minimum chunk size in bytes.
const DEFAULT_MIN_BYTES: u64 = 0x0000_0000_0000_1000_u64;

/// Default target chunk size in bytes.
const DEFAULT_TARGET_BYTES: u64 = 0x0000_0000_0000_4000_u64;

/// Default maximum chunk size in bytes.
const DEFAULT_MAX_BYTES: u64 = 0x0000_0000_0001_0000_u64;

/// Default minimum records per chunk.
const DEFAULT_MIN_RECORDS: u32 = 0x0000_0001_u32;

/// Default target records per chunk.
const DEFAULT_TARGET_RECORDS: u32 = 0x0000_0040_u32;

/// Default maximum records per chunk.
const DEFAULT_MAX_RECORDS: u32 = 0x0000_0400_u32;

/// Initial state mixed into each chunk-local Gear scan.
const GEAR_STATE_IV: u64 = 0x243F_6A88_85A3_08D3_u64;

/// Multiplier used when deriving a Gear initial state from public salt bytes.
const SEED_MIX_MULTIPLIER: u64 = 0x9E37_79B9_7F4A_7C15_u64;

/// Versioned Mach Gear table generated by the `SplitMix64` source documented in
/// this crate.
const MACH_V1_GEAR_TABLE: [u64; 0x100_usize] = [
    0x63CF_C62A_2B09_7592_u64,
    0xDC07_46B4_1946_6AEC_u64,
    0x0826_4674_F98A_A19E_u64,
    0x3CA4_EB47_B26D_E7AC_u64,
    0xA5B3_84AD_339C_FCC3_u64,
    0x08F7_20D0_5989_2BC4_u64,
    0xFE66_75C9_2D60_F3DF_u64,
    0x1D59_C7B9_C3A5_6969_u64,
    0xEA56_85B6_014A_22C9_u64,
    0x3935_C47E_C47E_016D_u64,
    0xF723_14EF_3D87_AE57_u64,
    0xE2C2_311B_A18C_FD93_u64,
    0x509D_7011_D7BC_72C9_u64,
    0x4CD8_9B95_38C2_7512_u64,
    0xA4E3_8806_108A_16A3_u64,
    0x5A46_9FB3_420A_4216_u64,
    0x5087_CFEA_06CF_AE9E_u64,
    0x76EF_EB82_D49F_AD30_u64,
    0xA21F_9904_1583_0CDD_u64,
    0xD3CF_31C5_DD26_C237_u64,
    0xB956_E4E4_73A0_297F_u64,
    0xE297_A7E4_48A0_894C_u64,
    0x779D_A682_1D49_3912_u64,
    0xD715_7405_5724_395D_u64,
    0x797E_22F6_0798_2BAE_u64,
    0xFEC0_40B0_3A7F_1E41_u64,
    0x1F25_8FAD_67F6_4E49_u64,
    0x4EDC_DDD4_3446_9277_u64,
    0xA205_3EBD_77CB_8B08_u64,
    0x77BF_2263_0526_5856_u64,
    0x6DE7_291E_AAA3_D085_u64,
    0x96D7_536E_A745_DFFE_u64,
    0xF9C6_680E_9424_7B49_u64,
    0xC882_19FC_9CF0_493E_u64,
    0x1E31_F2C9_6F41_C928_u64,
    0x6CFA_87ED_E9C1_F270_u64,
    0xA86D_4345_37F8_A23A_u64,
    0xA15F_376D_2BEF_48D9_u64,
    0x0566_17E9_F8F4_2D36_u64,
    0xF24B_9093_554C_D786_u64,
    0x62D5_6DAF_E2BB_1E59_u64,
    0xB06D_E450_2F88_3955_u64,
    0xBE4C_8D81_46C0_D0AB_u64,
    0x83E6_6C72_05D6_AF78_u64,
    0x7800_5FA8_D605_DED0_u64,
    0x4B21_1F62_33E9_8863_u64,
    0x1045_1D9D_286A_B638_u64,
    0x5BBD_90AE_A8B4_B277_u64,
    0x7F7A_AEEA_56D1_839A_u64,
    0x65D4_894E_D424_3013_u64,
    0x6DD3_AA78_170E_9AF1_u64,
    0xD46A_9444_D379_9968_u64,
    0x659A_245A_5B48_1F0D_u64,
    0x1565_2888_D3BB_C8DF_u64,
    0x8B73_FDDB_CE64_BEFA_u64,
    0x0BFC_A26E_4C5F_B77A_u64,
    0xC484_9A2E_AE85_81B2_u64,
    0xC22D_D397_E260_CD58_u64,
    0x92F0_919F_78F4_9D90_u64,
    0xECDD_8449_D5E7_96DF_u64,
    0x7A09_4A53_DA9A_2011_u64,
    0x64FF_8E70_1AC6_665E_u64,
    0x9A27_18AC_8690_427A_u64,
    0x03FE_A5F1_FFC6_CDE0_u64,
    0x19B6_560A_01AD_4034_u64,
    0x896A_2EE6_8EDB_277A_u64,
    0x6E8E_7574_571E_76E7_u64,
    0x4F24_8C2C_5923_DFB3_u64,
    0xC6A7_1954_79D0_2D29_u64,
    0xB78C_342F_689E_D1CD_u64,
    0x3FA8_6FBC_793B_CD5C_u64,
    0xC47C_1E84_11E1_296D_u64,
    0x5F46_1BDE_3886_2E3C_u64,
    0x15AA_1C31_A6D3_E5D1_u64,
    0xB59F_FEAC_43EB_9BCF_u64,
    0xB337_97B8_0682_FB8E_u64,
    0x8242_47E1_303D_F497_u64,
    0xBDA0_B7E1_A9BD_1089_u64,
    0xA315_8AB7_1D99_CD18_u64,
    0xC257_41EC_D2AC_9FB2_u64,
    0x7173_B3D3_06F6_481F_u64,
    0x5FF0_80F2_21B0_EC33_u64,
    0xB80D_9936_EF1A_2177_u64,
    0x5BCF_5EE0_AFED_6941_u64,
    0x3367_CDFC_6E91_746F_u64,
    0x628F_06DC_67CD_8D10_u64,
    0x9B5D_29D3_387D_8FE0_u64,
    0x4113_33C0_F557_27A3_u64,
    0xE4F2_1DEF_307B_D64A_u64,
    0x654F_7E53_D53E_C6A0_u64,
    0x6D1C_6352_B72B_2DC1_u64,
    0xAB6B_2E66_36AB_6A4B_u64,
    0xB8AC_5A49_5D67_C6BA_u64,
    0x5086_3463_1E16_ACB4_u64,
    0xA85B_AF8D_6401_DFC2_u64,
    0x5654_3E94_1681_858E_u64,
    0x13B0_BDF6_C6AA_8016_u64,
    0x872F_E81D_3100_D87E_u64,
    0x8540_D20D_3F17_E625_u64,
    0x54BF_3B95_82EC_1C16_u64,
    0xC88C_E667_2E8B_2E5E_u64,
    0x7762_3F12_6327_77F7_u64,
    0x7ACF_9CB3_D918_C7A5_u64,
    0xFC7B_3447_06E0_19A4_u64,
    0xFE4C_CCC5_91E7_59E7_u64,
    0xC7C8_AC08_A93F_8AB0_u64,
    0x64E3_0E0B_06F5_9CF4_u64,
    0xD92E_E107_E60C_68AF_u64,
    0x3A61_F146_15ED_3141_u64,
    0x8526_D39F_4B86_6B62_u64,
    0x2EEC_4B67_D469_BAEE_u64,
    0x8515_5E4B_B6DB_5F31_u64,
    0x0213_2955_6FD9_A48B_u64,
    0xAE2F_1F8A_0C98_408D_u64,
    0x5C4A_BDFD_D6B6_4E09_u64,
    0x9270_21ED_7998_449E_u64,
    0x5089_3FAC_7A70_16FD_u64,
    0x3BA5_5287_1846_7B16_u64,
    0x100E_7235_4F14_964F_u64,
    0x1E95_1030_B915_04E8_u64,
    0x58BD_6F34_1595_6770_u64,
    0x4C48_F3DB_2BB9_FC97_u64,
    0xC28D_ED4D_7336_172C_u64,
    0xC1C4_F647_9A92_FBA1_u64,
    0xEDD2_5017_9DC0_37B8_u64,
    0xA0E9_B447_6994_FE0A_u64,
    0x2197_22EA_A7E1_34FA_u64,
    0x556A_34C8_6B93_E559_u64,
    0x9F92_CAD8_40DB_5CD4_u64,
    0xFA39_5BC0_E723_02D7_u64,
    0xA938_64EF_A116_88F6_u64,
    0x4828_B480_A740_4C16_u64,
    0x009D_7B10_1914_6442_u64,
    0x2AEA_80DD_0FD9_A87E_u64,
    0xD238_9AE1_7F52_0E2D_u64,
    0xCC8B_4DC8_7A43_5309_u64,
    0x545B_2712_728E_32AE_u64,
    0x0197_2B2B_759F_6CA1_u64,
    0x9AF4_A0E7_048E_6CE3_u64,
    0xCB79_E958_9345_3221_u64,
    0xA667_C7C7_AC04_4B01_u64,
    0xC5B9_6C9E_221F_FB06_u64,
    0x3347_CA53_3356_8EC8_u64,
    0x3D4E_56D2_1AA5_9484_u64,
    0xEAE7_2282_CADA_E561_u64,
    0x4AB5_90A5_0674_6228_u64,
    0xD5B6_66F6_221B_2E21_u64,
    0xBC6E_B34E_99CB_E624_u64,
    0x3F5C_9756_3F22_2382_u64,
    0x1181_8C6E_8CD3_3AEB_u64,
    0x7092_57E5_2D91_C95B_u64,
    0x7AF8_167D_D67D_A46B_u64,
    0x6B78_4107_B944_4E6A_u64,
    0xE503_9789_88BE_7F04_u64,
    0xE6C0_96A8_C4E5_CB52_u64,
    0x2E81_0F6D_E737_2820_u64,
    0x0881_5BB4_3E76_4D8E_u64,
    0x74C0_2098_5B40_7417_u64,
    0x9E5B_B9D4_1235_AC0C_u64,
    0x69D1_0C8E_2DD7_55EF_u64,
    0x206B_EEEE_05BE_9F92_u64,
    0xED28_A35C_2697_6580_u64,
    0x23FB_2239_98C1_DD8D_u64,
    0xE724_F92B_D60B_EFA0_u64,
    0x39F9_1045_0CE8_735E_u64,
    0x9686_5BFF_B2B5_C9BB_u64,
    0xD9D8_F838_BF60_0228_u64,
    0xC900_366A_AFB4_8B29_u64,
    0xD9D5_EC56_0DC8_09A8_u64,
    0xD7D0_A682_7A0D_88A4_u64,
    0x5E5E_E11D_A778_2ADC_u64,
    0x7410_96F1_A8FD_732B_u64,
    0x13F3_ECA1_2FF5_064A_u64,
    0x974B_8DBA_65A9_3A66_u64,
    0x4EA1_351F_023D_B3C3_u64,
    0xDA1B_38B8_62AE_579B_u64,
    0x8AE3_429F_4A0F_AB9E_u64,
    0x4CD0_B9F7_48AE_BC23_u64,
    0xACB4_1C40_A752_20C2_u64,
    0xECF3_D4F5_4950_40B0_u64,
    0xC098_556A_A4CE_A858_u64,
    0x0776_C8D9_15FC_64FC_u64,
    0xAAF8_BA2C_DC7A_9D41_u64,
    0x1326_2BB0_FE9E_7BC3_u64,
    0xB226_1D77_FA70_4973_u64,
    0xAC19_5C7F_AEBE_F934_u64,
    0xE501_763A_9BB3_9601_u64,
    0x2749_5D1D_D164_1751_u64,
    0x1199_59C9_D15C_B02E_u64,
    0xD869_40CE_C516_02BB_u64,
    0x2628_26B6_8C32_4853_u64,
    0x1C7A_1127_E871_E1FF_u64,
    0x20CA_7B07_137B_11EF_u64,
    0xA70A_5636_B444_CE19_u64,
    0xD8D7_F430_FB61_F097_u64,
    0x1574_3FA9_6D05_DE00_u64,
    0xA4FA_F5C4_2789_E8C0_u64,
    0x8FA5_4C35_BA03_F12B_u64,
    0xDBAF_3909_4B32_8278_u64,
    0xD7B4_4DAE_0863_3716_u64,
    0xBE8A_CC13_573E_AF72_u64,
    0x4156_76D0_69C5_4CDB_u64,
    0xE24B_949B_E6A0_4823_u64,
    0x2C8A_22E1_DD3E_D3E1_u64,
    0x4C27_144D_40FB_62B7_u64,
    0x463E_6279_A7B8_1991_u64,
    0x604D_1ED4_1AAD_75DB_u64,
    0xD043_2163_DE9C_DDD6_u64,
    0xF5C2_027B_8CD9_76EE_u64,
    0xB939_2320_BF1C_7771_u64,
    0x46F0_9197_0B73_C999_u64,
    0x9FB9_BB13_EAE1_32AC_u64,
    0xE21E_99F5_A7DB_E246_u64,
    0xE5D3_0862_BD54_399C_u64,
    0x868E_564B_7F8E_08E6_u64,
    0x11CE_898C_645A_FF49_u64,
    0xE2F4_9C19_A001_5B61_u64,
    0xF8F9_9E93_1A8D_E3DE_u64,
    0x1BDA_F881_19FD_69B7_u64,
    0xCE87_83E6_01C5_5607_u64,
    0x16CC_703C_FEF7_65E0_u64,
    0xEF4E_3F64_1578_FEEC_u64,
    0x37B9_0750_4545_0C0C_u64,
    0x34CC_299A_C8DC_1C30_u64,
    0xA6B0_D3B0_C86C_EDDC_u64,
    0xD716_94FA_3D5E_1565_u64,
    0x0770_5599_5940_B148_u64,
    0x59B2_DA7E_56C8_D627_u64,
    0x59FF_2A08_8D38_836A_u64,
    0x0499_5A8A_B2BF_0E6D_u64,
    0x4B47_C98B_EE2B_3EE3_u64,
    0xE57A_6754_01DC_F414_u64,
    0xADD6_D148_02BF_ADE9_u64,
    0x8BEC_A4E9_079B_9384_u64,
    0xA596_917B_EF1F_1165_u64,
    0xA2A0_528C_085A_F450_u64,
    0x2B91_C70B_62EC_602B_u64,
    0xBA60_3814_703E_E279_u64,
    0x04B0_F614_F48B_56EA_u64,
    0xC660_2758_585E_D9A0_u64,
    0x4CCD_FDDF_AD39_B91A_u64,
    0xD15F_AC46_DC6F_FB91_u64,
    0x1CF6_8851_DB92_8B8F_u64,
    0x0521_5130_88FC_F276_u64,
    0x134D_10C6_3384_C0E3_u64,
    0xFD2F_46B5_CA56_299A_u64,
    0xEA1D_7278_D225_D8B0_u64,
    0x22DC_E3E8_A727_540E_u64,
    0x96F4_940D_7098_8C5A_u64,
    0x340A_406C_CD54_05A0_u64,
    0x1435_3BD6_E3E5_914B_u64,
    0x5320_6676_5550_9344_u64,
    0x2D87_8ACF_43DE_C8E0_u64,
    0x0D0A_DCD4_73AF_C709_u64,
    0x7B84_EEFA_A0E9_8D96_u64,
    0xCED3_4DD0_5B9A_775A_u64,
];

/// Define an opaque integer carrier whose only primitive conversions are exact
/// implementations of the standard [`From`] trait.
macro_rules! semantic_integer
{
    (
        $(#[$attribute:meta])*
        $visibility:vis struct $name:ident($primitive:ty);
    ) => {
        $(#[$attribute])*
        #[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
        #[repr(transparent)]
        $visibility struct $name($primitive);

        impl From<$primitive> for $name
        {
            #[inline]
            fn from(value: $primitive) -> Self
            {
                return Self(value);
            }
        }

        impl From<$name> for $primitive
        {
            #[inline]
            fn from(value: $name) -> Self
            {
                return value.0;
            }
        }
    };
}

semantic_integer! {
    /// A canonical byte count, used for chunk limits and measured payload sizes.
    pub struct ByteCount(u64);
}

semantic_integer! {
    /// A canonical byte-stream position.
    pub struct BytePosition(u64);
}

semantic_integer! {
    /// A bounded per-chunk record count.
    pub struct RecordCount(u32);
}

semantic_integer! {
    /// A position in canonical record order.
    pub struct RecordPosition(u64);
}

semantic_integer! {
    /// Raw seed-policy discriminator carried by parameter commitments.
    pub struct SeedKind(u8);
}

semantic_integer! {
    /// Number of input records for which a scanner reserves boundary capacity.
    struct RecordCapacity(usize);
}

semantic_integer! {
    /// Record distance used to advance a canonical record position.
    struct RecordDistance(u64);
}

semantic_integer! {
    /// Chunk-local Gear hash state.
    struct GearState(u64);
}

semantic_integer! {
    /// One value selected from the committed Gear table.
    struct GearValue(u64);
}

semantic_integer! {
    /// Gear predicate mask derived from the target byte count.
    struct CutMask(u64);
}

semantic_integer! {
    /// One canonical input byte.
    struct InputByte(u8);
}

semantic_integer! {
    /// A position in the fixed parameter commitment.
    struct CommitmentIndex(usize);
}

semantic_integer! {
    /// A fixed field offset in the parameter commitment.
    struct CommitmentOffset(usize);
}

semantic_integer! {
    /// One byte of the parameter commitment.
    struct CommitmentByte(u8);
}

semantic_integer! {
    /// One big-endian 16-bit commitment field.
    struct CommitmentWord(u16);
}

semantic_integer! {
    /// A private decision returned by chunk-boundary predicates.
    struct CutDecision(bool);
}

impl From<RecordCount> for RecordDistance
{
    #[inline]
    fn from(count: RecordCount) -> Self
    {
        return Self(u64::from(count.0));
    }
}

impl ByteCount
{
    /// Adds two byte counts while preserving the requested failure operation.
    fn checked_add(
        self,
        rhs: Self,
        operation: ArithmeticOperation,
    ) -> Result<Self, ChunkerError>
    {
        return match self.0.checked_add(rhs.0) {
            | Some(sum) => Ok(Self(sum)),
            | None => Err(ChunkerError::ArithmeticOverflow { operation }),
        };
    }
}

impl BytePosition
{
    /// Advances a byte position by a byte count.
    fn checked_advance(
        self,
        count: ByteCount,
        operation: ArithmeticOperation,
    ) -> Result<Self, ChunkerError>
    {
        return match self.0.checked_add(count.0) {
            | Some(position) => Ok(Self(position)),
            | None => Err(ChunkerError::ArithmeticOverflow { operation }),
        };
    }

    /// Measures a byte count from an earlier position.
    fn checked_distance_from(
        self,
        start: Self,
        operation: ArithmeticOperation,
    ) -> Result<ByteCount, ChunkerError>
    {
        return match self.0.checked_sub(start.0) {
            | Some(distance) => Ok(ByteCount(distance)),
            | None => Err(ChunkerError::ArithmeticOverflow { operation }),
        };
    }
}

impl RecordCount
{
    /// Increments a bounded per-chunk record count.
    fn checked_increment(
        self,
        operation: ArithmeticOperation,
    ) -> Result<Self, ChunkerError>
    {
        return match self.0.checked_add(0x01_u32) {
            | Some(count) => Ok(Self(count)),
            | None => Err(ChunkerError::ArithmeticOverflow { operation }),
        };
    }
}

impl RecordPosition
{
    /// Advances a canonical record position by a record distance.
    fn checked_advance(
        self,
        distance: RecordDistance,
        operation: ArithmeticOperation,
    ) -> Result<Self, ChunkerError>
    {
        return match self.0.checked_add(distance.0) {
            | Some(position) => Ok(Self(position)),
            | None => Err(ChunkerError::ArithmeticOverflow { operation }),
        };
    }

    /// Advances to the next canonical record position.
    fn checked_next(self) -> Result<Self, ChunkerError>
    {
        return self.checked_advance(RecordDistance(0x01_u64), ArithmeticOperation::RecordIndex);
    }
}

/// Caller-provided public salt mixed into each chunk-local Gear state.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(transparent)]
pub struct SeedSalt
{
    /// Exact committed salt bytes.
    bytes: [u8; 0x20_usize],
}

impl From<[u8; 0x20_usize]> for SeedSalt
{
    #[inline]
    fn from(bytes: [u8; 0x20_usize]) -> Self
    {
        return Self { bytes };
    }
}

impl AsRef<[u8; 0x20_usize]> for SeedSalt
{
    #[inline]
    fn as_ref(&self) -> &[u8; 0x20_usize]
    {
        return &self.bytes;
    }
}

/// Stable fixed-order parameter commitment.
#[derive(Clone, Debug, Eq, PartialEq)]
#[repr(transparent)]
pub struct ParameterCommitment
{
    /// Canonical commitment bytes.
    bytes: [u8; PARAMETER_COMMITMENT_LEN],
}

impl AsRef<[u8]> for ParameterCommitment
{
    #[inline]
    fn as_ref(&self) -> &[u8]
    {
        return self.bytes.as_ref();
    }
}

/// Borrowed canonical bytes supplied to [`chunk_spans`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(transparent)]
pub struct CanonicalBytes<'bytes>
{
    /// Borrowed canonical byte stream.
    bytes: &'bytes [u8],
}

impl<'bytes> From<&'bytes [u8]> for CanonicalBytes<'bytes>
{
    #[inline]
    fn from(bytes: &'bytes [u8]) -> Self
    {
        return Self { bytes };
    }
}

impl AsRef<[u8]> for CanonicalBytes<'_>
{
    #[inline]
    fn as_ref(&self) -> &[u8]
    {
        return self.bytes;
    }
}

/// Borrowed ordered canonical record slices supplied to
/// [`chunk_record_slices`].
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(transparent)]
pub struct CanonicalRecords<'records>
{
    /// Borrowed canonical records in their committed order.
    records: &'records [&'records [u8]],
}

impl<'records> From<&'records [&'records [u8]]> for CanonicalRecords<'records>
{
    #[inline]
    fn from(records: &'records [&'records [u8]]) -> Self
    {
        return Self { records };
    }
}

impl<'records> AsRef<[&'records [u8]]> for CanonicalRecords<'records>
{
    #[inline]
    fn as_ref(&self) -> &[&'records [u8]]
    {
        return self.records;
    }
}

/// One borrowed canonical record consumed by the scanner.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
#[repr(transparent)]
struct CanonicalRecord<'record>
{
    /// Borrowed canonical record bytes.
    bytes: &'record [u8],
}

impl<'record> From<&'record [u8]> for CanonicalRecord<'record>
{
    #[inline]
    fn from(bytes: &'record [u8]) -> Self
    {
        return Self { bytes };
    }
}

impl AsRef<[u8]> for CanonicalRecord<'_>
{
    #[inline]
    fn as_ref(&self) -> &[u8]
    {
        return self.bytes;
    }
}

/// Local algorithm profile identifier committed into chunker parameters.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(transparent)]
pub struct AlgorithmVersion
{
    /// Raw committed algorithm version.
    raw: u16,
}

impl AlgorithmVersion
{
    /// FastCDC-2020-inspired local Gear scanner profile.
    pub const FASTCDC_2020: Self = Self {
        raw: ALGORITHM_FASTCDC_2020_RAW,
    };
}

impl TryFrom<u16> for AlgorithmVersion
{
    type Error = ChunkerError;

    #[inline]
    fn try_from(raw: u16) -> Result<Self, Self::Error>
    {
        if raw == ALGORITHM_FASTCDC_2020_RAW {
            return Ok(Self { raw });
        }

        return Err(ChunkerError::UnsupportedAlgorithmVersion { raw });
    }
}

impl From<AlgorithmVersion> for u16
{
    #[inline]
    fn from(version: AlgorithmVersion) -> Self
    {
        return version.raw;
    }
}

/// Versioned Gear table identifier committed into chunker parameters.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(transparent)]
pub struct GearTableVersion
{
    /// Raw committed Gear table version.
    raw: u16,
}

impl GearTableVersion
{
    /// Mach's first deterministic local Gear table.
    pub const MACH_V1: Self = Self {
        raw: GEAR_TABLE_MACH_V1_RAW,
    };
}

impl TryFrom<u16> for GearTableVersion
{
    type Error = ChunkerError;

    #[inline]
    fn try_from(raw: u16) -> Result<Self, Self::Error>
    {
        if raw == GEAR_TABLE_MACH_V1_RAW {
            return Ok(Self { raw });
        }

        return Err(ChunkerError::UnsupportedGearTableVersion { raw });
    }
}

impl From<GearTableVersion> for u16
{
    #[inline]
    fn from(version: GearTableVersion) -> Self
    {
        return version.raw;
    }
}

/// Seed policy for deterministic boundary detection.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct SeedPolicy
{
    /// Raw seed kind plus support marker.
    kind: SeedPolicyKind,
    /// Caller-provided salt bytes, or all zeroes for [`SeedPolicy::NONE`].
    salt: SeedSalt,
}

impl SeedPolicy
{
    /// Deterministic scan with no public salt.
    pub const NONE: Self = Self {
        kind: SeedPolicyKind::None,
        salt: SeedSalt {
            bytes: [0_u8; 0x20_usize],
        },
    };

    /// Creates a supported caller-provided public salt policy.
    #[inline]
    #[must_use]
    pub const fn public_salt(salt: SeedSalt) -> Self
    {
        return Self {
            kind: SeedPolicyKind::PublicSalt,
            salt,
        };
    }

    /// Creates an explicitly unsupported seed policy for validation tests and
    /// forward-compatible decoding.
    #[inline]
    #[must_use]
    pub const fn unsupported(kind: SeedKind) -> Self
    {
        return Self {
            kind: SeedPolicyKind::Unsupported(kind),
            salt: SeedSalt {
                bytes: [0_u8; 0x20_usize],
            },
        };
    }

    /// Returns the seed kind committed into parameter bytes.
    #[inline]
    #[must_use]
    pub const fn kind(&self) -> SeedKind
    {
        return self.kind.raw();
    }

    /// Returns the committed public salt.
    #[inline]
    #[must_use]
    pub const fn salt(&self) -> &SeedSalt
    {
        return &self.salt;
    }
}

/// Internal seed-kind representation that distinguishes unsupported raw values.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum SeedPolicyKind
{
    /// No salt is applied.
    None,
    /// A caller-provided public salt is mixed into the chunk-local Gear state.
    PublicSalt,
    /// Unsupported raw seed kind decoded from future parameter bytes.
    Unsupported(SeedKind),
}

impl SeedPolicyKind
{
    /// Returns the seed kind committed into parameter bytes.
    const fn raw(self) -> SeedKind
    {
        return match self {
            | Self::None => SeedKind(SEED_KIND_NONE),
            | Self::PublicSalt => SeedKind(SEED_KIND_PUBLIC_SALT),
            | Self::Unsupported(kind) => kind,
        };
    }
}

/// Input normalization policy committed into chunker parameters.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(transparent)]
pub struct NormalizationPolicy
{
    /// Raw committed normalization policy.
    raw: u8,
}

impl NormalizationPolicy
{
    /// Preserve caller-provided canonical bytes exactly.
    pub const NONE: Self = Self {
        raw: NORMALIZATION_NONE_RAW,
    };
}

impl TryFrom<u8> for NormalizationPolicy
{
    type Error = ChunkerError;

    #[inline]
    fn try_from(raw: u8) -> Result<Self, Self::Error>
    {
        if raw == NORMALIZATION_NONE_RAW {
            return Ok(Self { raw });
        }

        return Err(ChunkerError::UnsupportedNormalizationPolicy { raw });
    }
}

impl From<NormalizationPolicy> for u8
{
    #[inline]
    fn from(policy: NormalizationPolicy) -> Self
    {
        return policy.raw;
    }
}

/// Rule that maps candidate boundaries to record-safe chunk boundaries.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(transparent)]
pub struct RecordBoundaryRule
{
    /// Raw committed record-boundary rule.
    raw: u8,
}

impl RecordBoundaryRule
{
    /// Emit cuts only between complete canonical records.
    pub const BETWEEN_RECORDS: Self = Self {
        raw: RECORD_BOUNDARY_BETWEEN_RECORDS_RAW,
    };
}

impl TryFrom<u8> for RecordBoundaryRule
{
    type Error = ChunkerError;

    #[inline]
    fn try_from(raw: u8) -> Result<Self, Self::Error>
    {
        if raw == RECORD_BOUNDARY_BETWEEN_RECORDS_RAW {
            return Ok(Self { raw });
        }

        return Err(ChunkerError::UnsupportedRecordBoundaryRule { raw });
    }
}

impl From<RecordBoundaryRule> for u8
{
    #[inline]
    fn from(rule: RecordBoundaryRule) -> Self
    {
        return rule.raw;
    }
}

/// Validated byte and record limits for record-safe chunking.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ChunkLimits
{
    /// Minimum bytes before hash-predicate cuts are allowed.
    min_bytes: ByteCount,
    /// Target bytes used to derive the Gear cut mask.
    target_bytes: ByteCount,
    /// Hard byte cap for a chunk.
    max_bytes: ByteCount,
    /// Minimum records before hash-predicate cuts are allowed.
    min_records: RecordCount,
    /// Target records committed for the current profile and future profiles.
    target_records: RecordCount,
    /// Hard record-count cap for a chunk.
    max_records: RecordCount,
}

impl ChunkLimits
{
    /// Creates validated chunk byte and record limits.
    ///
    /// # Errors
    ///
    /// Returns [`ChunkerError::InvalidParameters`] when any limit is zero, when
    /// byte or record limits are inverted, or when target bytes exceed the
    /// current release-build validation cap.
    #[inline]
    #[must_use = "invalid chunk limits must be handled"]
    pub const fn new(
        min_bytes: ByteCount,
        target_bytes: ByteCount,
        max_bytes: ByteCount,
        min_records: RecordCount,
        target_records: RecordCount,
        max_records: RecordCount,
    ) -> Result<Self, ChunkerError>
    {
        if min_bytes.0 == 0_u64 || target_bytes.0 == 0_u64 || max_bytes.0 == 0_u64 {
            return Err(ChunkerError::InvalidParameters {
                reason: InvalidParameterReason::ZeroByteLimit,
            });
        }

        if min_records.0 == 0_u32 || target_records.0 == 0_u32 || max_records.0 == 0_u32 {
            return Err(ChunkerError::InvalidParameters {
                reason: InvalidParameterReason::ZeroRecordLimit,
            });
        }

        if min_bytes.0 > target_bytes.0 {
            return Err(ChunkerError::InvalidParameters {
                reason: InvalidParameterReason::MinByteExceedsTargetByte,
            });
        }

        if target_bytes.0 > max_bytes.0 {
            return Err(ChunkerError::InvalidParameters {
                reason: InvalidParameterReason::InvertedByteLimits,
            });
        }

        if target_bytes.0 > MAX_TARGET_BYTES {
            return Err(ChunkerError::InvalidParameters {
                reason: InvalidParameterReason::TargetByteExceedsU32,
            });
        }

        if min_records.0 > target_records.0 || target_records.0 > max_records.0 {
            return Err(ChunkerError::InvalidParameters {
                reason: InvalidParameterReason::InvertedRecordLimits,
            });
        }

        return Ok(Self {
            min_bytes,
            target_bytes,
            max_bytes,
            min_records,
            target_records,
            max_records,
        });
    }

    /// Returns the default FastCDC-inspired limit profile.
    #[inline]
    #[must_use]
    pub const fn default_fastcdc() -> Self
    {
        return Self {
            min_bytes: ByteCount(DEFAULT_MIN_BYTES),
            target_bytes: ByteCount(DEFAULT_TARGET_BYTES),
            max_bytes: ByteCount(DEFAULT_MAX_BYTES),
            min_records: RecordCount(DEFAULT_MIN_RECORDS),
            target_records: RecordCount(DEFAULT_TARGET_RECORDS),
            max_records: RecordCount(DEFAULT_MAX_RECORDS),
        };
    }

    /// Returns the minimum byte count before hash cuts are allowed.
    #[inline]
    #[must_use]
    pub const fn min_bytes(&self) -> ByteCount
    {
        return self.min_bytes;
    }

    /// Returns the target byte count used to derive the Gear cut mask.
    #[inline]
    #[must_use]
    pub const fn target_bytes(&self) -> ByteCount
    {
        return self.target_bytes;
    }

    /// Returns the hard maximum byte count for a chunk.
    #[inline]
    #[must_use]
    pub const fn max_bytes(&self) -> ByteCount
    {
        return self.max_bytes;
    }

    /// Returns the minimum record count before hash cuts are allowed.
    #[inline]
    #[must_use]
    pub const fn min_records(&self) -> RecordCount
    {
        return self.min_records;
    }

    /// Returns the committed target record count.
    #[inline]
    #[must_use]
    pub const fn target_records(&self) -> RecordCount
    {
        return self.target_records;
    }

    /// Returns the hard maximum record count for a chunk.
    #[inline]
    #[must_use]
    pub const fn max_records(&self) -> RecordCount
    {
        return self.max_records;
    }
}

impl Default for ChunkLimits
{
    #[inline]
    fn default() -> Self
    {
        return Self::default_fastcdc();
    }
}

/// Validated chunker parameters and their stable commitment bytes.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct ChunkerParams
{
    /// Committed algorithm profile.
    algorithm_version: AlgorithmVersion,
    /// Committed Gear table version.
    gear_table_version: GearTableVersion,
    /// Committed seed policy and salt bytes.
    seed_policy: SeedPolicy,
    /// Committed input normalization policy.
    normalization_policy: NormalizationPolicy,
    /// Committed record-boundary rule.
    record_boundary_rule: RecordBoundaryRule,
    /// Validated byte and record limits.
    limits: ChunkLimits,
    /// Stable fixed-order parameter commitment bytes.
    commitment: ParameterCommitment,
    /// Initial Gear state for each chunk after seed-policy mixing.
    initial_state: GearState,
    /// Gear cut mask derived from target bytes.
    cut_mask: CutMask,
}

impl ChunkerParams
{
    /// Creates validated chunker parameters.
    ///
    /// # Errors
    ///
    /// Returns a precise [`ChunkerError`] when an algorithm, table,
    /// normalization, seed, boundary rule, or limit value is unsupported or
    /// invalid.
    #[must_use = "invalid chunker parameters must be handled"]
    #[inline]
    pub fn new(
        algorithm_version: AlgorithmVersion,
        gear_table_version: GearTableVersion,
        seed_policy: SeedPolicy,
        normalization_policy: NormalizationPolicy,
        record_boundary_rule: RecordBoundaryRule,
        limits: ChunkLimits,
    ) -> Result<Self, ChunkerError>
    {
        if let SeedPolicyKind::Unsupported(kind) = seed_policy.kind {
            return Err(ChunkerError::UnsupportedSeedPolicy {
                kind: u8::from(kind),
            });
        }

        let commitment = build_parameter_commitment(
            algorithm_version,
            gear_table_version,
            &seed_policy,
            normalization_policy,
            record_boundary_rule,
            &limits,
        );
        let initial_state = derive_initial_state(&seed_policy);
        let cut_mask = cut_mask_for_target(limits.target_bytes());

        return Ok(Self {
            algorithm_version,
            gear_table_version,
            seed_policy,
            normalization_policy,
            record_boundary_rule,
            limits,
            commitment,
            initial_state,
            cut_mask,
        });
    }

    /// Returns the default supported FastCDC-inspired profile.
    #[inline]
    #[must_use]
    pub fn default_fastcdc() -> Self
    {
        let limits = ChunkLimits::default_fastcdc();
        let seed_policy = SeedPolicy::NONE;
        let commitment = build_parameter_commitment(
            AlgorithmVersion::FASTCDC_2020,
            GearTableVersion::MACH_V1,
            &seed_policy,
            NormalizationPolicy::NONE,
            RecordBoundaryRule::BETWEEN_RECORDS,
            &limits,
        );
        let initial_state = derive_initial_state(&seed_policy);
        let cut_mask = cut_mask_for_target(limits.target_bytes());

        return Self {
            algorithm_version: AlgorithmVersion::FASTCDC_2020,
            gear_table_version: GearTableVersion::MACH_V1,
            seed_policy,
            normalization_policy: NormalizationPolicy::NONE,
            record_boundary_rule: RecordBoundaryRule::BETWEEN_RECORDS,
            limits,
            commitment,
            initial_state,
            cut_mask,
        };
    }

    /// Returns the stable fixed-order parameter commitment.
    #[inline]
    #[must_use]
    pub const fn commitment_bytes(&self) -> &ParameterCommitment
    {
        return &self.commitment;
    }

    /// Returns the committed algorithm version.
    #[inline]
    #[must_use]
    pub const fn algorithm_version(&self) -> AlgorithmVersion
    {
        return self.algorithm_version;
    }

    /// Returns the committed Gear table version.
    #[inline]
    #[must_use]
    pub const fn gear_table_version(&self) -> GearTableVersion
    {
        return self.gear_table_version;
    }

    /// Returns the committed seed policy.
    #[inline]
    #[must_use]
    pub const fn seed_policy(&self) -> &SeedPolicy
    {
        return &self.seed_policy;
    }

    /// Returns the committed normalization policy.
    #[inline]
    #[must_use]
    pub const fn normalization_policy(&self) -> NormalizationPolicy
    {
        return self.normalization_policy;
    }

    /// Returns the committed record-boundary rule.
    #[inline]
    #[must_use]
    pub const fn record_boundary_rule(&self) -> RecordBoundaryRule
    {
        return self.record_boundary_rule;
    }

    /// Returns validated chunk limits.
    #[inline]
    #[must_use]
    pub const fn limits(&self) -> &ChunkLimits
    {
        return &self.limits;
    }

    /// Returns the chunk-local initial Gear state.
    const fn initial_state(&self) -> GearState
    {
        return self.initial_state;
    }

    /// Returns the Gear cut mask.
    const fn cut_mask(&self) -> CutMask
    {
        return self.cut_mask;
    }
}

impl Default for ChunkerParams
{
    #[inline]
    fn default() -> Self
    {
        return Self::default_fastcdc();
    }
}

/// Half-open byte span in the canonical record byte stream.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct ByteSpan
{
    /// Inclusive start byte position.
    pub start: BytePosition,
    /// Exclusive end byte position.
    pub end: BytePosition,
}

impl ByteSpan
{
    /// Creates a half-open byte span.
    #[inline]
    #[must_use]
    pub const fn new(
        start: BytePosition,
        end: BytePosition,
    ) -> Self
    {
        return Self { start, end };
    }

    /// Returns the inclusive start byte position.
    #[inline]
    #[must_use]
    pub const fn start(&self) -> BytePosition
    {
        return self.start;
    }

    /// Returns the exclusive end byte position.
    #[inline]
    #[must_use]
    pub const fn end(&self) -> BytePosition
    {
        return self.end;
    }
}

/// Half-open record-index span in canonical record order.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct RecordSpan
{
    /// Inclusive start record position.
    pub start: RecordPosition,
    /// Exclusive end record position.
    pub end: RecordPosition,
}

impl RecordSpan
{
    /// Creates a half-open record span.
    #[inline]
    #[must_use]
    pub const fn new(
        start: RecordPosition,
        end: RecordPosition,
    ) -> Self
    {
        return Self { start, end };
    }

    /// Returns the inclusive start record position.
    #[inline]
    #[must_use]
    pub const fn start(&self) -> RecordPosition
    {
        return self.start;
    }

    /// Returns the exclusive end record position.
    #[inline]
    #[must_use]
    pub const fn end(&self) -> RecordPosition
    {
        return self.end;
    }
}

/// Record-safe chunk span and the reason its boundary was emitted.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct ChunkSpan
{
    /// Byte range covered by the chunk.
    pub bytes: ByteSpan,
    /// Record-index range covered by the chunk.
    pub records: RecordSpan,
    /// Boundary reason for the chunk end.
    pub reason: BoundaryReason,
}

impl ChunkSpan
{
    /// Creates a record-safe chunk span.
    #[inline]
    #[must_use]
    pub const fn new(
        bytes: ByteSpan,
        records: RecordSpan,
        reason: BoundaryReason,
    ) -> Self
    {
        return Self {
            bytes,
            records,
            reason,
        };
    }

    /// Returns the byte range covered by this chunk.
    #[inline]
    #[must_use]
    pub const fn bytes(&self) -> ByteSpan
    {
        return self.bytes;
    }

    /// Returns the record-index range covered by this chunk.
    #[inline]
    #[must_use]
    pub const fn records(&self) -> RecordSpan
    {
        return self.records;
    }

    /// Returns why this chunk boundary was emitted.
    #[inline]
    #[must_use]
    pub const fn reason(&self) -> BoundaryReason
    {
        return self.reason;
    }
}

/// Reason a record-safe chunk boundary was emitted.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum BoundaryReason
{
    /// The Gear hash predicate fired after a complete record.
    HashPredicate,
    /// The hard byte cap forced a boundary after a complete record.
    MaxByteCap,
    /// The hard record-count cap forced a boundary after a complete record.
    MaxRecordCap,
    /// End of input emitted a remaining non-empty chunk.
    FinalRemainder,
}

/// Invalid parameter condition detected during construction.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum InvalidParameterReason
{
    /// At least one byte limit was zero.
    ZeroByteLimit,
    /// Minimum byte limit exceeded the target byte limit.
    MinByteExceedsTargetByte,
    /// Byte limits did not satisfy target <= max.
    InvertedByteLimits,
    /// At least one record limit was zero.
    ZeroRecordLimit,
    /// Record limits did not satisfy min <= target <= max.
    InvertedRecordLimits,
    /// Target bytes exceed the current release-build validation cap.
    TargetByteExceedsU32,
}

/// Arithmetic operation that overflowed while validating or scanning input.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum ArithmeticOperation
{
    /// A byte offset or canonical byte-stream length overflowed [`u64`].
    ByteOffset,
    /// A record index overflowed [`u64`].
    RecordIndex,
    /// A record byte length could not be represented safely.
    RecordLength,
    /// A chunk byte count overflowed [`u64`].
    ChunkByteCount,
    /// A chunk record count overflowed [`u32`].
    ChunkRecordCount,
}

/// Error returned by parameter validation or record-safe boundary detection.
#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub enum ChunkerError
{
    /// Parameter limits are zero or inverted.
    InvalidParameters
    {
        /// Specific invalid parameter condition.
        reason: InvalidParameterReason,
    },
    /// Checked arithmetic failed while deriving offsets or counts.
    ArithmeticOverflow
    {
        /// Operation that overflowed.
        operation: ArithmeticOperation,
    },
    /// Record byte spans were not a contiguous monotonic partition.
    NonMonotonicRecordSpans
    {
        /// Index of the offending record span.
        index: usize,
    },
    /// A record span extended beyond the canonical byte stream.
    RecordSpanOutOfBounds
    {
        /// Index of the offending record span.
        index: usize,
        /// Observed end byte offset.
        end: u64,
        /// Canonical byte stream length.
        canonical_len: u64,
    },
    /// Canonical bytes were not covered by the provided record spans.
    UncoveredCanonicalBytes
    {
        /// End offset covered by the last record span.
        covered_end: u64,
        /// Canonical byte stream length.
        canonical_len: u64,
    },
    /// A single complete record exceeded the hard chunk byte cap.
    RecordByteLengthCapViolation
    {
        /// Index of the offending record.
        record_index: u64,
        /// Record byte length.
        record_len: u64,
        /// Maximum bytes allowed in one chunk.
        max_bytes: u64,
    },
    /// Adding the next complete record would violate the byte cap before the
    /// current chunk can satisfy minimum limits.
    ChunkByteCapViolation
    {
        /// Start record of the chunk being built.
        chunk_start_record: u64,
        /// Next record that would violate the byte cap.
        next_record_index: u64,
        /// Attempted chunk byte count.
        attempted_bytes: u64,
        /// Maximum bytes allowed in one chunk.
        max_bytes: u64,
    },
    /// Adding the next complete record would violate the record cap before the
    /// current chunk can satisfy minimum limits.
    ChunkRecordCapViolation
    {
        /// Start record of the chunk being built.
        chunk_start_record: u64,
        /// Next record that would violate the record cap.
        next_record_index: u64,
        /// Attempted chunk record count.
        attempted_records: u32,
        /// Maximum records allowed in one chunk.
        max_records: u32,
    },
    /// Algorithm version is not implemented by this crate.
    UnsupportedAlgorithmVersion
    {
        /// Raw unsupported algorithm version.
        raw: u16,
    },
    /// Gear table version is not implemented by this crate.
    UnsupportedGearTableVersion
    {
        /// Raw unsupported Gear table version.
        raw: u16,
    },
    /// Normalization policy is not implemented by this crate.
    UnsupportedNormalizationPolicy
    {
        /// Raw unsupported normalization policy.
        raw: u8,
    },
    /// Seed policy is not implemented by this crate.
    UnsupportedSeedPolicy
    {
        /// Raw unsupported seed kind.
        kind: u8,
    },
    /// Record-boundary rule is not implemented by this crate.
    UnsupportedRecordBoundaryRule
    {
        /// Raw unsupported record-boundary rule.
        raw: u8,
    },
}

impl fmt::Display for ChunkerError
{
    #[inline]
    fn fmt(
        &self,
        f: &mut fmt::Formatter<'_>,
    ) -> fmt::Result
    {
        return match *self {
            | Self::InvalidParameters { reason } => {
                write!(f, "invalid chunker parameters: {reason}")
            },
            | Self::ArithmeticOverflow { operation } => {
                write!(f, "arithmetic overflow while computing {operation}")
            },
            | Self::NonMonotonicRecordSpans { index } => {
                write!(f, "record span {index} is not contiguous")
            },
            | Self::RecordSpanOutOfBounds {
                index,
                end,
                canonical_len,
            } => write!(
                f,
                "record span {index} ends at {end}, beyond canonical byte length {canonical_len}"
            ),
            | Self::UncoveredCanonicalBytes {
                covered_end,
                canonical_len,
            } => write!(
                f,
                "record spans cover bytes through {covered_end}, not canonical length {canonical_len}"
            ),
            | Self::RecordByteLengthCapViolation {
                record_index,
                record_len,
                max_bytes,
            } => write!(
                f,
                "record {record_index} length {record_len} exceeds maximum chunk bytes {max_bytes}"
            ),
            | Self::ChunkByteCapViolation {
                chunk_start_record,
                next_record_index,
                attempted_bytes,
                max_bytes,
            } => write!(
                f,
                "chunk from record {chunk_start_record} cannot add record {next_record_index} without reaching {attempted_bytes} bytes, exceeding max bytes {max_bytes}"
            ),
            | Self::ChunkRecordCapViolation {
                chunk_start_record,
                next_record_index,
                attempted_records,
                max_records,
            } => write!(
                f,
                "chunk from record {chunk_start_record} cannot add record {next_record_index} without reaching {attempted_records} records, exceeding max records {max_records}"
            ),
            | Self::UnsupportedAlgorithmVersion { raw } => {
                write!(f, "unsupported algorithm version {raw}")
            },
            | Self::UnsupportedGearTableVersion { raw } => {
                write!(f, "unsupported Gear table version {raw}")
            },
            | Self::UnsupportedNormalizationPolicy { raw } => {
                write!(f, "unsupported normalization policy {raw}")
            },
            | Self::UnsupportedSeedPolicy { kind } => {
                write!(f, "unsupported seed policy {kind}")
            },
            | Self::UnsupportedRecordBoundaryRule { raw } => {
                write!(f, "unsupported record-boundary rule {raw}")
            },
        };
    }
}

impl core::error::Error for ChunkerError
{
}

impl fmt::Display for InvalidParameterReason
{
    #[inline]
    fn fmt(
        &self,
        f: &mut fmt::Formatter<'_>,
    ) -> fmt::Result
    {
        return match *self {
            | Self::ZeroByteLimit => write!(f, "a byte limit is zero"),
            | Self::MinByteExceedsTargetByte => {
                write!(f, "minimum byte limit must not exceed target byte limit")
            },
            | Self::InvertedByteLimits => {
                write!(f, "target byte limit must not exceed max byte limit")
            },
            | Self::ZeroRecordLimit => write!(f, "a record limit is zero"),
            | Self::InvertedRecordLimits => {
                write!(f, "record limits must satisfy min <= target <= max")
            },
            | Self::TargetByteExceedsU32 => {
                write!(f, "target byte limit exceeds u32::MAX")
            },
        };
    }
}

impl fmt::Display for ArithmeticOperation
{
    #[inline]
    fn fmt(
        &self,
        f: &mut fmt::Formatter<'_>,
    ) -> fmt::Result
    {
        return match *self {
            | Self::ByteOffset => write!(f, "byte offset"),
            | Self::RecordIndex => write!(f, "record index"),
            | Self::RecordLength => write!(f, "record length"),
            | Self::ChunkByteCount => write!(f, "chunk byte count"),
            | Self::ChunkRecordCount => write!(f, "chunk record count"),
        };
    }
}

/// Chunks borrowed canonical record slices without copying record payloads.
///
/// # Errors
///
/// Returns [`ChunkerError::RecordByteLengthCapViolation`] when one complete
/// record is larger than the hard byte cap. Returns
/// [`ChunkerError::ArithmeticOverflow`] if byte offsets or record counts exceed
/// representable limits. Minimum-limit cap conflicts return
/// [`ChunkerError::ChunkByteCapViolation`] or
/// [`ChunkerError::ChunkRecordCapViolation`].
#[must_use = "the returned chunk spans or chunking error must be handled"]
#[inline]
pub fn chunk_record_slices(
    records: CanonicalRecords<'_>,
    params: &ChunkerParams,
) -> Result<Vec<ChunkSpan>, ChunkerError>
{
    let records = records.as_ref();
    let mut scan = ChunkScan::new(params, RecordCapacity::from(records.len()));
    let mut record_index = RecordPosition::from(0_u64);
    let mut next_start = BytePosition::from(0_u64);
    for record_ref in records {
        let record = CanonicalRecord::from(*record_ref);
        let record_len = match u64::try_from(record.as_ref().len()) {
            | Ok(len) => ByteCount::from(len),
            | Err(_error) => {
                return Err(ChunkerError::ArithmeticOverflow {
                    operation: ArithmeticOperation::RecordLength,
                });
            },
        };
        let record_end = next_start.checked_advance(record_len, ArithmeticOperation::ByteOffset)?;
        scan.consume_record(record_index, next_start, record_end, record)?;
        next_start = record_end;
        record_index = record_index.checked_next()?;
    }

    scan.finish(record_index)?;
    return Ok(scan.into_chunks());
}

/// Chunks canonical bytes using precomputed contiguous record byte spans.
///
/// The spans must form a contiguous half-open partition of `canonical_bytes`.
/// The scanner borrows each record byte range and never copies record payloads.
///
/// # Errors
///
/// Returns [`ChunkerError::NonMonotonicRecordSpans`] when spans are inverted,
/// overlapping, or gapped. Returns [`ChunkerError::RecordSpanOutOfBounds`] or
/// [`ChunkerError::UncoveredCanonicalBytes`] when spans do not cover the byte
/// stream exactly. Record cap, byte cap, and arithmetic failures are reported
/// with the same variants as [`chunk_record_slices`].
#[must_use = "the returned chunk spans or chunking error must be handled"]
#[inline]
pub fn chunk_spans(
    canonical_bytes: CanonicalBytes<'_>,
    record_spans: &[ByteSpan],
    params: &ChunkerParams,
) -> Result<Vec<ChunkSpan>, ChunkerError>
{
    let canonical_bytes = canonical_bytes.as_ref();
    let canonical_len = match u64::try_from(canonical_bytes.len()) {
        | Ok(len) => BytePosition::from(len),
        | Err(_error) => {
            return Err(ChunkerError::ArithmeticOverflow {
                operation: ArithmeticOperation::ByteOffset,
            });
        },
    };
    let mut scan = ChunkScan::new(params, RecordCapacity::from(record_spans.len()));
    let mut expected_start = BytePosition::from(0_u64);
    let mut record_index = RecordPosition::from(0_u64);
    let mut span_index = 0_usize;

    for candidate_ref in record_spans {
        let byte_bounds = *candidate_ref;
        if byte_bounds.start() != expected_start || byte_bounds.end() < byte_bounds.start() {
            return Err(ChunkerError::NonMonotonicRecordSpans { index: span_index });
        }

        if byte_bounds.end() > canonical_len {
            return Err(ChunkerError::RecordSpanOutOfBounds {
                index: span_index,
                end: u64::from(byte_bounds.end()),
                canonical_len: u64::from(canonical_len),
            });
        }

        let start = match usize::try_from(u64::from(byte_bounds.start())) {
            | Ok(start) => start,
            | Err(_error) => {
                return Err(ChunkerError::ArithmeticOverflow {
                    operation: ArithmeticOperation::ByteOffset,
                });
            },
        };
        let end = match usize::try_from(u64::from(byte_bounds.end())) {
            | Ok(end) => end,
            | Err(_error) => {
                return Err(ChunkerError::ArithmeticOverflow {
                    operation: ArithmeticOperation::ByteOffset,
                });
            },
        };
        let Some(record) = canonical_bytes.get(start .. end)
        else {
            return Err(ChunkerError::RecordSpanOutOfBounds {
                index: span_index,
                end: u64::from(byte_bounds.end()),
                canonical_len: u64::from(canonical_len),
            });
        };

        scan.consume_record(
            record_index,
            byte_bounds.start(),
            byte_bounds.end(),
            CanonicalRecord::from(record),
        )?;
        expected_start = byte_bounds.end();
        record_index = record_index.checked_next()?;
        span_index = match span_index.checked_add(0x01_usize) {
            | Some(next) => next,
            | None => {
                return Err(ChunkerError::ArithmeticOverflow {
                    operation: ArithmeticOperation::RecordIndex,
                });
            },
        };
    }

    if expected_start != canonical_len {
        return Err(ChunkerError::UncoveredCanonicalBytes {
            covered_end: u64::from(expected_start),
            canonical_len: u64::from(canonical_len),
        });
    }

    scan.finish(record_index)?;
    return Ok(scan.into_chunks());
}

/// Mutable scanner state for one chunking pass.
struct ChunkScan
{
    /// Validated byte and record limits for this scan.
    limits: ChunkLimits,
    /// Initial Gear state for each newly opened chunk.
    initial_state: GearState,
    /// Gear cut mask for the committed target size.
    cut_mask: CutMask,
    /// Allocated boundary output.
    chunks: Vec<ChunkSpan>,
    /// Current chunk-local Gear state.
    state: GearState,
    /// Start byte position for the current chunk.
    chunk_start_byte: BytePosition,
    /// Start record position for the current chunk.
    chunk_start_record: RecordPosition,
    /// Current chunk byte count.
    chunk_bytes: ByteCount,
    /// Current chunk record count.
    chunk_records: RecordCount,
    /// End byte position of the last consumed record.
    last_record_end: BytePosition,
}

impl ChunkScan
{
    /// Creates a scanner with capacity for at most one boundary per input
    /// record.
    fn new(
        params: &ChunkerParams,
        record_capacity: RecordCapacity,
    ) -> Self
    {
        let initial_state = params.initial_state();
        return Self {
            limits: *params.limits(),
            initial_state,
            cut_mask: params.cut_mask(),
            chunks: Vec::with_capacity(record_capacity.0),
            state: initial_state,
            chunk_start_byte: BytePosition::from(0_u64),
            chunk_start_record: RecordPosition::from(0_u64),
            chunk_bytes: ByteCount::from(0_u64),
            chunk_records: RecordCount::from(0_u32),
            last_record_end: BytePosition::from(0_u64),
        };
    }

    /// Consumes one complete canonical record and may emit a boundary after it.
    fn consume_record(
        &mut self,
        record_index: RecordPosition,
        record_start: BytePosition,
        record_end: BytePosition,
        record: CanonicalRecord<'_>,
    ) -> Result<(), ChunkerError>
    {
        let record_len =
            record_end.checked_distance_from(record_start, ArithmeticOperation::RecordLength)?;
        if record_len > self.limits.max_bytes() {
            return Err(ChunkerError::RecordByteLengthCapViolation {
                record_index: u64::from(record_index),
                record_len: u64::from(record_len),
                max_bytes: u64::from(self.limits.max_bytes()),
            });
        }

        if self.chunk_records != RecordCount::from(0_u32) {
            let bytes_if_added = self
                .chunk_bytes
                .checked_add(record_len, ArithmeticOperation::ChunkByteCount)?;
            let records_if_added = self
                .chunk_records
                .checked_increment(ArithmeticOperation::ChunkRecordCount)?;

            if bytes_if_added > self.limits.max_bytes() {
                if !bool::from(self.chunk_satisfies_minimum_limits()) {
                    return Err(ChunkerError::ChunkByteCapViolation {
                        chunk_start_record: u64::from(self.chunk_start_record),
                        next_record_index: u64::from(record_index),
                        attempted_bytes: u64::from(bytes_if_added),
                        max_bytes: u64::from(self.limits.max_bytes()),
                    });
                }

                self.emit_boundary(BoundaryReason::MaxByteCap)?;
            }
            else if records_if_added > self.limits.max_records() {
                if !bool::from(self.chunk_satisfies_minimum_limits()) {
                    return Err(ChunkerError::ChunkRecordCapViolation {
                        chunk_start_record: u64::from(self.chunk_start_record),
                        next_record_index: u64::from(record_index),
                        attempted_records: u32::from(records_if_added),
                        max_records: u32::from(self.limits.max_records()),
                    });
                }

                self.emit_boundary(BoundaryReason::MaxRecordCap)?;
            }
        }

        if self.chunk_records == RecordCount::from(0_u32) {
            self.chunk_start_byte = record_start;
            self.chunk_start_record = record_index;
            self.state = self.initial_state;
        }

        self.state = consume_record_bytes(self.state, record);
        self.chunk_bytes = self
            .chunk_bytes
            .checked_add(record_len, ArithmeticOperation::ChunkByteCount)?;
        self.chunk_records = self
            .chunk_records
            .checked_increment(ArithmeticOperation::ChunkRecordCount)?;
        self.last_record_end = record_end;

        if self.chunk_bytes > self.limits.max_bytes() {
            return Err(ChunkerError::ChunkByteCapViolation {
                chunk_start_record: u64::from(self.chunk_start_record),
                next_record_index: u64::from(record_index),
                attempted_bytes: u64::from(self.chunk_bytes),
                max_bytes: u64::from(self.limits.max_bytes()),
            });
        }

        if self.chunk_records > self.limits.max_records() {
            return Err(ChunkerError::ChunkRecordCapViolation {
                chunk_start_record: u64::from(self.chunk_start_record),
                next_record_index: u64::from(record_index),
                attempted_records: u32::from(self.chunk_records),
                max_records: u32::from(self.limits.max_records()),
            });
        }

        if self.chunk_bytes == self.limits.max_bytes() {
            self.emit_boundary(BoundaryReason::MaxByteCap)?;
        }
        else if self.chunk_records == self.limits.max_records() {
            self.emit_boundary(BoundaryReason::MaxRecordCap)?;
        }
        else if bool::from(self.hash_predicate_allows_cut()) {
            self.emit_boundary(BoundaryReason::HashPredicate)?;
        }

        return Ok(());
    }

    /// Emits the final non-empty remainder chunk.
    fn finish(
        &mut self,
        next_record_index: RecordPosition,
    ) -> Result<(), ChunkerError>
    {
        if self.chunk_records != RecordCount::from(0_u32) {
            let expected_end_record = self.chunk_start_record.checked_advance(
                RecordDistance::from(self.chunk_records),
                ArithmeticOperation::RecordIndex,
            )?;
            if expected_end_record != next_record_index {
                return Err(ChunkerError::ArithmeticOverflow {
                    operation: ArithmeticOperation::RecordIndex,
                });
            }
            self.emit_boundary(BoundaryReason::FinalRemainder)?;
        }

        return Ok(());
    }

    /// Returns allocated chunk spans after scanning is complete.
    fn into_chunks(self) -> Vec<ChunkSpan>
    {
        return self.chunks;
    }

    /// Returns whether the current chunk has satisfied minimum byte and record
    /// limits.
    const fn chunk_satisfies_minimum_limits(&self) -> CutDecision
    {
        return CutDecision(
            self.chunk_bytes.0 >= self.limits.min_bytes().0
                && self.chunk_records.0 >= self.limits.min_records().0,
        );
    }

    /// Returns whether the current complete-record boundary satisfies the hash
    /// predicate.
    const fn hash_predicate_allows_cut(&self) -> CutDecision
    {
        if !self.chunk_satisfies_minimum_limits().0 {
            return CutDecision(false);
        }

        return CutDecision((self.state.0 & self.cut_mask.0) == 0_u64);
    }

    /// Emits a boundary for the current non-empty chunk and resets chunk-local
    /// state.
    fn emit_boundary(
        &mut self,
        reason: BoundaryReason,
    ) -> Result<(), ChunkerError>
    {
        if self.chunk_records == RecordCount::from(0_u32) {
            return Ok(());
        }

        let record_end = self.chunk_start_record.checked_advance(
            RecordDistance::from(self.chunk_records),
            ArithmeticOperation::RecordIndex,
        )?;
        self.chunks.push(ChunkSpan::new(
            ByteSpan::new(self.chunk_start_byte, self.last_record_end),
            RecordSpan::new(self.chunk_start_record, record_end),
            reason,
        ));
        self.chunk_start_byte = self.last_record_end;
        self.chunk_start_record = record_end;
        self.chunk_bytes = ByteCount::from(0_u64);
        self.chunk_records = RecordCount::from(0_u32);
        self.state = self.initial_state;

        return Ok(());
    }
}

/// Consumes bytes into the FastCDC-inspired chunk-local Gear state.
fn consume_record_bytes(
    mut state: GearState,
    record: CanonicalRecord<'_>,
) -> GearState
{
    for byte_ref in record.as_ref() {
        let byte = InputByte::from(*byte_ref);
        state.0 = state.0.rotate_left(0x01_u32).wrapping_add(gear_for(byte).0);
    }

    return state;
}

/// Returns the Mach v1 Gear value for a byte.
///
/// # Contract
/// - requires: nothing; every [`InputByte`] maps to a table entry.
/// - ensures: returns the corresponding `MACH_V1_GEAR_TABLE` entry.
/// - provides: the Gear mixing value for one input byte.
/// - fails: cannot fail; the fallback is unreachable because an input byte
///   always names one of the table's 256 entries.
/// - panics: none.
fn gear_for(byte: InputByte) -> GearValue
{
    let index = usize::from(byte.0);

    // `usize::from(byte)` is always in `0..=255` and `MACH_V1_GEAR_TABLE` has
    // exactly 256 entries, so the lookup always resolves; the fallback keeps the
    // access total without `unsafe` (gandr forbids partial functions).
    return GearValue(MACH_V1_GEAR_TABLE.get(index).copied().unwrap_or(0_u64));
}

/// Returns a predicate mask whose expected interval tracks the target size.
const fn cut_mask_for_target(target_bytes: ByteCount) -> CutMask
{
    if target_bytes.0 <= 0x01_u64 {
        return CutMask(0_u64);
    }

    let Some(power) = target_bytes.0.checked_next_power_of_two()
    else {
        return CutMask(u64::MAX);
    };
    let Some(mask) = power.checked_sub(0x01_u64)
    else {
        return CutMask(0_u64);
    };

    return CutMask(mask);
}

/// Derives deterministic chunk-local initial state from the committed seed
/// policy.
fn derive_initial_state(seed_policy: &SeedPolicy) -> GearState
{
    let mut state = GEAR_STATE_IV ^ u64::from(u8::from(seed_policy.kind()));
    for byte_ref in seed_policy.salt().as_ref() {
        let byte = *byte_ref;
        state = state.rotate_left(0x05_u32) ^ u64::from(byte);
        state = state.wrapping_mul(SEED_MIX_MULTIPLIER);
    }

    return GearState(state);
}

/// Builds the fixed-order parameter commitment bytes.
fn build_parameter_commitment(
    algorithm_version: AlgorithmVersion,
    gear_table_version: GearTableVersion,
    seed_policy: &SeedPolicy,
    normalization_policy: NormalizationPolicy,
    record_boundary_rule: RecordBoundaryRule,
    limits: &ChunkLimits,
) -> ParameterCommitment
{
    return ParameterCommitment {
        bytes: core::array::from_fn(|index| {
            return commitment_byte_at(
                CommitmentIndex::from(index),
                algorithm_version,
                gear_table_version,
                seed_policy,
                normalization_policy,
                record_boundary_rule,
                limits,
            )
            .0;
        }),
    };
}

/// Returns one byte from the parameter commitment by position.
fn commitment_byte_at(
    index: CommitmentIndex,
    algorithm_version: AlgorithmVersion,
    gear_table_version: GearTableVersion,
    seed_policy: &SeedPolicy,
    normalization_policy: NormalizationPolicy,
    record_boundary_rule: RecordBoundaryRule,
    limits: &ChunkLimits,
) -> CommitmentByte
{
    return match index.0 {
        | 0x00_usize ..= 0x07_usize => magic_byte(index),
        | 0x08_usize ..= 0x09_usize => u16_be_byte(
            CommitmentWord::from(COMMITMENT_FORMAT_VERSION),
            relative_index(
                index,
                CommitmentOffset::from(COMMITMENT_FORMAT_VERSION_OFFSET),
            ),
        ),
        | 0x0A_usize ..= 0x0B_usize => u16_be_byte(
            CommitmentWord::from(u16::from(algorithm_version)),
            relative_index(index, CommitmentOffset::from(COMMITMENT_ALGORITHM_OFFSET)),
        ),
        | 0x0C_usize ..= 0x0D_usize => u16_be_byte(
            CommitmentWord::from(u16::from(gear_table_version)),
            relative_index(index, CommitmentOffset::from(COMMITMENT_TABLE_OFFSET)),
        ),
        | 0x0E_usize => CommitmentByte::from(u8::from(seed_policy.kind())),
        | 0x0F_usize ..= 0x2E_usize => salt_byte(
            seed_policy,
            relative_index(index, CommitmentOffset::from(COMMITMENT_SALT_OFFSET)),
        ),
        | 0x2F_usize => CommitmentByte::from(u8::from(normalization_policy)),
        | 0x30_usize => CommitmentByte::from(u8::from(record_boundary_rule)),
        | 0x31_usize ..= 0x38_usize => u64_be_byte(
            limits.min_bytes(),
            relative_index(index, CommitmentOffset::from(COMMITMENT_MIN_BYTES_OFFSET)),
        ),
        | 0x39_usize ..= 0x40_usize => u64_be_byte(
            limits.target_bytes(),
            relative_index(
                index,
                CommitmentOffset::from(COMMITMENT_TARGET_BYTES_OFFSET),
            ),
        ),
        | 0x41_usize ..= 0x48_usize => u64_be_byte(
            limits.max_bytes(),
            relative_index(index, CommitmentOffset::from(COMMITMENT_MAX_BYTES_OFFSET)),
        ),
        | 0x49_usize ..= 0x4C_usize => u32_be_byte(
            limits.min_records(),
            relative_index(index, CommitmentOffset::from(COMMITMENT_MIN_RECORDS_OFFSET)),
        ),
        | 0x4D_usize ..= 0x50_usize => u32_be_byte(
            limits.target_records(),
            relative_index(
                index,
                CommitmentOffset::from(COMMITMENT_TARGET_RECORDS_OFFSET),
            ),
        ),
        | 0x51_usize ..= 0x54_usize => u32_be_byte(
            limits.max_records(),
            relative_index(index, CommitmentOffset::from(COMMITMENT_MAX_RECORDS_OFFSET)),
        ),
        | _other => CommitmentByte::from(0_u8),
    };
}

/// Returns one magic byte by position.
const fn magic_byte(index: CommitmentIndex) -> CommitmentByte
{
    return CommitmentByte(match index.0 {
        | 0x00_usize => b'M',
        | 0x01_usize => b'P',
        | 0x02_usize => b'B',
        | 0x03_usize => b'C',
        | 0x04_usize => b'H',
        | 0x05_usize => b'K',
        | 0x06_usize => b'0',
        | 0x07_usize => b'1',
        | _other => 0_u8,
    });
}

/// Returns one big-endian byte from a 16-bit commitment field.
const fn u16_be_byte(
    value: CommitmentWord,
    index: CommitmentIndex,
) -> CommitmentByte
{
    let [b0, b1] = value.0.to_be_bytes();
    return CommitmentByte(match index.0 {
        | 0x00_usize => b0,
        | 0x01_usize => b1,
        | _other => 0_u8,
    });
}

/// Computes a commitment position relative to a known field offset.
const fn relative_index(
    index: CommitmentIndex,
    offset: CommitmentOffset,
) -> CommitmentIndex
{
    if let Some(relative) = index.0.checked_sub(offset.0) {
        return CommitmentIndex(relative);
    }

    return CommitmentIndex(usize::MAX);
}

/// Returns one salt byte by position.
fn salt_byte(
    seed_policy: &SeedPolicy,
    index: CommitmentIndex,
) -> CommitmentByte
{
    let mut cursor = 0_usize;
    for byte_ref in seed_policy.salt().as_ref() {
        if cursor == index.0 {
            return CommitmentByte::from(*byte_ref);
        }
        cursor = match cursor.checked_add(0x01_usize) {
            | Some(next) => next,
            | None => return CommitmentByte::from(0_u8),
        };
    }

    return CommitmentByte::from(0_u8);
}

/// Returns one big-endian byte from a byte-count commitment field.
const fn u64_be_byte(
    value: ByteCount,
    index: CommitmentIndex,
) -> CommitmentByte
{
    let [b0, b1, b2, b3, b4, b5, b6, b7] = value.0.to_be_bytes();
    return CommitmentByte(match index.0 {
        | 0x00_usize => b0,
        | 0x01_usize => b1,
        | 0x02_usize => b2,
        | 0x03_usize => b3,
        | 0x04_usize => b4,
        | 0x05_usize => b5,
        | 0x06_usize => b6,
        | 0x07_usize => b7,
        | _other => 0_u8,
    });
}

/// Returns one big-endian byte from a record-count commitment field.
const fn u32_be_byte(
    value: RecordCount,
    index: CommitmentIndex,
) -> CommitmentByte
{
    let [b0, b1, b2, b3] = value.0.to_be_bytes();
    return CommitmentByte(match index.0 {
        | 0x00_usize => b0,
        | 0x01_usize => b1,
        | 0x02_usize => b2,
        | 0x03_usize => b3,
        | _other => 0_u8,
    });
}
