concrete GandrDocsLexHtml of GandrDocsLex = GandrDocsHtml ** {
  lin
    term_acceleration_band = { key = "acceleration-band" ; text = "acceleration band" } ;
    term_boundary_polarity = { key = "boundary-polarity" ; text = "Boundary polarity" } ;
    term_boundary_theorem = { key = "boundary-theorem" ; text = "boundary theorem" } ;
    term_canonical_schedule = { key = "canonical-schedule" ; text = "canonical schedule" } ;
    term_cartesian_double_theory = { key = "cartesian-double-theory" ; text = "cartesian double theory" } ;
    term_causal_signature = { key = "causal-signature" ; text = "causal signature" } ;
    term_cc_normal_form = { key = "cc-normal-form" ; text = "CC-normal form" } ;
    term_cell_store = { key = "cell-store" ; text = "cell store" } ;
    term_cell_visible_fragment = { key = "cell-visible-fragment" ; text = "cell-visible fragment" } ;
    term_certificate = { key = "certificate" ; text = "certificate" } ;
    term_code_universe = { key = "code-universe" ; text = "code universe" } ;
    term_coend = { key = "coend" ; text = "end" } ;
    term_command = { key = "command" ; text = "command" } ;
    term_command_cell = { key = "command-cell" ; text = "cell" } ;
    term_command_il = { key = "command-il" ; text = "polarized command IL" } ;
    term_completeness_contract = { key = "completeness-contract" ; text = "completeness contract" } ;
    term_completion = { key = "completion" ; text = "completion" } ;
    term_component = { key = "component" ; text = "component" } ;
    term_computation_type = { key = "computation-type" ; text = "computation type" } ;
    term_consumer = { key = "consumer" ; text = "consumer" } ;
    term_conversion_firewall = { key = "conversion-firewall" ; text = "conversion firewall" } ;
    term_convolution = { key = "convolution" ; text = "convolution" } ;
    term_core_ir = { key = "core-ir" ; text = "core IR" } ;
    term_crdc = { key = "crdc" ; text = "compositional rewriting double category" } ;
    term_cut = { key = "cut" ; text = "cut" } ;
    term_data_declaration = { key = "data-declaration" ; text = "data declaration" } ;
    term_decl_table = { key = "decl-table" ; text = "decl table" } ;
    term_decomposition_space = { key = "decomposition-space" ; text = "decomposition space" } ;
    term_directed_hom = { key = "directed-hom" ; text = "directed hom" } ;
    term_directed_j = { key = "directed-j" ; text = "directed J" } ;
    term_directed_rewrite = { key = "directed-rewrite" ; text = "directed rewrite" } ;
    term_directed_variance = { key = "directed-variance" ; text = "directed variance" } ;
    term_direction_sigil = { key = "direction-sigil" ; text = "direction sigil" } ;
    term_effect_graded_returner = { key = "effect-graded-returner" ; text = "effect-graded returner" } ;
    term_effect_row = { key = "effect-row" ; text = "effect row" } ;
    term_effect_signature = { key = "effect-signature" ; text = "effect signature" } ;
    term_exhaustiveness = { key = "exhaustiveness" ; text = "exhaustiveness" } ;
    term_factorization_preorder = { key = "factorization-preorder" ; text = "factorization preordered" } ;
    term_focusing = { key = "focusing" ; text = "focusing" } ;
    term_forbidden_relation = { key = "forbidden-relation" ; text = "forbidden relations" } ;
    term_frozen_core = { key = "frozen-core" ; text = "frozen core" } ;
    term_fusion_by_completion = { key = "fusion-by-completion" ; text = "fusion by completion" } ;
    term_generative_nominal = { key = "generative-nominal" ; text = "generative and nominal" } ;
    term_grade = { key = "grade" ; text = "grade" } ;
    term_grade_carrier = { key = "grade-carrier" ; text = "grade carrier" } ;
    term_gradual_hole = { key = "gradual-hole" ; text = "gradual hole" } ;
    term_host_effect_seam = { key = "host-effect-seam" ; text = "host-effect seam" } ;
    term_host_handler = { key = "host-handler" ; text = "host handler" } ;
    term_host_reply = { key = "host-reply" ; text = "host reply" } ;
    term_identity_eliminator = { key = "identity-eliminator" ; text = "identity eliminator" } ;
    term_instantiation_slot = { key = "instantiation-slot" ; text = "instantiation slot" } ;
    term_interchange_laxator = { key = "interchange-laxator" ; text = "interchange laxator" } ;
    term_l_machine = { key = "l-machine" ; text = "L machine" } ;
    term_levy_area = { key = "levy-area" ; text = "Lévy area" } ;
    term_literature_correspondence = { key = "literature-correspondence" ; text = "literature correspondence" } ;
    term_loose_arrow = { key = "loose-arrow" ; text = "loose arrow" } ;
    term_matching_modulo = { key = "matching-modulo" ; text = "matching modulo" } ;
    term_message_theory = { key = "message-theory" ; text = "message theories" } ;
    term_metatheory_currency = { key = "metatheory-currency" ; text = "metatheory currency" } ;
    term_native_builtin = { key = "native-builtin" ; text = "native builtin" } ;
    term_operation_frame = { key = "operation-frame" ; text = "operation frame" } ;
    term_overlap = { key = "overlap" ; text = "overlap" } ;
    term_overlap_support = { key = "overlap-support" ; text = "overlap support" } ;
    term_path_type = { key = "path-type" ; text = "path type" } ;
    term_pattern = { key = "pattern" ; text = "pattern matching" } ;
    term_phase_gates = { key = "phase-gates" ; text = "phase gates" } ;
    term_physical_profile = { key = "physical-profile" ; text = "physical profile" } ;
    term_polarity_orientation = { key = "polarity-orientation" ; text = "polarity orientation" } ;
    term_polygraph_presentation = { key = "polygraph-presentation" ; text = "polygraph presentation" } ;
    term_preserved_boundary = { key = "preserved-boundary" ; text = "preserved boundary" } ;
    term_primitive_tracelet = { key = "primitive-tracelet" ; text = "primitive" } ;
    term_producer = { key = "producer" ; text = "producer" } ;
    term_productivity_ladder = { key = "productivity-ladder" ; text = "productivity ladder" } ;
    term_produoidal_category = { key = "produoidal-category" ; text = "produoidal category" } ;
    term_produoidal_normalization = { key = "produoidal-normalization" ; text = "Produoidal normalization" } ;
    term_promotion_decision = { key = "promotion-decision" ; text = "promotion decision" } ;
    term_prose = { key = "prose" ; text = "prose" } ;
    term_proterm = { key = "proterm" ; text = "proterm" } ;
    term_protype = { key = "protype" ; text = "protype" } ;
    term_protype_isomorphism = { key = "protype-isomorphism" ; text = "protype isomorphism" } ;
    term_recursion_marker = { key = "recursion-marker" ; text = "recursion marker" } ;
    term_recursive_scope = { key = "recursive-scope" ; text = "recursive scope" } ;
    term_reflection_face = { key = "reflection-face" ; text = "reflection face" } ;
    term_reified_stack = { key = "reified-stack" ; text = "reified stack" } ;
    term_replay_equivalence = { key = "replay-equivalence" ; text = "replay-equivalence" } ;
    term_replay_plan = { key = "replay-plan" ; text = "replay plan" } ;
    term_representable = { key = "representable" ; text = "representable" } ;
    term_residue = { key = "residue" ; text = "residue" } ;
    term_respect_obligation = { key = "respect-obligation" ; text = "respect obligation" } ;
    term_restriction = { key = "restriction" ; text = "restriction" } ;
    term_scale_as_ideal = { key = "scale-as-ideal" ; text = "scale-as-ideal" } ;
    term_semantic_currency = { key = "semantic-currency" ; text = "semantic currency" } ;
    term_shift_equivalence = { key = "shift-equivalence" ; text = "shift equivalence" } ;
    term_sigma_type = { key = "sigma-type" ; text = "dependent pair" } ;
    term_split_motive = { key = "split-motive" ; text = "split motive" } ;
    term_status = { key = "status" ; text = "status" } ;
    term_structural_subtyping = { key = "structural-subtyping" ; text = "structural subtyping" } ;
    term_structural_value_equality = { key = "structural-value-equality" ; text = "no-reduction structural value equality" } ;
    term_structure_univalence = { key = "structure-univalence" ; text = "structure-univalence" } ;
    term_substrate_shape = { key = "substrate-shape" ; text = "substrate shape" } ;
    term_tabulator = { key = "tabulator" ; text = "tabulator" } ;
    term_tight_arrow = { key = "tight-arrow" ; text = "tight arrow" } ;
    term_tracelet = { key = "tracelet" ; text = "tracelet" } ;
    term_tracelet_algebra = { key = "tracelet-algebra" ; text = "tracelet algebra" } ;
    term_tracelet_normal_form = { key = "tracelet-normal-form" ; text = "tracelet normal form" } ;
    term_two_region_store = { key = "two-region-store" ; text = "two-region store" } ;
    term_two_zone_context = { key = "two-zone-context" ; text = "two-zone context" } ;
    term_value_type = { key = "value-type" ; text = "value type" } ;
    term_variance = { key = "variance" ; text = "variance" } ;
    term_vdc_cell = { key = "vdc-cell" ; text = "multi-ary cell" } ;
    term_virtual_double_category = { key = "virtual-double-category" ; text = "virtual double category" } ;
    term_virtual_line = { key = "virtual-line" ; text = "virtual line" } ;
    term_without_k_unification = { key = "without-k-unification" ; text = "without-K-equivalent" } ;
    term_zigzag = { key = "zigzag" ; text = "zigzag double category" } ;
    cite_A_10 = { key = "A-10" } ;
    cite_A_11a = { key = "A-11a" } ;
    cite_A_11b = { key = "A-11b" } ;
    cite_A_12a = { key = "A-12a" } ;
    cite_A_12b = { key = "A-12b" } ;
    cite_A_12c = { key = "A-12c" } ;
    cite_A_13 = { key = "A-13" } ;
    cite_A_14 = { key = "A-14" } ;
    cite_A_15a = { key = "A-15a" } ;
    cite_A_15b = { key = "A-15b" } ;
    cite_A_16 = { key = "A-16" } ;
    cite_A_17 = { key = "A-17" } ;
    cite_A_18 = { key = "A-18" } ;
    cite_A_19 = { key = "A-19" } ;
    cite_A_1a = { key = "A-1a" } ;
    cite_A_1b = { key = "A-1b" } ;
    cite_A_2 = { key = "A-2" } ;
    cite_A_20 = { key = "A-20" } ;
    cite_A_21 = { key = "A-21" } ;
    cite_A_22a = { key = "A-22a" } ;
    cite_A_22b = { key = "A-22b" } ;
    cite_A_23 = { key = "A-23" } ;
    cite_A_24 = { key = "A-24" } ;
    cite_A_25 = { key = "A-25" } ;
    cite_A_26a = { key = "A-26a" } ;
    cite_A_26b = { key = "A-26b" } ;
    cite_A_27 = { key = "A-27" } ;
    cite_A_28 = { key = "A-28" } ;
    cite_A_29 = { key = "A-29" } ;
    cite_A_3 = { key = "A-3" } ;
    cite_A_30 = { key = "A-30" } ;
    cite_A_31 = { key = "A-31" } ;
    cite_A_32 = { key = "A-32" } ;
    cite_A_33 = { key = "A-33" } ;
    cite_A_34 = { key = "A-34" } ;
    cite_A_35 = { key = "A-35" } ;
    cite_A_36 = { key = "A-36" } ;
    cite_A_37 = { key = "A-37" } ;
    cite_A_38 = { key = "A-38" } ;
    cite_A_39 = { key = "A-39" } ;
    cite_A_4 = { key = "A-4" } ;
    cite_A_40 = { key = "A-40" } ;
    cite_A_41 = { key = "A-41" } ;
    cite_A_42 = { key = "A-42" } ;
    cite_A_5 = { key = "A-5" } ;
    cite_A_6a = { key = "A-6a" } ;
    cite_A_6b = { key = "A-6b" } ;
    cite_A_7a = { key = "A-7a" } ;
    cite_A_7b = { key = "A-7b" } ;
    cite_A_8a = { key = "A-8a" } ;
    cite_A_8b = { key = "A-8b" } ;
    cite_A_9 = { key = "A-9" } ;
    cite_B_1 = { key = "B-1" } ;
    cite_B_10 = { key = "B-10" } ;
    cite_B_11 = { key = "B-11" } ;
    cite_B_12 = { key = "B-12" } ;
    cite_B_13 = { key = "B-13" } ;
    cite_B_2 = { key = "B-2" } ;
    cite_B_3 = { key = "B-3" } ;
    cite_B_4 = { key = "B-4" } ;
    cite_B_5 = { key = "B-5" } ;
    cite_B_6 = { key = "B-6" } ;
    cite_B_7 = { key = "B-7" } ;
    cite_B_8 = { key = "B-8" } ;
    cite_B_9 = { key = "B-9" } ;
    cite_C_1 = { key = "C-1" } ;
    cite_C_2 = { key = "C-2" } ;
    cite_C_3 = { key = "C-3" } ;
    cite_C_4 = { key = "C-4" } ;
    cite_C_5 = { key = "C-5" } ;
    cite_C_6 = { key = "C-6" } ;
    cite_C_7 = { key = "C-7" } ;
    cite_C_8 = { key = "C-8" } ;
    cite_D_1 = { key = "D-1" } ;
    cite_D_10 = { key = "D-10" } ;
    cite_D_11 = { key = "D-11" } ;
    cite_D_12 = { key = "D-12" } ;
    cite_D_2 = { key = "D-2" } ;
    cite_D_3a = { key = "D-3a" } ;
    cite_D_3b = { key = "D-3b" } ;
    cite_D_4 = { key = "D-4" } ;
    cite_D_5 = { key = "D-5" } ;
    cite_D_6 = { key = "D-6" } ;
    cite_D_7 = { key = "D-7" } ;
    cite_D_8 = { key = "D-8" } ;
    cite_D_9 = { key = "D-9" } ;
    cite_E_1 = { key = "E-1" } ;
    cite_E_10 = { key = "E-10" } ;
    cite_E_2 = { key = "E-2" } ;
    cite_E_3 = { key = "E-3" } ;
    cite_E_4 = { key = "E-4" } ;
    cite_E_5 = { key = "E-5" } ;
    cite_E_6 = { key = "E-6" } ;
    cite_E_7 = { key = "E-7" } ;
    cite_E_8 = { key = "E-8" } ;
    cite_E_9 = { key = "E-9" } ;
    cite_F_1 = { key = "F-1" } ;
    cite_F_2 = { key = "F-2" } ;
    cite_F_3 = { key = "F-3" } ;
    cite_F_4 = { key = "F-4" } ;
    cite_F_5 = { key = "F-5" } ;
    cite_F_6 = { key = "F-6" } ;
    cite_F_7 = { key = "F-7" } ;
    cite_F_8 = { key = "F-8" } ;
    cite_F_9 = { key = "F-9" } ;
    cite_G_1 = { key = "G-1" } ;
    cite_G_2 = { key = "G-2" } ;
    cite_G_3 = { key = "G-3" } ;
    cite_G_4 = { key = "G-4" } ;
    cite_G_5 = { key = "G-5" } ;
    cite_G_6 = { key = "G-6" } ;
    cite_G_7 = { key = "G-7" } ;
    cite_G_8 = { key = "G-8" } ;
    cite_H_1 = { key = "H-1" } ;
    cite_H_2 = { key = "H-2" } ;
    cite_H_3 = { key = "H-3" } ;
    cite_H_4 = { key = "H-4" } ;
    cite_H_5 = { key = "H-5" } ;
    cite_H_6 = { key = "H-6" } ;
    cite_H_7 = { key = "H-7" } ;
    cite_I_1 = { key = "I-1" } ;
    cite_I_10 = { key = "I-10" } ;
    cite_I_11 = { key = "I-11" } ;
    cite_I_12 = { key = "I-12" } ;
    cite_I_13 = { key = "I-13" } ;
    cite_I_2 = { key = "I-2" } ;
    cite_I_3a = { key = "I-3a" } ;
    cite_I_3b = { key = "I-3b" } ;
    cite_I_4 = { key = "I-4" } ;
    cite_I_5 = { key = "I-5" } ;
    cite_I_6 = { key = "I-6" } ;
    cite_I_7a = { key = "I-7a" } ;
    cite_I_7b = { key = "I-7b" } ;
    cite_I_8 = { key = "I-8" } ;
    cite_I_9 = { key = "I-9" } ;
    cite_J_1 = { key = "J-1" } ;
    cite_J_10 = { key = "J-10" } ;
    cite_J_11 = { key = "J-11" } ;
    cite_J_12 = { key = "J-12" } ;
    cite_J_13 = { key = "J-13" } ;
    cite_J_14 = { key = "J-14" } ;
    cite_J_15 = { key = "J-15" } ;
    cite_J_16 = { key = "J-16" } ;
    cite_J_17 = { key = "J-17" } ;
    cite_J_18 = { key = "J-18" } ;
    cite_J_19 = { key = "J-19" } ;
    cite_J_2 = { key = "J-2" } ;
    cite_J_20 = { key = "J-20" } ;
    cite_J_21 = { key = "J-21" } ;
    cite_J_23 = { key = "J-23" } ;
    cite_J_24 = { key = "J-24" } ;
    cite_J_25a = { key = "J-25a" } ;
    cite_J_25b = { key = "J-25b" } ;
    cite_J_25c = { key = "J-25c" } ;
    cite_J_26 = { key = "J-26" } ;
    cite_J_27 = { key = "J-27" } ;
    cite_J_28 = { key = "J-28" } ;
    cite_J_29 = { key = "J-29" } ;
    cite_J_3 = { key = "J-3" } ;
    cite_J_30 = { key = "J-30" } ;
    cite_J_31 = { key = "J-31" } ;
    cite_J_32 = { key = "J-32" } ;
    cite_J_33 = { key = "J-33" } ;
    cite_J_34 = { key = "J-34" } ;
    cite_J_35 = { key = "J-35" } ;
    cite_J_36 = { key = "J-36" } ;
    cite_J_37 = { key = "J-37" } ;
    cite_J_38 = { key = "J-38" } ;
    cite_J_39 = { key = "J-39" } ;
    cite_J_4 = { key = "J-4" } ;
    cite_J_40 = { key = "J-40" } ;
    cite_J_41 = { key = "J-41" } ;
    cite_J_42 = { key = "J-42" } ;
    cite_J_43 = { key = "J-43" } ;
    cite_J_44 = { key = "J-44" } ;
    cite_J_45 = { key = "J-45" } ;
    cite_J_46 = { key = "J-46" } ;
    cite_J_47 = { key = "J-47" } ;
    cite_J_48 = { key = "J-48" } ;
    cite_J_49 = { key = "J-49" } ;
    cite_J_5 = { key = "J-5" } ;
    cite_J_50 = { key = "J-50" } ;
    cite_J_51 = { key = "J-51" } ;
    cite_J_6 = { key = "J-6" } ;
    cite_J_7a = { key = "J-7a" } ;
    cite_J_7b = { key = "J-7b" } ;
    cite_J_8 = { key = "J-8" } ;
    cite_J_9 = { key = "J-9" } ;
    cite_K_1 = { key = "K-1" } ;
    cite_K_10 = { key = "K-10" } ;
    cite_K_11 = { key = "K-11" } ;
    cite_K_12 = { key = "K-12" } ;
    cite_K_13 = { key = "K-13" } ;
    cite_K_14 = { key = "K-14" } ;
    cite_K_15 = { key = "K-15" } ;
    cite_K_2 = { key = "K-2" } ;
    cite_K_3 = { key = "K-3" } ;
    cite_K_4 = { key = "K-4" } ;
    cite_K_5 = { key = "K-5" } ;
    cite_K_6 = { key = "K-6" } ;
    cite_K_7 = { key = "K-7" } ;
    cite_K_8 = { key = "K-8" } ;
    cite_K_9 = { key = "K-9" } ;
    cite_L_1 = { key = "L-1" } ;
    cite_L_2 = { key = "L-2" } ;
    cite_L_3 = { key = "L-3" } ;
    cite_L_4 = { key = "L-4" } ;
    cite_L_5 = { key = "L-5" } ;
    cite_L_6 = { key = "L-6" } ;
    cite_L_7 = { key = "L-7" } ;
    cite_L_8 = { key = "L-8" } ;
    cite_L_9 = { key = "L-9" } ;
    cite_M_1 = { key = "M-1" } ;
    cite_M_10 = { key = "M-10" } ;
    cite_M_11a = { key = "M-11a" } ;
    cite_M_11b = { key = "M-11b" } ;
    cite_M_12a = { key = "M-12a" } ;
    cite_M_12b = { key = "M-12b" } ;
    cite_M_13 = { key = "M-13" } ;
    cite_M_14 = { key = "M-14" } ;
    cite_M_15 = { key = "M-15" } ;
    cite_M_2a = { key = "M-2a" } ;
    cite_M_2b = { key = "M-2b" } ;
    cite_M_3 = { key = "M-3" } ;
    cite_M_4 = { key = "M-4" } ;
    cite_M_5 = { key = "M-5" } ;
    cite_M_6 = { key = "M-6" } ;
    cite_M_7 = { key = "M-7" } ;
    cite_M_8 = { key = "M-8" } ;
    cite_M_9 = { key = "M-9" } ;
    cite_N_1a = { key = "N-1a" } ;
    cite_N_1b = { key = "N-1b" } ;
    cite_N_2 = { key = "N-2" } ;
    cite_N_3 = { key = "N-3" } ;
    cite_N_4a = { key = "N-4a" } ;
    cite_N_4b = { key = "N-4b" } ;
    cite_N_4c = { key = "N-4c" } ;
    cite_N_4d = { key = "N-4d" } ;
    cite_N_5 = { key = "N-5" } ;
    cite_N_6 = { key = "N-6" } ;
    cite_N_7 = { key = "N-7" } ;
    cite_N_8 = { key = "N-8" } ;
    cite_N_9 = { key = "N-9" } ;
    cite_O_1a = { key = "O-1a" } ;
    cite_O_1b = { key = "O-1b" } ;
    cite_O_2 = { key = "O-2" } ;
    cite_O_3a = { key = "O-3a" } ;
    cite_O_3b = { key = "O-3b" } ;
    cite_O_4a = { key = "O-4a" } ;
    cite_O_4b = { key = "O-4b" } ;
    cite_O_5 = { key = "O-5" } ;
    cite_O_6 = { key = "O-6" } ;
    cite_P_1 = { key = "P-1" } ;
    cite_P_2 = { key = "P-2" } ;
    cite_P_3a = { key = "P-3a" } ;
    cite_P_3b = { key = "P-3b" } ;
    cite_P_4a = { key = "P-4a" } ;
    cite_P_4b = { key = "P-4b" } ;
    cite_P_5 = { key = "P-5" } ;
    cite_P_6a = { key = "P-6a" } ;
    cite_P_6b = { key = "P-6b" } ;
    cite_P_7 = { key = "P-7" } ;
    cite_Q_1 = { key = "Q-1" } ;
    cite_Q_10 = { key = "Q-10" } ;
    cite_Q_11 = { key = "Q-11" } ;
    cite_Q_12 = { key = "Q-12" } ;
    cite_Q_13 = { key = "Q-13" } ;
    cite_Q_14 = { key = "Q-14" } ;
    cite_Q_15 = { key = "Q-15" } ;
    cite_Q_16 = { key = "Q-16" } ;
    cite_Q_17 = { key = "Q-17" } ;
    cite_Q_18 = { key = "Q-18" } ;
    cite_Q_19 = { key = "Q-19" } ;
    cite_Q_2 = { key = "Q-2" } ;
    cite_Q_20 = { key = "Q-20" } ;
    cite_Q_21 = { key = "Q-21" } ;
    cite_Q_22 = { key = "Q-22" } ;
    cite_Q_23 = { key = "Q-23" } ;
    cite_Q_24 = { key = "Q-24" } ;
    cite_Q_25 = { key = "Q-25" } ;
    cite_Q_3 = { key = "Q-3" } ;
    cite_Q_4 = { key = "Q-4" } ;
    cite_Q_5 = { key = "Q-5" } ;
    cite_Q_6a = { key = "Q-6a" } ;
    cite_Q_6b = { key = "Q-6b" } ;
    cite_Q_7a = { key = "Q-7a" } ;
    cite_Q_7b = { key = "Q-7b" } ;
    cite_Q_8 = { key = "Q-8" } ;
    cite_Q_9 = { key = "Q-9" } ;
    cite_R_1 = { key = "R-1" } ;
    cite_R_10 = { key = "R-10" } ;
    cite_R_11 = { key = "R-11" } ;
    cite_R_12 = { key = "R-12" } ;
    cite_R_13 = { key = "R-13" } ;
    cite_R_14 = { key = "R-14" } ;
    cite_R_15 = { key = "R-15" } ;
    cite_R_16 = { key = "R-16" } ;
    cite_R_17 = { key = "R-17" } ;
    cite_R_18 = { key = "R-18" } ;
    cite_R_19 = { key = "R-19" } ;
    cite_R_2 = { key = "R-2" } ;
    cite_R_20 = { key = "R-20" } ;
    cite_R_21 = { key = "R-21" } ;
    cite_R_22 = { key = "R-22" } ;
    cite_R_23 = { key = "R-23" } ;
    cite_R_24 = { key = "R-24" } ;
    cite_R_25 = { key = "R-25" } ;
    cite_R_26 = { key = "R-26" } ;
    cite_R_27 = { key = "R-27" } ;
    cite_R_28 = { key = "R-28" } ;
    cite_R_29 = { key = "R-29" } ;
    cite_R_3 = { key = "R-3" } ;
    cite_R_30 = { key = "R-30" } ;
    cite_R_31 = { key = "R-31" } ;
    cite_R_32 = { key = "R-32" } ;
    cite_R_33 = { key = "R-33" } ;
    cite_R_34 = { key = "R-34" } ;
    cite_R_35 = { key = "R-35" } ;
    cite_R_36 = { key = "R-36" } ;
    cite_R_37 = { key = "R-37" } ;
    cite_R_38 = { key = "R-38" } ;
    cite_R_39 = { key = "R-39" } ;
    cite_R_4 = { key = "R-4" } ;
    cite_R_40 = { key = "R-40" } ;
    cite_R_41 = { key = "R-41" } ;
    cite_R_42 = { key = "R-42" } ;
    cite_R_43 = { key = "R-43" } ;
    cite_R_44 = { key = "R-44" } ;
    cite_R_45 = { key = "R-45" } ;
    cite_R_46 = { key = "R-46" } ;
    cite_R_47 = { key = "R-47" } ;
    cite_R_48 = { key = "R-48" } ;
    cite_R_49 = { key = "R-49" } ;
    cite_R_5 = { key = "R-5" } ;
    cite_R_50 = { key = "R-50" } ;
    cite_R_51 = { key = "R-51" } ;
    cite_R_52 = { key = "R-52" } ;
    cite_R_53 = { key = "R-53" } ;
    cite_R_54 = { key = "R-54" } ;
    cite_R_55 = { key = "R-55" } ;
    cite_R_56 = { key = "R-56" } ;
    cite_R_57 = { key = "R-57" } ;
    cite_R_58 = { key = "R-58" } ;
    cite_R_59 = { key = "R-59" } ;
    cite_R_6 = { key = "R-6" } ;
    cite_R_60 = { key = "R-60" } ;
    cite_R_7 = { key = "R-7" } ;
    cite_R_8 = { key = "R-8" } ;
    cite_R_9 = { key = "R-9" } ;
    cite_S_1 = { key = "S-1" } ;
    cite_S_2 = { key = "S-2" } ;
    cite_S_3 = { key = "S-3" } ;
    cite_S_4 = { key = "S-4" } ;
    cite_S_5 = { key = "S-5" } ;
    cite_S_6 = { key = "S-6" } ;
    cite_S_7 = { key = "S-7" } ;
    cite_S_8 = { key = "S-8" } ;
    cite_S_9 = { key = "S-9" } ;
    cite_T_1 = { key = "T-1" } ;
    cite_T_10 = { key = "T-10" } ;
    cite_T_11 = { key = "T-11" } ;
    cite_T_12 = { key = "T-12" } ;
    cite_T_13 = { key = "T-13" } ;
    cite_T_14 = { key = "T-14" } ;
    cite_T_2 = { key = "T-2" } ;
    cite_T_3 = { key = "T-3" } ;
    cite_T_4 = { key = "T-4" } ;
    cite_T_5 = { key = "T-5" } ;
    cite_T_6 = { key = "T-6" } ;
    cite_T_7 = { key = "T-7" } ;
    cite_T_8 = { key = "T-8" } ;
    cite_T_9 = { key = "T-9" } ;
    cite_U_1 = { key = "U-1" } ;
    cite_U_2 = { key = "U-2" } ;
    cite_U_3 = { key = "U-3" } ;
    cite_U_4 = { key = "U-4" } ;
    cite_U_5 = { key = "U-5" } ;
    cite_U_6 = { key = "U-6" } ;
    cite_U_7 = { key = "U-7" } ;
    cite_U_8 = { key = "U-8" } ;
    cite_U_9 = { key = "U-9" } ;
    cite_V_1 = { key = "V-1" } ;
    cite_V_2 = { key = "V-2" } ;
    cite_V_3 = { key = "V-3" } ;
    cite_V_4 = { key = "V-4" } ;
    cite_V_5 = { key = "V-5" } ;
    cite_V_6 = { key = "V-6" } ;
    cite_V_7 = { key = "V-7" } ;
    cite_V_8 = { key = "V-8" } ;
    cite_V_9 = { key = "V-9" } ;
    anchor_cert_consequences = { id = "cert-consequences" ; title = "Consequences for the engine and staging" } ;
    anchor_cert_laxness = { id = "cert-laxness" ; title = "Laxness is structural: the coherence caveats" } ;
    anchor_cert_metatheory = { id = "cert-metatheory" ; title = "The metatheory face of the two lanes" } ;
    anchor_cert_negatives = { id = "cert-negatives" ; title = "Ruled-out routes, kept vocabulary, and re-opening conditions" } ;
    anchor_cert_overview = { id = "cert-overview" ; title = "Overview and the decision" } ;
    anchor_cert_polarization = { id = "cert-polarization" ; title = "Polarized boundaries and the message-theory target" } ;
    anchor_cert_produoidal = { id = "cert-produoidal" ; title = "The produoidal reading of the two modes" } ;
    anchor_certificate_composition = { id = "certificate-composition" ; title = "Certificate composition: the produoidal normal form and polarized boundaries" } ;
    anchor_ci_comp_types = { id = "ci-comp-types" ; title = "Computation-type shapes" } ;
    anchor_ci_contexts = { id = "ci-contexts" ; title = "Contexts and the machine inventory" } ;
    anchor_ci_effects = { id = "ci-effects" ; title = "The effect row on F" } ;
    anchor_ci_firewall = { id = "ci-firewall" ; title = "The conversion firewall, corrected" } ;
    anchor_ci_grades = { id = "ci-grades" ; title = "Grades on U" } ;
    anchor_ci_hooks = { id = "ci-hooks" ; title = "Decided-direction hooks" } ;
    anchor_ci_hooks_cost = { id = "ci-hooks-cost" ; title = "The phase modality and the cost effect" } ;
    anchor_ci_hooks_dependent = { id = "ci-hooks-dependent" ; title = "Dependent elimination and conversion" } ;
    anchor_ci_hooks_erasure = { id = "ci-hooks-erasure" ; title = "The erasure functor" } ;
    anchor_ci_overview = { id = "ci-overview" ; title = "The contract and its discipline" } ;
    anchor_ci_polarity = { id = "ci-polarity" ; title = "Polarity: two sorts and the adjunction" } ;
    anchor_ci_realization = { id = "ci-realization" ; title = "The realization map" } ;
    anchor_ci_staged = { id = "ci-staged" ; title = "Staged extension points" } ;
    anchor_ci_terms = { id = "ci-terms" ; title = "Term node shapes" } ;
    anchor_ci_value_types = { id = "ci-value-types" ; title = "Value-type shapes" } ;
    anchor_component_vocabulary = { id = "component-vocabulary" ; title = "The component vocabulary" } ;
    anchor_core_ir = { id = "core-ir" ; title = "The core IR contract: the frozen call-by-push-value substrate" } ;
    anchor_corr_overview = { id = "corr-overview" ; title = "The correspondence record" } ;
    anchor_corr_scope = { id = "corr-scope" ; title = "Scope and non-goals" } ;
    anchor_corr_structure_univalence = { id = "corr-structure-univalence" ; title = "The structure-univalence statement-shape precedent" } ;
    anchor_corr_universe_axis = { id = "corr-universe-axis" ; title = "The universe axis is not a Π-former" } ;
    anchor_corr_vdc_lineage = { id = "corr-vdc-lineage" ; title = "Lineage of the reflection face: the virtual line, not Ruit's" } ;
    anchor_correspondence = { id = "correspondence" ; title = "The literature correspondence: gandr's lineage and citation record" } ;
    anchor_cv_blocks = { id = "cv-blocks" ; title = "Block types" } ;
    anchor_cv_def_prose = { id = "cv-def-prose" ; title = "prose (definition)" } ;
    anchor_cv_diagram = { id = "cv-diagram" ; title = "A component contains sections, which contain blocks." } ;
    anchor_cv_examples = { id = "cv-examples" ; title = "Checked examples" } ;
    anchor_cv_overview = { id = "cv-overview" ; title = "Overview" } ;
    anchor_cv_rule_app = { id = "cv-rule-app" ; title = "T-App" } ;
    anchor_data_patterns = { id = "data-patterns" ; title = "The joint data-declarations and pattern-matching surface" } ;
    anchor_dp_cyclic = { id = "dp-cyclic" ; title = "Cyclic data and the wheel firewall" } ;
    anchor_dp_data_block = { id = "dp-data-block" ; title = "The data block: constructors, operations, and directed rewrites as siblings" } ;
    anchor_dp_exhaustiveness = { id = "dp-exhaustiveness" ; title = "Exhaustiveness and compilation: Maranget, to the existing eliminators" } ;
    anchor_dp_levitation = { id = "dp-levitation" ; title = "Levitation-compatibility and the anti-retrofit checklist" } ;
    anchor_dp_matching_modulo = { id = "dp-matching-modulo" ; title = "The matching-modulo stance" } ;
    anchor_dp_nominal = { id = "dp-nominal" ; title = "Nominal identity: declarations mint named 0-cells" } ;
    anchor_dp_overview = { id = "dp-overview" ; title = "Overview and the load-bearing asymmetry" } ;
    anchor_dp_patterns = { id = "dp-patterns" ; title = "The pattern grammar" } ;
    anchor_dp_without_k = { id = "dp-without-k" ; title = "Without-K-equivalent unification" } ;
    anchor_hes_overview = { id = "hes-overview" ; title = "The seam" } ;
    anchor_hes_preserved_boundary = { id = "hes-preserved-boundary" ; title = "The preserved-boundary property" } ;
    anchor_hes_realization = { id = "hes-realization" ; title = "Realization and consumers" } ;
    anchor_host_effect_seam = { id = "host-effect-seam" ; title = "The host-effect seam" } ;
    anchor_recursion_surface = { id = "recursion-surface" ; title = "The (co)recursion surface: recursive scope and call-site evidence markers" } ;
    anchor_rs_application_syntax = { id = "rs-application-syntax" ; title = "Application syntax" } ;
    anchor_rs_architecture = { id = "rs-architecture" ; title = "Architecture and API surface" } ;
    anchor_rs_corpus_plan = { id = "rs-corpus-plan" ; title = "Corpus-examples plan" } ;
    anchor_rs_edge = { id = "rs-edge" ; title = "Edge cases and non-decisions" } ;
    anchor_rs_evidence_site = { id = "rs-evidence-site" ; title = "Where termination evidence lives" } ;
    anchor_rs_examples = { id = "rs-examples" ; title = "Examples" } ;
    anchor_rs_ladder = { id = "rs-ladder" ; title = "The productivity ladder" } ;
    anchor_rs_marker_slot = { id = "rs-marker-slot" ; title = "The instantiation slot" } ;
    anchor_rs_one_family = { id = "rs-one-family" ; title = "One def rec family" } ;
    anchor_rs_open_questions = { id = "rs-open-questions" ; title = "Open questions and residuals" } ;
    anchor_rs_overview = { id = "rs-overview" ; title = "Overview and the decision" } ;
    anchor_rs_scope_rule = { id = "rs-scope-rule" ; title = "Recursive scope and self-reference" } ;
    anchor_rs_staging = { id = "rs-staging" ; title = "Staging and gates" } ;
    anchor_rs_type_level = { id = "rs-type-level" ; title = "Type-level self-reference" } ;
    anchor_sequent_kernel = { id = "sequent-kernel" ; title = "The sequent kernel: the polarized L command IL, machine, and fusion engine (phases L0-L2)" } ;
    anchor_si_about = { id = "si-about" ; title = "About this corpus" } ;
    anchor_si_conventions = { id = "si-conventions" ; title = "Conventions" } ;
    anchor_sk_closures = { id = "sk-closures" ; title = "Closures as rewrites (the closures lane, design)" } ;
    anchor_sk_effects = { id = "sk-effects" ; title = "Effects and control as consumer patterns" } ;
    anchor_sk_focusing = { id = "sk-focusing" ; title = "Focusing: the core-to-command translation" } ;
    anchor_sk_fusion = { id = "sk-fusion" ; title = "Fusion by completion (phase L2)" } ;
    anchor_sk_fusion_engine = { id = "sk-fusion-engine" ; title = "The engine: cell store, overlap enumeration, completion" } ;
    anchor_sk_fusion_overlaps = { id = "sk-fusion-overlaps" ; title = "Critical pairs at the seam" } ;
    anchor_sk_fusion_record = { id = "sk-fusion-record" ; title = "Why completion beats pragmas, and the gate" } ;
    anchor_sk_fusion_rules = { id = "sk-fusion-rules" ; title = "What a rule becomes" } ;
    anchor_sk_fusion_scope = { id = "sk-fusion-scope" ; title = "Scope and honest limits" } ;
    anchor_sk_glued_nbe = { id = "sk-glued-nbe" ; title = "Glued NbE re-sequenced onto the L machine" } ;
    anchor_sk_il = { id = "sk-il" ; title = "The kernel IL" } ;
    anchor_sk_machine = { id = "sk-machine" ; title = "The L machine and its store" } ;
    anchor_sk_overview = { id = "sk-overview" ; title = "Overview and decisions" } ;
    anchor_sk_phase_l0 = { id = "sk-phase-l0" ; title = "Phase L0 — the command IR and focusing" } ;
    anchor_sk_phase_l1 = { id = "sk-phase-l1" ; title = "Phase L1 — the L machine and its differential" } ;
    anchor_sk_phase_l2 = { id = "sk-phase-l2" ; title = "Phase L2 — the fusion engine" } ;
    anchor_sk_phase_l3 = { id = "sk-phase-l3" ; title = "Phase L3 — the promotion decision" } ;
    anchor_sk_phases = { id = "sk-phases" ; title = "Phases and gates" } ;
    anchor_sk_strategy = { id = "sk-strategy" ; title = "Strategy as polarity orientation" } ;
    anchor_spec_index = { id = "spec-index" ; title = "gandr specification corpus" } ;
    anchor_ta_acceleration = { id = "ta-acceleration" ; title = "Acceleration band" } ;
    anchor_ta_adr = { id = "ta-adr" ; title = "Draft ADR candidate" } ;
    anchor_ta_bifibration = { id = "ta-bifibration" ; title = "Bifibration firewall" } ;
    anchor_ta_bracket = { id = "ta-bracket" ; title = "Bracket oracle" } ;
    anchor_ta_constrained = { id = "ta-constrained" ; title = "Constrained overlaps" } ;
    anchor_ta_convolution = { id = "ta-convolution" ; title = "Convolution face" } ;
    anchor_ta_corpus_plan = { id = "ta-corpus-plan" ; title = "Corpus-examples plan" } ;
    anchor_ta_crdc = { id = "ta-crdc" ; title = "crDC ladder" } ;
    anchor_ta_doctrine = { id = "ta-doctrine" ; title = "Doctrine alignment" } ;
    anchor_ta_feta = { id = "ta-feta" ; title = "Pathway queries" } ;
    anchor_ta_normal_form = { id = "ta-normal-form" ; title = "Normal form" } ;
    anchor_ta_objects = { id = "ta-objects" ; title = "Objects, aligned" } ;
    anchor_ta_open_questions = { id = "ta-open-questions" ; title = "Open questions" } ;
    anchor_ta_overview = { id = "ta-overview" ; title = "Division of labor" } ;
    anchor_ta_signatures = { id = "ta-signatures" ; title = "Causal signatures" } ;
    anchor_ta_staging = { id = "ta-staging" ; title = "Staging and gates" } ;
    anchor_tracelet_algebra = { id = "tracelet-algebra" ; title = "The tracelet algebra" } ;
    anchor_vdc_reflection = { id = "vdc-reflection" ; title = "The VDC reflection face: the rewrite layer as a virtual double category, FVDblTT and the LLV directed fragment" } ;
    anchor_vdcr_additivity = { id = "vdcr-additivity" ; title = "The reflection face gates nothing (F8)" } ;
    anchor_vdcr_certificates = { id = "vdcr-certificates" ; title = "The certificate-composition theory (F3, F4)" } ;
    anchor_vdcr_dictionary = { id = "vdcr-dictionary" ; title = "The dictionary (F1)" } ;
    anchor_vdcr_dictionary_test = { id = "vdcr-dictionary-test" ; title = "The dictionary test (F2)" } ;
    anchor_vdcr_directed = { id = "vdcr-directed" ; title = "The LLV directed fragment (F7)" } ;
    anchor_vdcr_directed_scope = { id = "vdcr-directed-scope" ; title = "Out of scope (direction only)" } ;
    anchor_vdcr_face = { id = "vdcr-face" ; title = "The reflection face: FVDblTT as the internal language (F5)" } ;
    anchor_vdcr_l1 = { id = "vdcr-l1" ; title = "Ł1 — variance-sorted reflected contexts" } ;
    anchor_vdcr_l2 = { id = "vdcr-l2" ; title = "Ł2 — hom as directed equality" } ;
    anchor_vdcr_l3 = { id = "vdcr-l3" ; title = "Ł3 — (co)ends as quantifiers" } ;
    anchor_vdcr_l4 = { id = "vdcr-l4" ; title = "Ł4 — the boundary theorem" } ;
    anchor_vdcr_overview = { id = "vdcr-overview" ; title = "Overview and decisions" } ;
    anchor_vdcr_query = { id = "vdcr-query" ; title = "What the face buys: the query surface (F6)" } ;
    anchor_vdcr_theorem = { id = "vdcr-theorem" ; title = "The theorem shape (F6.3) and the division of labor" } ;
}
