//! **The atom-occurrence flow projection** — a *prototype* certificate-side
//! identity discipline that sits **beside** replay-equivalence and the tracelet
//! normal form, and is consumed by nothing.
//!
//! # Status: prototype, and deliberately inert
//!
//! Nothing in this crate or downstream calls into this module.
//! [`gandr_theory_coherent_resolutions::tracelet::replay_equivalent`] remains
//! the identity criterion and [`crate::normal_form::nf_equal`] remains the
//! decidable fast path. This module exists to **measure** one question: whether
//! tracking cell and atom occurrences across a recorded leg — and forgetting
//! the formula-level arrangement — yields a relation that coincides with
//! certificate identity. It answers by disagreeing with both neighbours on
//! recorded fixtures, and the disagreements are the deliverable; see the
//! differential suite (`flow::tests` in the crate's integration target).
//!
//! # The construction being instantiated
//!
//! The source object is the **atomic flow** of A. Guglielmi and T. Gundersen,
//! "Normalisation control in deep inference via atomic flows", Logical Methods
//! in Computer Science 4(1:9) 2008, DOI `10.2168/LMCS-4(1:9)2008`, Definition
//! 3.2: a tuple `(V, E, η, up, lo)` where `V` is a finite vertex set, `E` a
//! finite edge set, `η` labels each vertex with the structural rule instance it
//! stands for, and `up`/`lo` map each edge to a vertex or to one of two special
//! vertices `⊤` and `⊥` — `⊤` "creates all the atom occurrences in the premiss"
//! and `⊥` "destroys all atom occurrences in the conclusion". Edges are atom
//! occurrences; the logical structure of the formulas is discarded; and
//! **linear rules introduce no vertices**, because they neither create nor
//! destroy atoms.
//!
//! The instantiation for gandr replaces two components and keeps the rest:
//!
//! - `V` is the **cell-application events** of one recorded leg, in place of
//!   the six structural rule instances of the source system.
//! - `η` labels a vertex with the firing cell's **position-free content
//!   address** ([`cell_address`]), in place of the six rule labels. The
//!   position is deliberately absent: [`crate::normal_form::prim_address`]
//!   digests the position as well as the content, and a flow that labelled its
//!   vertices with primitive addresses would re-import exactly the arrangement
//!   the projection is defined to forget.
//! - `E`, `up`, `lo`, `⊤` and `⊥` are the source's, verbatim: an edge is one
//!   atom occurrence's thread, `⊤` creates the peak's occurrences, and `⊥`
//!   destroys the occurrences surviving to the leg's end.
//!
//! **The load-bearing consequence is that [`Flow`] carries no alphabet
//! parameter.** Once the arrangement is discarded there is nothing
//! alphabet-shaped left: a flow is combinatorial data, and only
//! [`project_flow`] is generic. That is the shape the source's Definition 3.2
//! has and the shape the recorded certificate data does not, and it is the
//! sharpest available evidence that the projection is the right object rather
//! than a re-encoding of what was already there.
//!
//! **The source is this one and not the BV reading, and the difference is
//! structural rather than a matter of preference.** M. Acclavio, L.
//! Straßburger and V. Zamdzhiev, "Proof Identity and Categorical Models of BV",
//! FSCD 2026, DOI `10.4230/LIPIcs.FSCD.2026.22`, also defines atomic flows —
//! but for BV, whose rules are linear in atoms apart from the atomic identity
//! and atomic cut, so its flows are *generated by* the identity wire, the
//! crossing, the cup and the cap (their Definition 5) and carry no boxes at
//! all. A gandr cell consumes a whole left-hand skeleton and produces a whole
//! right-hand one, at arities the cell chooses, so its flow needs a labelled
//! vertex of arbitrary arity — which is Definition 3.2's shape and not
//! Definition 5's. The practical consequence is stated under the caveats on
//! this crate's design record: **there is nothing in a gandr flow to yank**, so
//! the BV correspondence between cut elimination and yanking has no counterpart
//! here to transfer or to fail.
//!
//! **What is imported is the projection's *shape*; the *control* theory is not
//! imported and is not claimed.** Definition 3.2 supplies the object — a
//! labelled vertex set, atom-occurrence edges, and two boundary vertices — and
//! that is the whole of what this module takes from the source. The source
//! line's normalisation control (streamlining, the splitting measures, and the
//! flow rewriting that drives them) is stated for classical deep-inference
//! systems, and the intuitionistic presentation's own cut elimination is
//! established indirectly, by simulation in sequent and hypersequent systems,
//! rather than internally. So no control result reaches gandr's setting by
//! citation, and none is used here: this module defines a relation and decides
//! it, and every soundness argument it rests on — the convexity fence above,
//! the strict projection's safety, the boundary conjunct below — is gandr's
//! own and is discharged in this tree.
//!
//! One boundary convention does diverge from the source, deliberately. The
//! source's flows forget the premiss and the conclusion outright; this
//! projection **anchors `⊤`** — a peak occurrence's thread carries which
//! occurrence of the peak it is — because the relation being measured compares
//! two legs *of one peak*, and an unanchored comparison would identify legs
//! that consume different parts of it.
//!
//! # What an atom occurrence is here, and the resolution ceiling
//!
//! An atom occurrence is an address in the alphabet's own vocabulary —
//! an entry of [`CellAlphabet::command_positions`]. The projection is
//! therefore exactly as fine as that vocabulary and no finer, which is the same
//! ceiling [`crate::footprint`] documents for the same reason: over
//! [`gandr_theory_cell_complexes::sequent::SequentAlphabet`] a command pattern
//! is one cut whose children are a producer and a consumer, so a term has
//! exactly one address and every leg over it projects to a flow whose every
//! thread runs from `⊤` to `⊥` through one vertex. The differential suite
//! therefore runs on the toy alphabet, the one alphabet in the tree whose terms
//! nest commands.
//!
//! # The strict projection, and the residual map it does not need
//!
//! What is built here is the **strict** projection: a step consumes every
//! occurrence its match image covers and creates every occurrence the image
//! covers afterwards, with occurrences outside the image threading through
//! untouched at unchanged addresses. Nothing inside a redex is traced from one
//! side of the step to the other.
//!
//! That is a real restriction and it is the one place this module stops short
//! of the definition it instantiates. The **lax** projection would additionally
//! carry a redex's hole contents across the step — the rule's own metavariable
//! at its left-hand address maps to the same metavariable at its right-hand
//! address, so the occurrences beneath it are transported rather than destroyed
//! and re-created. Computing that needs a **residual map on positions**, which
//! is precisely the debt [`crate::footprint`] names as owed and which
//! [`gandr_theory_coherent_resolutions::rewrite::CellApp`] has no room for. The
//! strict projection is sound without it — refusing to identify two occurrences
//! is always the safe direction — and it is exact on the permutation-tile
//! class, where the two images are disjoint and nothing needs transporting. It
//! is *coarser than the definition* only outside that class.
//!
//! # The soundness fence, which the projection inherits rather than escapes
//!
//! **Convexity is formula-level arrangement, so a flow cannot see it.** The
//! shift guard's third conjunct exists because disjointness of supports does
//! not imply independence once matches must be convex: applying one rule can
//! create a directed path that destroys another's convexity, on hyperedge sets
//! that never met. A flow has discarded exactly the structure that path lives
//! in. The projection is therefore sound on precisely the fence
//! [`ConvexityDischarge::LeftConnectedOverAcyclicTarget`] already names, every
//! [`Flow`] carries the discharge it was taken under, and an alphabet
//! answering [`ConvexityDischarge::ReCheckRequired`] must be refused the
//! identification rather than have the question re-derived here.
//!
//! # Where this sits between its two neighbours
//!
//! Measured on the fixtures in the differential suite, the three relations on
//! certificate data are strictly nested:
//!
//! - **Shift equivalence** (what [`crate::normal_form`] decides) is strictly
//!   inside flow equality. The shift guard refuses a pair whose *cells* overlap
//!   even at incomparable positions, because it asks
//!   [`gandr_theory_coherent_resolutions::overlap::overlaps_between`], which is
//!   a question about the alphabet. The projection reads the *instance*, where
//!   two disjoint images share no occurrence whatever the cells could have done
//!   elsewhere, so it licenses that pair.
//! - **Flow equality** is strictly inside replay-equivalence.
//!   [`gandr_theory_coherent_resolutions::tracelet::replay_equivalent`]
//!   compares a boundary and asks each side to replay, ignoring the recorded
//!   paths outright, so no relation that reads the paths can coincide with it.
//!   [`gandr_theory_coherent_resolutions::tracelet::derive_fused`] exhibits the
//!   gap in the tree: one boundary whose `path_a` is a two-step derivation and
//!   whose `path_b` is a single fused step — replay-equal by construction, and
//!   flow-distinct because the vertex label multisets differ.
//!
//! So a flow is **strictly finer than certificate identity**, and reading
//! "equal flows" as "same certificate" is wrong in the direction that does not
//! announce itself. What flow equality does decide, on the permutation-tile
//! class, is the *shift* identification — which is the quotient
//! [`crate::shift::derive_shift_equivalence`] currently pays two term rewrites
//! per pair to confirm.
//!
//! # The nesting is a claim about **certificates**, and it costs the boundary
//!
//! The second containment above is a statement about a relation on
//! certificates, and it holds only for a certificate-level relation that
//! compares certificates — boundaries included. A relation reading the two
//! projected flows and nothing else is **not** inside replay-equivalence: one
//! metavariable-carrying cell fired on two unrelated ground instances produces
//! two legs with the same flow over two different boundaries, which
//! replay-equivalence separates and a flow-only comparison does not. The
//! chain's second strictness was published in that broken form and is
//! corrected here rather than quietly narrowed;
//! `flow::tests::equal_flows_over_different_boundaries_are_not_one_certificate`
//! is the regression that fails if the boundary conjunct is dropped again.
//!
//! The remedy is the one [`crate::normal_form::TraceletNf`] already took:
//! **the certificate-level datum carries the boundary**, so
//! [`TraceletFlow`] holds a peak and a join beside the two flows and
//! [`tracelet_flow`] refuses a leg that lands anywhere else. Containment is
//! then a consequence of what the datum **is** rather than a property of how
//! it happens to be compared, and it survives any later change to the flow
//! comparison itself.
//!
//! **The no-alphabet-parameter result above survives this intact, and a reader
//! who meets a boundary here should not conclude otherwise.** [`Flow`] is
//! untouched and still carries no alphabet parameter; the parameter the
//! boundary brings sits one level up, on [`TraceletFlow`]. Forgetting the
//! formula-level arrangement is the projection's content, forgetting the
//! endpoints never was, and conflating the two is exactly what produced the
//! defect.
//!
//! # One discipline, in two places: refuse where a choice would be arbitrary
//!
//! This module declines to answer twice, for one reason, and the repetition is
//! what makes it a discipline rather than two local decisions.
//!
//! - [`Flow::canonical`] gives **no** canonical form to a flow whose vertices
//!   share a re-indexing key, rather than ordering them arbitrarily.
//! - The convexity fence gives **no** identification on a carrier answering
//!   [`ConvexityDischarge::ReCheckRequired`], rather than re-deriving the
//!   question with the structure that would settle it already discarded.
//!
//! **The rule both follow: an identification not made is always sound, and one
//! made wrongly is not.** So a negative from this layer means "not identified
//! here" and never "distinct", and a third refusal met later reads the same
//! way.
//!
//! It is also why a hazard the source line carries does not reach these
//! relations. Cycle removal in that literature is **non-confluent** — the
//! transformation has no canonical result — so an identity defined by
//! quotienting under it inherits a choice of representative. None of the
//! relations here is defined that way: each is an explicit predicate on
//! recorded data, and at the one place a representative choice would have been
//! needed, the canonical form's ties, this module declines to make one.
//!
//! # Cost
//!
//! Deliberately unoptimized: one rewrite per recorded step, plus a linear scan
//! of the term's addresses per step and a quadratic address lookup inside it.
//! It is a measurement instrument, not a fast path.
//!
//! [`CellAlphabet::command_positions`]: gandr_theory_cell_complexes::alphabet::CellAlphabet::command_positions
//! [`ConvexityDischarge::LeftConnectedOverAcyclicTarget`]: gandr_theory_cell_complexes::alphabet::ConvexityDischarge::LeftConnectedOverAcyclicTarget
//! [`ConvexityDischarge::ReCheckRequired`]: gandr_theory_cell_complexes::alphabet::ConvexityDischarge::ReCheckRequired

use alloc::boxed::Box;
use alloc::vec::Vec;

use gandr_theory_cell_complexes::alphabet::CellAlphabet;
use gandr_theory_cell_complexes::alphabet::ConvexityDischarge;
use gandr_theory_cell_complexes::alphabet::PositionOrder;
use gandr_theory_cell_complexes::boundary::FlowEquality;
use gandr_theory_cell_complexes::boundary::FlowPortIndex;
use gandr_theory_cell_complexes::boundary::FlowVertexIndex;
use gandr_theory_cell_complexes::boundary::PeakOccurrenceIndex;
use gandr_theory_cell_complexes::cell::CellId;
use gandr_theory_cell_complexes::cell::CellStore;
use gandr_theory_cell_complexes::sequent::SequentAlphabet;
use gandr_theory_coherent_resolutions::rewrite::CellApp;
use gandr_theory_coherent_resolutions::rewrite::rewrite_at;
use gandr_theory_coherent_resolutions::tracelet::Tracelet;

use crate::normal_form::CellAddress;
use crate::normal_form::cell_address;

/// One end of an atom-occurrence thread — a vertex of the flow, or one of the
/// two special vertices.
///
/// The variant order is the comparison order the canonical form sorts on, and
/// it is chosen to read top-down: the premiss boundary, then the body, then the
/// conclusion boundary.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub enum FlowEnd
{
    /// The special vertex that creates every atom occurrence of the peak,
    /// carrying which occurrence of the peak this thread starts at.
    Peak
    {
        /// The occurrence's index in the peak's enumerated addresses.
        occurrence: PeakOccurrenceIndex,
    },
    /// A cell-application event, at one of its upper or lower ports.
    Vertex
    {
        /// Which event.
        vertex: FlowVertexIndex,
        /// Which incidence of that event, in the term's address order.
        port: FlowPortIndex,
    },
    /// The special vertex that destroys every atom occurrence surviving to the
    /// end of the leg.
    Join,
}

/// One **atom-occurrence thread** — an edge of the flow, with the source's
/// `up` and `lo` maps read off it.
#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
pub struct FlowThread
{
    /// Where the occurrence is created.
    pub up: FlowEnd,
    /// Where the occurrence is destroyed.
    pub lo: FlowEnd,
}

/// The **atom-occurrence flow** of one recorded leg.
///
/// Carries no alphabet parameter, which is the projection's whole content: once
/// the formula-level arrangement is discarded there is nothing alphabet-shaped
/// left in it.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct Flow
{
    /// `η` — one content address per cell-application event, indexed by
    /// [`FlowEnd::Vertex`]'s `vertex` field.
    pub labels: Vec<CellAddress>,
    /// `E` with its `up` and `lo` maps.
    pub threads: Vec<FlowThread>,
    /// The warrant the projection's soundness fence was discharged under,
    /// carried rather than recomputed.
    pub convexity: ConvexityDischarge,
}

/// The flow of a **certificate** — its boundary, and its two legs' flows.
///
/// The boundary is carried for the same reason
/// [`crate::normal_form::TraceletNf`] carries its own: a certificate is a
/// boundary together with derivations of it, so a datum standing for one
/// without its endpoints stands for less than a certificate. A [`Flow`]
/// forgets the **formula-level arrangement**, which is the projection's whole
/// content; forgetting the arrangement is not forgetting the endpoints, and a
/// certificate-level relation that dropped them would identify two
/// certificates that transform different things the same way.
///
/// The alphabet parameter sits **here** and not on [`Flow`]. That placement is
/// the point: the combinatorial datum stays alphabet-free, and only the
/// boundary it is a flow *of* is alphabet-shaped.
#[derive(Clone, Debug, Eq, PartialEq)]
pub struct TraceletFlow<A: CellAlphabet = SequentAlphabet>
{
    /// The term both legs are derivations from, as recorded (schematic; the
    /// projection skolemizes it).
    pub peak: A::Cmd,
    /// The term both legs reach, as recorded (schematic).
    pub joins_at: A::Cmd,
    /// The first leg's flow.
    pub path_a: Flow,
    /// The second leg's flow.
    pub path_b: Flow,
}

/// Why a recorded leg could not be projected to a flow.
///
/// Refusal is data, never a panic and never a silent identity: a recorded step
/// list that is not a derivation of the peak has no flow.
#[derive(Clone, Debug, Eq, PartialEq)]
pub enum FlowObstruction<A: CellAlphabet = SequentAlphabet>
{
    /// A recorded step names a cell the store does not hold.
    UnknownCell
    {
        /// The identifier that resolved to nothing.
        cell: CellId,
    },
    /// A recorded step does not fire at its recorded position, so the leg is
    /// not a derivation and there is nothing to project.
    StepDoesNotFire
    {
        /// The step that failed to fire.
        step: Box<CellApp<A>>,
    },
    /// Every recorded step fired, and the leg landed somewhere other than the
    /// certificate's recorded join — so the leg is a derivation, but not a
    /// derivation of **this** boundary.
    ///
    /// Only [`tracelet_flow`] raises it, because only a certificate has a join
    /// to miss; [`project_flow`] is given a peak and a path and has nothing to
    /// compare against.
    LegMissesTheJoin
    {
        /// The skolemized term the leg actually reached.
        reached: Box<A::Cmd>,
    },
}

/// An atom occurrence still alive at some point in the walk.
#[derive(Clone, Debug)]
struct LiveAtom<A: CellAlphabet>
{
    /// Where the occurrence was created.
    birth: FlowEnd,
    /// The address it currently sits at.
    at: A::Pos,
}

impl Flow
{
    /// The **canonical form** — the same flow with its vertices re-indexed by a
    /// key that does not depend on the order the leg recorded them in.
    ///
    /// The key is the causal depth, then the label, then the sorted peak
    /// occurrences the vertex consumes, then its two incidence counts. Two
    /// vertices sharing a key cannot be told apart by it, and the flow is
    /// **refused** a canonical form rather than given an arbitrary one.
    ///
    /// # Contract
    /// - ensures: `Some(flow)` whose `labels` are the input's re-indexed by the
    ///   key order and whose `threads` are the input's rewritten to the new
    ///   indices and sorted; the convexity discharge is carried through
    ///   unchanged.
    /// - ensures: two flows that differ only by the order their legs recorded
    ///   independent events in have equal canonical forms.
    /// - provides: the comparison normal form [`flows_equal`] decides on.
    /// - fails: `None` when two vertices share a key, so no canonical order is
    ///   determined. Refusing is the conservative direction: an identification
    ///   not made is always sound.
    /// - panics: none.
    /// - intension: one forward pass for the depths — the recorded order is
    ///   already topological, because an occurrence is created before it is
    ///   consumed — then one stable sort of the vertices and one of the
    ///   threads.
    ///
    /// # Adequacy
    /// - hypothesis: L2 — the two outcomes own separate decision surfaces,
    ///   separated by the permutation tile (whose two legs record the same two
    ///   events in opposite orders and must canonicalize together) and by a
    ///   flow whose two vertices carry one label, one depth, and no peak
    ///   incidence, which must be refused rather than ordered.
    /// - witness: `flow::tests::the_two_legs_of_a_permutation_tile_have_one_flow`
    /// - witness: `flow::tests::indistinguishable_vertices_are_refused_a_canonical_order`
    #[inline]
    #[must_use]
    pub fn canonical(&self) -> Option<Self>
    {
        let depths = self.causal_depths();
        let mut keys: Vec<(VertexKey, FlowVertexIndex)> = Vec::with_capacity(self.labels.len());
        for (index, label) in self.labels.iter().enumerate() {
            let vertex = FlowVertexIndex::from(index);
            let depth = depths.get(index).copied().unwrap_or_default();
            keys.push((self.vertex_key(vertex, *label, depth), vertex));
        }
        keys.sort_by(|left, right| left.0.cmp(&right.0));
        if keys
            .iter()
            .zip(keys.iter().skip(1_usize))
            .any(|(left, right)| left.0 == right.0)
        {
            return None;
        }
        // `rank[old] = new`, built by walking the sorted keys.
        let mut rank: Vec<FlowVertexIndex> = alloc::vec![FlowVertexIndex::default(); keys.len()];
        let mut labels = Vec::with_capacity(keys.len());
        for (fresh, entry) in keys.iter().enumerate() {
            let old = usize::from(entry.1);
            if let Some(slot) = rank.get_mut(old) {
                *slot = FlowVertexIndex::from(fresh);
            }
            labels.push(self.labels.get(old).copied().unwrap_or(entry.0.label));
        }
        let mut threads: Vec<FlowThread> = self
            .threads
            .iter()
            .map(|thread| FlowThread {
                up: reindex_end(thread.up, &rank),
                lo: reindex_end(thread.lo, &rank),
            })
            .collect();
        threads.sort_unstable();
        Some(Self {
            labels,
            threads,
            convexity: self.convexity,
        })
    }

    /// The causal layering — each vertex's depth in the dependence order the
    /// threads induce.
    ///
    /// # Contract
    /// - requires: every `Vertex` end's index is in range for `labels`, which
    ///   [`project_flow`] establishes.
    /// - ensures: one entry per vertex; zero for a vertex consuming no
    ///   occurrence any other vertex created, and otherwise one more than the
    ///   greatest depth among those creators.
    /// - panics: none.
    #[inline]
    fn causal_depths(&self) -> Vec<CausalLayer>
    {
        let mut depths: Vec<CausalLayer> = alloc::vec![CausalLayer::default(); self.labels.len()];
        // The recorded order is topological: a thread runs from the event that
        // created an occurrence to the event that consumed it, and creation
        // precedes consumption in the leg.
        for thread in &self.threads {
            let (FlowEnd::Vertex { vertex: up, .. }, FlowEnd::Vertex { vertex: lo, .. }) =
                (thread.up, thread.lo)
            else {
                continue;
            };
            let source = depths.get(usize::from(up)).copied().unwrap_or_default();
            let lifted = CausalLayer::from(usize::from(source).saturating_add(1_usize));
            if let Some(slot) = depths.get_mut(usize::from(lo))
                && *slot < lifted
            {
                *slot = lifted;
            }
        }
        depths
    }

    /// The sort key of one vertex.
    ///
    /// # Contract
    /// - ensures: a key built only from data invariant under re-ordering
    ///   independent events — the depth, the label, the peak occurrences
    ///   consumed, and the two incidence counts.
    /// - panics: none.
    #[inline]
    fn vertex_key(
        &self,
        vertex: FlowVertexIndex,
        label: CellAddress,
        depth: CausalLayer,
    ) -> VertexKey
    {
        let mut from_peak: Vec<PeakOccurrenceIndex> = Vec::new();
        let mut upper = IncidenceCount::default();
        let mut lower = IncidenceCount::default();
        for thread in &self.threads {
            if matches!(thread.lo, FlowEnd::Vertex { vertex: at, .. } if at == vertex) {
                upper = IncidenceCount::from(usize::from(upper).saturating_add(1_usize));
                if let FlowEnd::Peak { occurrence } = thread.up {
                    from_peak.push(occurrence);
                }
            }
            if matches!(thread.up, FlowEnd::Vertex { vertex: at, .. } if at == vertex) {
                lower = IncidenceCount::from(usize::from(lower).saturating_add(1_usize));
            }
        }
        from_peak.sort_unstable();
        VertexKey {
            depth,
            label,
            from_peak,
            upper,
            lower,
        }
    }
}

/// The layer a cell-application event sits in, in the dependence order its
/// atom-occurrence threads induce.
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct CausalLayer(usize);

impl From<usize> for CausalLayer
{
    #[inline]
    fn from(value: usize) -> Self
    {
        Self(value)
    }
}

impl From<CausalLayer> for usize
{
    #[inline]
    fn from(value: CausalLayer) -> Self
    {
        value.0
    }
}

/// The number of upper or lower incidences one flow vertex carries.
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct IncidenceCount(usize);

impl From<usize> for IncidenceCount
{
    #[inline]
    fn from(value: usize) -> Self
    {
        Self(value)
    }
}

impl From<IncidenceCount> for usize
{
    #[inline]
    fn from(value: IncidenceCount) -> Self
    {
        value.0
    }
}

/// The re-indexing key of one flow vertex.
#[derive(Clone, Debug, Eq, Ord, PartialEq, PartialOrd)]
struct VertexKey
{
    /// The causal layer, compared first.
    depth: CausalLayer,
    /// The cell content address.
    label: CellAddress,
    /// The peak occurrences this vertex consumes, sorted.
    from_peak: Vec<PeakOccurrenceIndex>,
    /// How many occurrences it consumes.
    upper: IncidenceCount,
    /// How many it creates.
    lower: IncidenceCount,
}

/// Rewrite one thread end through a vertex re-indexing.
///
/// # Contract
/// - ensures: `Peak` and `Join` ends unchanged; a `Vertex` end re-indexed
///   through `rank`, or left alone when the index is out of range, which
///   [`project_flow`]'s output never produces.
/// - panics: none.
#[inline]
fn reindex_end(
    end: FlowEnd,
    rank: &[FlowVertexIndex],
) -> FlowEnd
{
    match end {
        | FlowEnd::Vertex { vertex, port } => {
            let Some(fresh) = rank.get(usize::from(vertex))
            else {
                return end;
            };
            FlowEnd::Vertex {
                vertex: *fresh,
                port,
            }
        },
        | other => other,
    }
}

/// The index of `at` among `positions`.
///
/// # Contract
/// - requires: `positions` is a term's complete address enumeration, so an
///   address of that term is present exactly once.
/// - ensures: `Some(index)` at the address's place in the enumeration, `None`
///   for an address the term does not carry.
/// - panics: none.
#[inline]
fn address_index<A>(
    positions: &[A::Pos],
    at: &A::Pos,
) -> Option<FlowPortIndex>
where
    A: CellAlphabet,
{
    let found = positions.iter().position(|candidate| candidate == at)?;
    Some(FlowPortIndex::from(found))
}

/// Whether one address lies inside a step's match image.
#[repr(transparent)]
#[derive(Clone, Copy, Debug, Default, Eq, Hash, Ord, PartialEq, PartialOrd)]
struct ImageCoverage(bool);

impl From<bool> for ImageCoverage
{
    #[inline]
    fn from(value: bool) -> Self
    {
        Self(value)
    }
}

impl From<ImageCoverage> for bool
{
    #[inline]
    fn from(value: ImageCoverage) -> Self
    {
        value.0
    }
}

/// Whether `at` covers `position` — the match image test.
///
/// # Contract
/// - ensures: positive for the redex root and every address it encloses,
///   negative for an ancestor and for an incomparable address.
/// - panics: none.
#[inline]
fn covered_by<A>(
    at: &A::Pos,
    position: &A::Pos,
) -> ImageCoverage
where
    A: CellAlphabet,
{
    ImageCoverage::from(matches!(
        A::position_order(at, position),
        PositionOrder::Same | PositionOrder::Encloses
    ))
}

/// **Project** a recorded leg to its atom-occurrence flow, or refuse it.
///
/// The peak is skolemized first, under the same discipline replay uses
/// ([`CellAlphabet::skolemize`]), so the projection is taken over the ground
/// derivation rather than the schematic one. Each recorded step is then **run**
/// rather than reasoned about: a step that does not fire has no transition to
/// attach a vertex to, and the leg is refused.
///
/// # Contract
/// - requires: `path` is the leg recorded from `peak` against `store` — the
///   same pair [`Tracelet::replay`] would be given one half of.
/// - ensures: `Ok(flow)` whose `labels` are the firing cells' position-free
///   content addresses in recorded order; whose `threads` carry one edge per
///   atom occurrence, running from the peak or from the event that created it
///   to the event that consumed it or to the conclusion; and which carries the
///   alphabet's convexity discharge for `store`.
/// - ensures: every occurrence the step's match image covers is consumed, every
///   occurrence the image covers afterwards is created, and every occurrence
///   outside the image threads through at an unchanged address — the strict
///   projection the module documents.
/// - provides: the alphabet-independent combinatorial datum flow equality is
///   decided on.
/// - fails: [`FlowObstruction`] — an unresolvable cell identifier, or a step
///   that does not fire at its recorded position.
/// - panics: none.
/// - intension: one rewrite per recorded step and two address enumerations per
///   step. A vertex's ports are numbered **inside its match image**, so one
///   step's port numbering never depends on what another step did elsewhere in
///   the term; `⊤`'s edges come out in the peak's enumeration order and `⊥`'s
///   in the conclusion's, which is the source's own boundary ordering.
///
/// # Errors
/// See the `- fails:` clause above.
///
/// # Adequacy
/// - hypothesis: L2 — the projection's three occurrence classes own separate
///   decision surfaces, separated by a leg whose single step consumes the whole
///   term (every thread runs peak-to-vertex and vertex-to-join), by a leg whose
///   two steps fire at incomparable positions (each thread touches exactly one
///   vertex, and the untouched sibling threads peak-to-join), and by a leg
///   whose second step consumes what the first created (one thread runs
///   vertex-to-vertex); the two refusals are separated by an unstored
///   identifier and a non-firing step.
/// - witness: `flow::tests::a_single_step_leg_threads_the_whole_term_through_one_vertex`
/// - witness: `flow::tests::disjoint_steps_share_no_thread`
/// - witness: `flow::tests::a_consumed_creation_is_one_thread_between_two_vertices`
/// - witness: `flow::tests::a_leg_that_does_not_fire_has_no_flow`
///
/// [`CellAlphabet::skolemize`]: gandr_theory_cell_complexes::alphabet::CellAlphabet::skolemize
/// [`Tracelet::replay`]: gandr_theory_coherent_resolutions::tracelet::Tracelet::replay
#[inline]
pub fn project_flow<A>(
    store: &CellStore<A>,
    peak: &A::Cmd,
    path: &[CellApp<A>],
) -> Result<Flow, FlowObstruction<A>>
where
    A: CellAlphabet,
{
    project_walk(store, peak, path).map(|(flow, _reached)| flow)
}

/// [`project_flow`], keeping the term the leg reached.
///
/// The reached term is what [`tracelet_flow`] checks the recorded join
/// against; [`project_flow`] itself has nothing to compare it with and drops
/// it.
///
/// # Contract
/// - ensures: [`project_flow`]'s flow, paired with the skolemized term the last
///   recorded step produced (the skolemized peak, for an empty path).
/// - panics: none.
#[inline]
fn project_walk<A>(
    store: &CellStore<A>,
    peak: &A::Cmd,
    path: &[CellApp<A>],
) -> Result<(Flow, A::Cmd), FlowObstruction<A>>
where
    A: CellAlphabet,
{
    let mut current = A::skolemize(peak);
    let mut live: Vec<LiveAtom<A>> = A::command_positions(&current)
        .into_iter()
        .enumerate()
        .map(|(index, at)| LiveAtom {
            birth: FlowEnd::Peak {
                occurrence: PeakOccurrenceIndex::from(index),
            },
            at,
        })
        .collect();
    let mut labels: Vec<CellAddress> = Vec::with_capacity(path.len());
    let mut threads: Vec<FlowThread> = Vec::new();
    for (index, step) in path.iter().enumerate() {
        let Some(cell) = store.get(step.cell)
        else {
            return Err(FlowObstruction::UnknownCell { cell: step.cell });
        };
        let Some(next) = rewrite_at(cell, &current, &step.at)
        else {
            return Err(FlowObstruction::StepDoesNotFire {
                step: Box::new(step.clone()),
            });
        };
        let vertex = FlowVertexIndex::from(index);
        labels.push(cell_address(cell));
        // Ports are numbered inside the match image, never across the whole
        // term: a vertex's incidences are its own, as the source's are the
        // rule instance's, and a global numbering would make one step's ports
        // depend on what another step did elsewhere in the term.
        let before_covered: Vec<A::Pos> = A::command_positions(&current)
            .into_iter()
            .filter(|position| bool::from(covered_by::<A>(&step.at, position)))
            .collect();
        let after_covered: Vec<A::Pos> = A::command_positions(&next)
            .into_iter()
            .filter(|position| bool::from(covered_by::<A>(&step.at, position)))
            .collect();
        // Upper edges: everything the match image covers is consumed.
        let mut surviving: Vec<LiveAtom<A>> = Vec::with_capacity(live.len());
        for atom in live {
            if !bool::from(covered_by::<A>(&step.at, &atom.at)) {
                surviving.push(atom);
                continue;
            }
            let port = address_index::<A>(&before_covered, &atom.at).unwrap_or_default();
            threads.push(FlowThread {
                up: atom.birth,
                lo: FlowEnd::Vertex { vertex, port },
            });
        }
        live = surviving;
        // Lower edges: everything the image covers afterwards is created.
        for (port, at) in after_covered.into_iter().enumerate() {
            live.push(LiveAtom {
                birth: FlowEnd::Vertex {
                    vertex,
                    port: FlowPortIndex::from(port),
                },
                at,
            });
        }
        current = next;
    }
    // The conclusion's own enumeration orders `⊥`'s edges, as the source's does.
    let final_positions = A::command_positions(&current);
    live.sort_by_key(|atom| address_index::<A>(&final_positions, &atom.at).unwrap_or_default());
    for atom in live {
        threads.push(FlowThread {
            up: atom.birth,
            lo: FlowEnd::Join,
        });
    }
    Ok((
        Flow {
            labels,
            threads,
            convexity: A::convexity_discharge(store),
        },
        current,
    ))
}

/// Whether two flows are **the same flow**.
///
/// # Contract
/// - requires: both flows were projected by [`project_flow`], so their vertex
///   indices are in range and their boundaries are anchored in the same
///   vocabulary.
/// - ensures: positive iff both flows admit a canonical form, the two canonical
///   forms are equal, and both were taken under the same convexity discharge.
/// - provides: the identification the projection licenses.
/// - panics: none.
/// - intension: **the positive answer is the load-bearing one.** A flow with no
///   canonical order answers negatively rather than refusing, because an
///   identification not made is always sound and one made wrongly is not; a
///   negative therefore means "not identified here", never "distinct".
///
/// # Adequacy
/// - hypothesis: L2 — the positive and negative surfaces are separated by the
///   permutation tile, whose two legs record the same events in opposite orders
///   and are identified, and by the fused certificate, whose two legs carry
///   different label multisets and are not.
/// - witness: `flow::tests::the_two_legs_of_a_permutation_tile_have_one_flow`
/// - witness: `flow::tests::flow_equality_is_strictly_finer_than_replay_equivalence`
#[inline]
#[must_use]
pub fn flows_equal(
    left: &Flow,
    right: &Flow,
) -> FlowEquality
{
    if left.convexity != right.convexity {
        return FlowEquality::from(false);
    }
    let (Some(left), Some(right)) = (left.canonical(), right.canonical())
    else {
        return FlowEquality::from(false);
    };
    FlowEquality::from(left == right)
}

/// Project a **certificate** to its boundary and its two legs' flows.
///
/// Both legs are projected from the shared peak and each is required to reach
/// the recorded join, so a [`TraceletFlow`] exists only for a certificate that
/// **replays**. That requirement is what makes the certificate-level relation
/// below a subrelation of
/// [`gandr_theory_coherent_resolutions::tracelet::replay_equivalent`] rather
/// than merely comparable with it: replay-equivalence is equal peaks, equal
/// joins, and two successful replays, and projecting establishes the last of
/// the three while the datum carries the first two.
///
/// # Contract
/// - requires: the tracelet's paths are the legs recorded from its peak against
///   `store`.
/// - ensures: `Ok(flow)` carrying the certificate's recorded peak and join and
///   each leg's flow, and only when **both** legs fire step by step from the
///   skolemized peak and reach the skolemized join — that is, exactly when
///   [`gandr_theory_coherent_resolutions::tracelet::Tracelet::replay`] holds.
/// - provides: the certificate-level datum [`tracelets_flow_equal`] compares.
/// - fails: [`FlowObstruction`], from whichever leg is refused first —
///   including [`FlowObstruction::LegMissesTheJoin`] for a leg that fires
///   throughout and lands elsewhere.
/// - panics: none.
///
/// # Errors
/// See the `- fails:` clause above.
///
/// # Adequacy
/// - hypothesis: L2 — the reached-the-join requirement owns its own decision
///   surface, separated by a certificate that replays and one whose second leg
///   fires completely and lands short of the recorded join.
/// - witness: `flow::tests::a_certificate_has_its_own_flow`
/// - witness: `flow::tests::a_leg_that_lands_off_the_join_has_no_certificate_flow`
#[inline]
pub fn tracelet_flow<A>(
    tracelet: &Tracelet<A>,
    store: &CellStore<A>,
) -> Result<TraceletFlow<A>, FlowObstruction<A>>
where
    A: CellAlphabet,
{
    let target = A::skolemize(&tracelet.joins_at);
    let path_a = project_leg(store, &tracelet.overlap.peak, &target, &tracelet.path_a)?;
    let path_b = project_leg(store, &tracelet.overlap.peak, &target, &tracelet.path_b)?;
    Ok(TraceletFlow {
        peak: tracelet.overlap.peak.clone(),
        joins_at: tracelet.joins_at.clone(),
        path_a,
        path_b,
    })
}

/// Project one leg of a certificate, refusing it unless it reaches `target`.
///
/// # Contract
/// - requires: `target` is the skolemized recorded join.
/// - ensures: [`project_flow`]'s flow when the leg reaches `target`.
/// - fails: [`FlowObstruction::LegMissesTheJoin`] when it fires throughout and
///   lands elsewhere, or whatever [`project_flow`] refuses it for.
/// - panics: none.
#[inline]
fn project_leg<A>(
    store: &CellStore<A>,
    peak: &A::Cmd,
    target: &A::Cmd,
    path: &[CellApp<A>],
) -> Result<Flow, FlowObstruction<A>>
where
    A: CellAlphabet,
{
    let (flow, reached) = project_walk(store, peak, path)?;
    if reached == *target {
        return Ok(flow);
    }
    Err(FlowObstruction::LegMissesTheJoin {
        reached: Box::new(reached),
    })
}

/// Whether a tracelet's **two legs have one flow** — the tile-internal reading.
///
/// This is the reading that pays: on the permutation-tile class it decides the
/// shift identification, which
/// [`crate::shift::derive_shift_equivalence`] currently confirms by running
/// both sequentializations and comparing the terms they reach.
///
/// # Contract
/// - requires: the tracelet's paths are the legs recorded from its peak.
/// - ensures: positive iff both legs project and their flows are equal.
/// - provides: a syntactic witness for the shift quotient, in place of a
///   two-order replay.
/// - fails: [`FlowObstruction`] when either leg is not a derivation of the
///   peak.
/// - panics: none.
///
/// # Errors
/// See the `- fails:` clause above.
///
/// # Adequacy
/// - hypothesis: L1 evidence — the decision surface is one flow comparison,
///   separated by the permutation tile (equal) and by the fused certificate
///   (unequal, over a boundary that replays).
/// - witness: `flow::tests::the_two_legs_of_a_permutation_tile_have_one_flow`
/// - witness: `flow::tests::flow_equality_is_strictly_finer_than_replay_equivalence`
#[inline]
pub fn legs_flow_equal<A>(
    tracelet: &Tracelet<A>,
    store: &CellStore<A>,
) -> Result<FlowEquality, FlowObstruction<A>>
where
    A: CellAlphabet,
{
    let projected = tracelet_flow(tracelet, store)?;
    Ok(flows_equal(&projected.path_a, &projected.path_b))
}

/// Whether two tracelets are **the same certificate under the projection** —
/// the certificate-to-certificate reading: one boundary, and one flow per leg.
///
/// **The boundary is part of the comparison, and leaving it out was a
/// relation-soundness defect this function once had.** Comparing flows alone
/// answers positively for two certificates that transform *different* peaks
/// into *different* joins by the same combinatorial pattern — a single
/// metavariable-carrying cell fired on two unrelated ground instances is
/// enough over the sequent alphabet — so a flow-only relation is not contained
/// in [`gandr_theory_coherent_resolutions::tracelet::replay_equivalent`] and
/// the strict nesting the module claims is false for it. Forgetting the
/// formula-level **arrangement**, which is what the projection is for, is not
/// the same as forgetting the **endpoints**.
///
/// # Contract
/// - requires: both tracelets' paths are the legs recorded from their own
///   peaks, and both are read against `store`.
/// - ensures: positive iff both certificates project — which forces equal
///   recorded boundaries to be reached, so both replay — **and** their peaks
///   agree, their joins agree, and their two flows agree pairwise.
/// - ensures: a positive answer implies
///   [`gandr_theory_coherent_resolutions::tracelet::replay_equivalent`]: equal
///   peaks and equal joins are compared here, and both replays are what
///   [`tracelet_flow`] established.
/// - provides: the relation the module measures against replay-equivalence; it
///   is **strictly finer**, and a positive there does not follow from a
///   positive here.
/// - fails: [`FlowObstruction`] when either tracelet is not a pair of
///   derivations of its own recorded boundary.
/// - panics: none.
/// - intension: **the positive answer is the load-bearing one**, as at
///   [`flows_equal`]: a negative means "not identified here", never "distinct".
///
/// # Errors
/// See the `- fails:` clause above.
///
/// # Adequacy
/// - hypothesis: L2 — the boundary conjunct and the flow conjunct own separate
///   decision surfaces, separated by a certificate against itself, by two
///   replay-equivalent certificates whose legs carry different flows, and by
///   two certificates whose flows are equal over different boundaries.
/// - witness: `flow::tests::a_certificate_has_its_own_flow`
/// - witness: `flow::tests::replay_equivalent_certificates_can_carry_different_flows`
/// - witness: `flow::tests::equal_flows_over_different_boundaries_are_not_one_certificate`
/// - witness: `flow::tests::flow_equality_implies_replay_equivalence`
#[inline]
pub fn tracelets_flow_equal<A>(
    left: &Tracelet<A>,
    right: &Tracelet<A>,
    store: &CellStore<A>,
) -> Result<FlowEquality, FlowObstruction<A>>
where
    A: CellAlphabet,
{
    let left = tracelet_flow(left, store)?;
    let right = tracelet_flow(right, store)?;
    if left.peak != right.peak || left.joins_at != right.joins_at {
        return Ok(FlowEquality::from(false));
    }
    let heads = flows_equal(&left.path_a, &right.path_a);
    let tails = flows_equal(&left.path_b, &right.path_b);
    Ok(FlowEquality::from(bool::from(heads) && bool::from(tails)))
}

#[cfg(test)]
mod tests
{
    use gandr_core_sequent::il::Polarity;
    use gandr_theory_cell_complexes::cell::Cell;
    use gandr_theory_cell_complexes::pattern::CmdPat;
    use gandr_theory_cell_complexes::pattern::ConsPat;
    use gandr_theory_cell_complexes::pattern::Pos;
    use gandr_theory_cell_complexes::pattern::ProdPat;
    use gandr_theory_cell_complexes::pattern::Sym;
    use gandr_theory_cell_complexes::sequent::CellProvenance;
    use gandr_theory_cell_complexes::sequent::Orientation;
    use gandr_theory_cell_complexes::sequent::frame_defining_cell;

    use super::*;

    #[test]
    fn the_cell_address_forgets_the_position()
    {
        let frame = frame_defining_cell(&Sym::new("Succ"));
        let other = frame_defining_cell(&Sym::new("Pred"));
        assert_eq!(
            cell_address(&frame),
            cell_address(&frame),
            "one cell's address is a function of its content"
        );
        assert_ne!(
            cell_address(&frame),
            cell_address(&other),
            "two cells with different content have different addresses"
        );
        // The two addresses are domain-separated, and since the correction
        // that separation is **nominal**: a `CellAddress` and a `PrimId` are
        // different types, so this assertion cannot be written here at all and
        // the confusion it guarded against is now a compile error.
        // `normal_form::tests::the_two_address_domains_are_separated_by_type_and_by_digest`
        // carries what remains assertable, where the digests are visible.
    }

    #[test]
    fn the_sequent_alphabet_gives_the_projection_one_occurrence_to_work_with()
    {
        // The projection is only as fine as the alphabet's address vocabulary.
        // A sequent command pattern has exactly one command position, so the
        // whole term is one atom occurrence and every leg over it projects to a
        // chain through one thread per step. This is the ceiling `footprint`
        // documents, for the same reason, and it is why the differential suite
        // runs on the toy alphabet.
        let mut store = CellStore::new();
        let frame = store.insert(frame_defining_cell(&Sym::new("Succ")));
        let term = CmdPat::cut(
            Polarity::Positive,
            ProdPat::ctor("Zero", []),
            ConsPat::frame("Succ", ConsPat::Top),
        );
        let flow = project_flow(&store, &term, &[CellApp {
            cell: frame,
            at: Pos::root(),
        }])
        .expect("the frame-defining cell fires at the root");
        assert_eq!(1, flow.labels.len(), "one cell application, one vertex");
        assert_eq!(
            2,
            flow.threads.len(),
            "one occurrence consumed from the peak, one created and reaching the join"
        );
    }

    #[test]
    fn a_leg_that_does_not_fire_has_no_flow()
    {
        let mut store = CellStore::new();
        let frame = store.insert(frame_defining_cell(&Sym::new("Succ")));
        let term = CmdPat::cut(Polarity::Positive, ProdPat::ctor("Zero", []), ConsPat::Top);
        let step = CellApp {
            cell: frame,
            at: Pos::root(),
        };
        assert_eq!(
            Err(FlowObstruction::StepDoesNotFire {
                step: Box::new(step.clone()),
            }),
            project_flow(&store, &term, &[step]),
            "a leg is a derivation or it is nothing"
        );
        let missing = CellId(97);
        assert_eq!(
            Err(FlowObstruction::UnknownCell { cell: missing }),
            project_flow(&store, &term, &[CellApp {
                cell: missing,
                at: Pos::root(),
            }]),
            "and an unresolvable identifier is refused before the term is read"
        );
    }

    #[test]
    fn indistinguishable_vertices_are_refused_a_canonical_order()
    {
        // Two vertices at one depth, under one label, consuming nothing from
        // the peak: the key cannot tell them apart, so no canonical order is
        // determined and the flow is refused one rather than given an arbitrary
        // one.
        let label = cell_address(&frame_defining_cell(&Sym::new("Succ")));
        let flow = Flow {
            labels: alloc::vec![label, label],
            threads: alloc::vec![
                FlowThread {
                    up: FlowEnd::Vertex {
                        vertex: FlowVertexIndex::from(0_usize),
                        port: FlowPortIndex::default(),
                    },
                    lo: FlowEnd::Join,
                },
                FlowThread {
                    up: FlowEnd::Vertex {
                        vertex: FlowVertexIndex::from(1_usize),
                        port: FlowPortIndex::default(),
                    },
                    lo: FlowEnd::Join,
                },
            ],
            convexity: ConvexityDischarge::LeftConnectedOverAcyclicTarget,
        };
        assert!(
            flow.canonical().is_none(),
            "a tie in the key is refused, never broken arbitrarily"
        );
        assert!(
            !bool::from(flows_equal(&flow, &flow)),
            "and the refusal surfaces as a negative, which is the conservative direction"
        );
    }

    #[test]
    fn a_flow_taken_under_a_different_discharge_is_not_identified()
    {
        let empty = Flow {
            labels: Vec::new(),
            threads: Vec::new(),
            convexity: ConvexityDischarge::LeftConnectedOverAcyclicTarget,
        };
        let rechecked = Flow {
            labels: Vec::new(),
            threads: Vec::new(),
            convexity: ConvexityDischarge::ReCheckRequired,
        };
        assert!(
            bool::from(flows_equal(&empty, &empty)),
            "one discharge identifies a flow with itself"
        );
        assert!(
            !bool::from(flows_equal(&empty, &rechecked)),
            "and the fence is part of the flow, so two discharges never identify"
        );
    }

    /// (add-S): ⟨Succ(m) | add(n; α)⟩ ~> ⟨m | add(n; Succ⁻(α))⟩.
    fn add_s() -> Cell
    {
        let lhs = CmdPat::cut(
            Polarity::Positive,
            ProdPat::ctor("Succ", [ProdPat::meta("m")]),
            ConsPat::op("add", [ProdPat::meta("n")], ConsPat::meta("alpha")),
        );
        let rhs = CmdPat::cut(
            Polarity::Positive,
            ProdPat::meta("m"),
            ConsPat::op(
                "add",
                [ProdPat::meta("n")],
                ConsPat::frame("Succ", ConsPat::meta("alpha")),
            ),
        );
        Cell::new(
            lhs,
            rhs,
            Orientation::PolarityDerived,
            CellProvenance::SurfaceRule,
        )
    }

    #[test]
    fn a_two_step_leg_and_a_one_step_leg_have_different_flows()
    {
        // The fused-certificate gap, at the sequent alphabet: the two-step leg
        // has two vertices and the fused leg one, so no re-indexing can make
        // the label lists agree. The full statement — that the two are
        // replay-equivalent while being flow-distinct — is the integration
        // suite's, which has an alphabet with more than one address.
        use gandr_theory_coherent_resolutions::overlap::OverlapKind;
        use gandr_theory_coherent_resolutions::overlap::enumerate_overlaps;
        use gandr_theory_coherent_resolutions::tracelet::derive_fused;

        let mut store = CellStore::new();
        let frame = store.insert(frame_defining_cell(&Sym::new("Succ")));
        let add = store.insert(add_s());
        let composition = enumerate_overlaps(&store)
            .into_iter()
            .find(|overlap| {
                overlap.kind == OverlapKind::Composition
                    && overlap.left == frame
                    && overlap.right == add
            })
            .expect("the composition overlap exists");
        let (_fused, tracelet) =
            derive_fused(&composition, &mut store).expect("the fused cell derives");
        let projected = tracelet_flow(&tracelet, &store).expect("both legs project");
        assert_eq!(2, projected.path_a.labels.len(), "the two-step leg");
        assert_eq!(1, projected.path_b.labels.len(), "the single fused step");
        assert!(
            !bool::from(legs_flow_equal(&tracelet, &store).expect("both legs project")),
            "one boundary, two flows: the projection is strictly finer than the boundary"
        );
    }
}
